### ISSUE TITLE
File length getting doubled

### ISSUE THREAD

**Issue by Selenne** [Anime4000/IFME#100]
I have a problem in which after encoding, the file length gets doubled, and when I play it, after the initial time (half of that new file length) it just stops playing. I understand it ended, because it was only that long from the beginning, but why it shows that the file is two times longer???

Also I am using IFME to compress game recordings. Are there any presets for that? Or any suggested  settings I should use to get the best quality and size?

**Comment by Anime4000** [comment]
I afraid `temp` folder get messed, or compression not even effective from the source.

compress game recording is depending from the source, for example FPS will have busy motion, which is hard to compress unless there are motion blur. then you can use least `slow` preset @ `28` crf

**Comment by Selenne** [comment]
The thing is, that the file size gets smaller. It seems it got compressed just something weird happens to the length.

Thanks for the advice! I'll try it out next time.
