### ISSUE TITLE
Prototype feedback

### ISSUE THREAD

**Issue by SailorOnDaTea** [Anime4000/IFME#101]
ifme v7. unpacked it under its own folder on desktop and ran.

downloaded video and audio stream separately from internet with m4v and m4a extensions.

added m4v but under audio tab can not add sound file.

when i click start, 2 cli windows self close, third one starts with encoder but it won't pause or stop with GUI button. I have to close cli window with [X] button. however it is good thing this time GUI remains open.

when i choose 853x480 resolution, it wont encode, third cli window also closes itself. Then I chose 800x600, it worked.

it gives output files even after i close cli before it finishes.

**Comment by Anime4000** [comment]
you said m4v and m4a which is video and audio
you should add m4a into audio not m4v

**Comment by SailorOnDaTea** [comment]
my bad  my bad . i meant to say it doesnteven open "open file" window.

**Comment by Anime4000** [comment]
I didn't add code on that part yet, I currently testing encoding process
