### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by YellowHerbz** [Anime4000/IFME#105]
While trying to add videos to the queue, it states that it can't find the specified path. When I add the folder that is missing, it states that access is denied. I tried moving it to a different folder, the same thing happens. I attempted to run the program as an admin, same results. This issue only seems to occur on builds before 6.1, which are the most stable builds, which is disappointing. This appears to be a problem on my side since I don't see anyone else having the same problem. Does anyone know how to fix this?

**Comment by Anime4000** [comment]
file name can cause issue, like in linux, file name cannot contain `'` character

**Comment by YellowHerbz** [comment]
None of files contain any characters like that.
