### ISSUE TITLE
How to update x265 encoder?

### ISSUE THREAD

**Issue by canbonbon** [Anime4000/IFME#109]
Just downloaded and started using this wonderful tool. A couple of issues.
1) It is only taking ffmpeg 32 bit version even though I am on 64 bit Windows/Processor. Could you tell me where is the configuration file to fix that?
2) It is also saying update available for the x265 encoder. So not sure how to download and install it. Any pointers would be great.

Thanks

**Comment by Anime4000** [comment]
simply replace x265
x265-08 is for 8bit
x265-10 is for 10bit
x265-12 is for 12bit

need to rename based on encoder bit and replace it

x265 builds:
http://x265.ru/en/builds/
https://builds.x265.eu/

**Comment by canbonbon** [comment]
Thank you. Could you also let me know how I can activate 64 bit ffmpeg? It is only using the 32 bit one.

**Comment by canbonbon** [comment]
There are 3 folders for x265. Do you know which folder to replace in? x265gcc, x265icc, x265mvsc

**Comment by canbonbon** [comment]
Ok found it. There is a checkbox in the settings to use the 64 bit version.

**Comment by Anime4000** [comment]
nice 👍 
x265gcc is x265 compiled under GNU GCC
x265icc is x265 compiled under Intel C Compiler
x265mvsc is x265 compiled under Microsoft Visual C Compiler

**Comment by canbonbon** [comment]
Thank you. Also, the IFME GUI keeps saying "Attention: A new version is available. Click here to update". But  when I click there, it takes me to IFME website and the version there is same as mine. Is there any other location where the newer version is available?

**Comment by canbonbon** [comment]
For some reason I am getting this error on one of the files. Can you recommend what I am doing wrong here? The mkv file that gets generated is only 7 bytes due the error below.

'E:\Downloads\tmp\ifme\video0000_und.hevc' track 0: Extracted the aspect ratio information from the HEVC video data and set the display dimensions to 1920/1040.
Error: Re-rendering track headers: data_size != 0 not implemented yet. This should not have happened. Please contact the author Moritz Bunkus <moritz@bunkus.org> with this error/warning message, a description of what you were trying to do, the command line used and which operating system you are using. Thank you.
Clearing temp folder: E:\Downloads\tmp\ifme
[2017/01/06 04:47:48] Completed in 2h 23m 52s 496ms for C:\Users\xxxx_000\Downloads\convertedfiles\xxxxx (xxxx).mkv

Thanks

**Comment by canbonbon** [comment]
So I tried this again. The converted HEVC file was still in the tmp folder along with the extracted audio file in mp4 format. I just used MKVToolNix to combine them and final mkv file plays just fine. So looks like it converts the file fine but at the last step when it is trying to combine the audio+video something goes wrong. I would appreciate any input.

**Comment by Anime4000** [comment]
probably need to use older mkvtoolnix,
