### ISSUE TITLE
Format Profile Compatibility

### ISSUE THREAD

**Issue by winedog** [Anime4000/IFME#110]
I am having an issue with the format profile that IFME uses on video encoding.

Encoded videos show the following format profile:

@L4@Main

However, most hardware media players cannot display the video when this format profile is used.

Is there a way to change the format profile in IFME to:

Main@L4@Main

or to 

Main 10@L4@High

**Comment by Anime4000** [comment]
maybe x265 ship with have issue, try do manual update
