### ISSUE TITLE
UI not DPI aware?

### ISSUE THREAD

**Issue by ghost** [Anime4000/IFME#111]
Using win 7 @ 4k res and it`s impossible to see what the icons are,there is no hover information.Is the UI dpi aware?

**Comment by Anime4000** [comment]
I am aware about this, for current version was not DPI aware

**Comment by Anime4000** [comment]
IFME using Win32 Toolkit for GUI. When DPI is over 100%, Win32 begin to enlarge `bitmap` rather than `font`.

either I can try update to use `font` or...
move to better GUI Toolkit such as `ETO Toolkit`, `GTK`, `WPF`, which is I need re-write GUI code. This will be next generation of IFME `v8.0`
