### ISSUE TITLE
IFME has stopped working on 12core Dual Xeons

### ISSUE THREAD

**Issue by mrmorg** [Anime4000/IFME#112]
Hi on version 6.1 and when opening i get:
Unhandled Exception System Index is out of range exception  and it exits. 

System is a Dual Xeon Hex Core X5670 with 12cores plus HyperThreading running Server 2012.
please help.

6.1 works fine on my other machine (i7 6700K)

**Comment by Anime4000** [comment]
you have server? wow, I look this problem

**Comment by mrmorg** [comment]
Yh its a Dell T710 
Dual Zeons Hex core X5670 with 12cores plus HyperThreading running Server 2012.
24Gb Ram
40Tb Storage

**Comment by mrmorg** [comment]
any updates?

**Comment by mrmorg** [comment]
any way of getting IFME working??

**Comment by Anime4000** [comment]
sorry for late reply, actually I dont have much time, so I try to make it 👍 
next week (monday, GMT+8) I will be release IFME v7 beta, this beta will dont have much feature like 6 dose, my aim to make encoding stable as possible, after that I will add feature bit by bit

preview: https://www.facebook.com/internetfriendlymediaencoder/photos/a.290051507842046.1073741828.290041474509716/690724511108075/?type=3

**Comment by finalight** [comment]
ifme is able to utilize all the 12 cores? wow i'm impressed

I was thinking is it possible to do it in a distributed system or not

**Comment by Anime4000** [comment]
you mean, single video file, multiple computer?

**Comment by finalight** [comment]
yes that's what i mean
one video file -> let 3 to 5 computer convert parts of it then join them together 
or something like that

**Comment by mrmorg** [comment]
Any update on V6?? its still not working on my server....

**Comment by mrmorg** [comment]
![ifme error](https://cloud.githubusercontent.com/assets/16198405/25692942/18df1130-309e-11e7-8e89-1aeb64e33816.png)

**Comment by thefinaldegree** [comment]
You should try v7, it's good

**Comment by Anime4000** [comment]
you can get v7 here:
https://github.com/Anime4000/IFME/releases/tag/v7.0-beta

**Comment by SailorOnDaTea** [comment]
with dual cpu you may need to adjust thread pooling or "numa" nodes? if ram slots are dedicated for different cpu. it was about x265 encoder rather than ifme.

**Comment by Anime4000** [comment]
Try version 7.6...
I compile x265 with NUMA support for Windows and Linux, so x265 can distribute workload for each CPU socket
