### ISSUE TITLE
xml file 

### ISSUE THREAD

**Issue by finalight** [Anime4000/IFME#115]
for linux headless, I need to run ifme with xml file

however, i tried with a GUI desktop and don't see any options for xml generation..may I know where is it?

**Comment by Anime4000** [comment]
you mean xml of video list?

**Comment by finalight** [comment]
```
To run IFME with no desktop, execute ./ifme -c -i inputfile.xml, you need generate XML file via GUI first
```

was referring to this....possible to generate the XML on windows then use this list on linux machine?

**Comment by Anime4000** [comment]
it's possible, but you need to edit it first, by change only `file path`, since windows and linux are different
