### ISSUE TITLE
Original .webm file is smaller than resulting x265 .mkv

### ISSUE THREAD

**Issue by slrslr** [Anime4000/IFME#116]
Hello,

thx for nice IFME.

I wanted to ask why the original .webm file is smaller than HEVC encoded .mkv file?
Original (webm): 25mb, resulting (mkv): 26mb

On Picture tab i have default settings: auto, auto, 8, 420
On Video tab i have: medium, off, 26
On Audio tab i have: 128 bit rate set

Screenshot: https://snag.gy/cQHZu9.jpg

Does IFME wrongly detect bit rate?

If this is not issue, it can be closed. Thank You

**Comment by Anime4000** [comment]
encoding file already encoded is likey file getting bigger,
if original has pixel artifact cause by compression, when coding, that artifact become as new image, encoder doesn't know that was an artifact.

to overcome this, you need trade with `time` which is encode in `veryslow` preset, this will try to detect image artifact and copy as is.

**Comment by thefinaldegree** [comment]
You are correct. VP9 is a fairly similar, if simpler, codec.
x265 really is made for HD content and that's really where it'll start to
outperform VP9. Also x265 supports resolutions much past HD & 4K.
