### ISSUE TITLE
Hibernate/sleep does not work on Windows 10 64bit if the conversion job is paused

### ISSUE THREAD

**Issue by slrslr** [Anime4000/IFME#117]
Hello,

when i am encoding multiple files in IFME and want to pause encoding, there is pause button, but on my Windows 10 Home 64bit i can not sleep/hibernate my computer when it is paused. The computer start sleeping when i stop the job instead of pausing. But stopping the job makes little mess because i need to worry where i ended and if IFME will replace, reencode file that was last interupted right?

Thx

**Comment by Anime4000** [comment]
way I wrote code to pause encoding, I ask `Win32 API` to HALT `ffmpeg.exe` and `x265.exe`. it should work by putting computer on sleep or hibernate

**Comment by slrslr** [comment]
In my case when i pause IFME i see the x265 process in the Process Explorer: https://s30.postimg.org/6vpvzajrl/x265-08.jpg

**Comment by Anime4000** [comment]
It should sleep if computer in idle, not sure now Win32 API handle `suspended` process that cause auto sleep not work
