### ISSUE TITLE
Automatic bitrate for the audio?

### ISSUE THREAD

**Issue by slrslr** [Anime4000/IFME#118]
Hello, it is not possible to let the IFME auto detect bitrate of the audio?

I see i can auto detect frequency and channel, but not auto detect bit rate. When i add many videos into IFME to be decoded, these videos usually have various audio bit rates and it is quite tedious job to discover and set proper bitrate for each file in IFME so i encode each video with the best audio bit rate.

I usually want same bitrate or similar bitrate as original. Any possibility please to make IFME auto detect proper audio bit rate?

a work around would be for MS Windows to open folder with video files, select "Detailed" view of the icons. Right click the columns (like when you want to sort files) and select to add new columns and there enable ones for: Bitrate, Data speed (i do not know how they are named in english, i have different language Win.) then i can sort files according to audio bit rate and add into IFME only groups of files that have similar bit rates and do the task in batches. But automatic detection of the audio bit rate would be handy in IFME i think.

**Comment by thefinaldegree** [comment]
This was added some time ago, you can select audio passthrough so that you
don't need to re-encode the​ audio.

**Comment by slrslr** [comment]
I think that the Audio bit rate setting in IFME does not enforce this exact bit rate be used in encoded video file, but maybe instead it sets highest possible bit rate that will be used.

When i set Bit rate 512 and original video seems to be 384 kbps, resulting (encoded) video is also 384kbps. So this Audio bit rate IFME setting was misleading for me.

> select audio passthrough

Thx, yes, i already have Passthrough option set next to "Encoder:" on "Audio" tab.

**Comment by Anime4000** [comment]
way IFME detect only raw data, which is `decoded`, IFME only see Frequency, Bit Depth and Channel, much better if copy audio stream if you are output to MKV. I try to add this feature.
