### ISSUE TITLE
Error dialog box

### ISSUE THREAD

**Issue by NoRRt** [Anime4000/IFME#122]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at ifme.Branding.Banner(Int32 width, Int32 height)
   at ifme.frmMain.DrawBanner()
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.PictureBox.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ifme
    Assembly Version: 7.1.6377.40092
    Win32 Version: 7.1
    CodeBase: file:///C:/Internet.Friendly.Media.Encoder.7.1.0.0/ifme.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.0.0
    CodeBase: file:///C:/Internet.Friendly.Media.Encoder.7.1.0.0/Newtonsoft.Json.DLL
----------------------------------------
FFmpegDotNet
    Assembly Version: 0.11.0.0
    Win32 Version: 0.11
    CodeBase: file:///C:/Internet.Friendly.Media.Encoder.7.1.0.0/FFmpegDotNet.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Anime4000** [comment]
this seem error about banner picture that I use, I look into this :)

**Comment by NoRRt** [comment]
Internet Friendly Media Encoder v7.2 ('Enchantress')
Release: IFME v7.2 amd64 windows

(c) 2017 Anime4000, FFmpeg, MulticoreWare, VideoLAN, GPAC
Xiph.Org Foundation, Google Inc., Nero AG, Moritz Bunkus, et al.

Warning, DO NOT close this Terminal/Console, all useful info will be shown here.

Updating user settings.
Loading plugins complete!

# ifme [erro]: Error to redraw banner, missing/no permission? Parameter is not valid.

**Comment by Anime4000** [comment]
this error can ignore 👍

**Comment by Anime4000** [comment]
this bug has been fixed on IFME 7.4 😅 
re-open this issue if found

**Comment by AraHaan** [comment]
Wait a minute...
> Win32 Version: 4.7.2053.0 built by: NET47REL1

is this what I think it is? the version for .NET Framework 4.7.1? I am looking for the raw binaries for 4.6.2 instead and found these in place of them on my system and I want to ILSpy them to look at the resources in them. 🤔

**Comment by Anime4000** [comment]
IFME compiled on .NET 4.0 for compatibility and Mono Support.
IFME.exe is .NET assembly/bytecode, not binary machine code
