### ISSUE TITLE
See eRROR

### ISSUE THREAD

**Issue by NoRRt** [Anime4000/IFME#123]
nternet Friendly Media Encoder v7.2 ('Enchantress')
Release: IFME v7.2 amd64 windows

(c) 2017 Anime4000, FFmpeg, MulticoreWare, VideoLAN, GPAC
Xiph.Org Foundation, Google Inc., Nero AG, Moritz Bunkus, et al.

Warning, DO NOT close this Terminal/Console, all useful info will be shown here.

Updating user settings.
Loading plugins complete!

# Click minimize Program IFME :  ifme [erro]: Error to redraw banner, missing/no permission? Parameter is not valid.

**Comment by Anime4000** [comment]
This error can ignore
