### ISSUE TITLE
x265 crashes with IFME 7.3

### ISSUE THREAD

**Issue by L0Lock** [Anime4000/IFME#129]
Hello again ! 😄 
Since the 7.3 update, x265 randomly crashes sometimes during the encoding process, no matter what file is encoded or the encoding %. With that error in the console :

```
av_internkeaved_write_frame(): Broken pipe.64kb/s eta 0:32:30
Error writing trailer of pipe:: Broken pipe
```
Google told me it's a ffmpeg issue, so i tried to download the latest version, then an older one, but no success.

Thanks for your help.

**Comment by Anime4000** [comment]
IFME using nightly builds rather than stable builds.
You can get latest plugin package here
https://sourceforge.net/projects/ifme/files/plugin/

if still don't have auto update like before

**Comment by L0Lock** [comment]
I'll try this asap. Thanks for your fast reply.

**Comment by L0Lock** [comment]
Still crashes :'(

**Comment by Anime4000** [comment]
@L0Lock try use stable builds of x265 and FFmpeg?
both of them I use nightly builds

**Comment by L0Lock** [comment]
I try "ffmpeg 3.3.2" and "x265 2.4+13 Stable" now, I'll come back at the end of the job. Hope it'll work.

**Comment by L0Lock** [comment]
Ok, i end up with a mkv file with audio and subtitles only. No error in the console.
I notice that the files I downloaded doesn"t have the same names as those in the plugin folder. Maybe I have something to do with that ?

**Comment by Anime4000** [comment]
better replace x265 files inside plugin folder.
did you try copy `command-line` that IFME print? and test using cmd?

**Comment by Anime4000** [comment]
can you try with IFME 7.4?

**Comment by L0Lock** [comment]
This new release comes out at the right time, I just got an awfully heavy anime to encode properly. Like average 1GB per 20min episode...
I'll come back asap after encoding this.

**Comment by L0Lock** [comment]
Ok, the first video encoding just finished, didn't crashed, but i got this error instead :

`[matroska @ 00000000027cda00] Attachment stream 3 has no mimetype tag and it cannot be deduced from the codec id.
av_interleaved_write_frame(): Invalid argument
Error writing trailer of G:\encode\out\Clannad\Clannad 01 VostFr.mkv: Invalid argument
frame=    1 fps=0.0 q=-1.0 Lsize=       5kB time=00:00:06.73 bitrate=   5.5kbits/s speed= 498x
ifme [erro]: Damn! Video encoder make a mistake! Not my fault!`

Also, i noticed hundreds of yellow `Error parsing slice header: byte_align not found at end of header !` right after that :
`ifme [info]: Run command: "C:\AppInstl\Internet Friendly Media Encoder\plugin\mp4box\mp4box" -add "video0000_jpn.h265#video:lang=jpn" -new "video0000_jpn.mp4"
HEVC import - frame size 1920 x 1080 at 23.976 FPS`

In the output folder, i have an almost empty and unreadable mkv file, next to a "_videoname.raw_" folder containing, i guess, all the raw streams and attachments supposend to be merged in the mkv file.
I guess i just have to do something with mkvtoolnix or something.

**Comment by Anime4000** [comment]
"broken pipe" error happen during x265 encoding. is it right?
I working on 7.5 because of this issue, adding back `mkvmerge`.

ifme been using nightly update for x265, error  can be unpredicted either missing `pts` or unfinished end frame, you can replace with stable release x265, see how it goes.

**Comment by L0Lock** [comment]
Yup it's right.
I tried stable x265, still fails at merging. :'(

**Comment by Anime4000** [comment]
for this kind of issue, if Mkvtoolnix fail, IFME will try copy raw file to output path.
need mkvtoolnix return error code so that can trigger copy raw.

if there any other muxer except FFmpeg, make thing easy, since FFmpeg can't add attachment into mkv.

However, try it on version 7.6. this issue remain open

**Comment by L0Lock** [comment]
Hello again.

During the last few days I've been doing reencoding of about ~100 japanimes and movies files with IFME 7.6 and all of them have been well processed without error nor crash.

I think it's safe to say for now that the problem is solved.

And, for the sake of boasting, here are some stats :

![dkm7jmp 1](https://user-images.githubusercontent.com/16049822/34151860-f680b062-e4ac-11e7-9c9d-4f3f9cd5c548.png)
![79ek7ov 1](https://user-images.githubusercontent.com/16049822/34151883-08afa8c4-e4ad-11e7-9f58-14796c810c9b.png)
![oilhijt 1](https://user-images.githubusercontent.com/16049822/34151901-1a0ef4ee-e4ad-11e7-8a7c-ba0277e3f552.png)

My HDD thanks you !

**Comment by Anime4000** [comment]
I can safely close this issue 😄

**Comment by mikelimtw** [comment]
@Anime4000 
I'm using the lastest 7.7 build of IFME and I am getting this error also. So whatever you did between 7.6 and 7.7 it got broken again.

**Comment by Anime4000** [comment]
x265 crash?
