### ISSUE TITLE
Why is PSNR enabled in tune settings

### ISSUE THREAD

**Issue by L0Lock** [Anime4000/IFME#130]
Hello again.
I noticed IFME's presets use the PSNR tune settings.
But I learned in some forums (like [there](https://forum.videohelp.com/threads/344451-the-meaning-of-various-tunings-in-x264)) that PSNR is mostly for debugging and testing the encoding settings as it disables psychovisual settings. And that it should not be set on for normal use.

I'm not an expert of video encoding, so I can't tell if it's bad or wrong. I guess it's in IFME's presets for a reason, and I'd enjoy to know it.
Thanks for your reply.

**Comment by Anime4000** [comment]
just give a little bit smaller file size.
you can change `_plugin.json`
```
    "Tune": [
      "off",
      "psnr",
      "ssim",
      "grain",
      "zerolatency",
      "fastdecode"
    ],
    "TuneDefault": "psnr",
```
from `"TuneDefault": "psnr"` to `"TuneDefault": "off"`

**Comment by L0Lock** [comment]
Ok thank you.
