### ISSUE TITLE
'own' is neither a valid iso639-2 error

### ISSUE THREAD

**Issue by melphonese12** [Anime4000/IFME#132]
Hi,

I found an issue in which videos (output->HEVC) with unknown/undefined audio track language causes mkvmerge to fail merging the video/audio/etc. 

The error message:

> Error: 'own' is neither a valid ISO639-2 nor a valid ISO639-1 code. See 'mkvmerge --list-languages' for a list of all languages and their respective ISO639-2 codes.
> ted2mkv: mkvmerge failed

The failed process produces a folder on the destination containing all the output files albeit split individually e.g. video0000und.hevc/audio0000_unknown.m4a/etc.

 The solution is quite easy. Go to the audio tab and define the language. However I find this quite a hassle specially when I'm batch converting 5+ videos. The command line parameter also applies individually for each video so this is even more of a hassle.

I hope there would be an option in future updates wherein you can set the default language or cmd line parameters globally in the settings.

Thank you. Cheers. And great program 5/5

**Comment by Anime4000** [comment]
soon I update valid language list.

> However I find this quite a hassle specially when I'm batch converting 5+ videos.
> The command line parameter also applies individually for each video so this is even more of a hassle.
You can `Select All` in Main list or Video/Audio list, and apply settings. If you `Select All` in main list, simply change settings and add command-line, automatically apply all video and all streams.

**Comment by Anime4000** [comment]
FFmpeg Probe give invalid ISO639-2 code, IFME will change to `und` by default (hard coded).
