### ISSUE TITLE
Please bring back remaining time when encoding (7.4)

### ISSUE THREAD

**Issue by AbdalAliy** [Anime4000/IFME#135]

**Comment by Anime4000** [comment]
remaining time can be view on Console/Terminal window

**Comment by AbdalAliy** [comment]
If I encode > 1 file, only the first file is displaying the remaining time & frames
Below is the screenshot from 2nd file
![ifme_2017-08-22_14-13-09](https://user-images.githubusercontent.com/19300357/29553143-3a019106-8744-11e7-8049-7de1a38c5199.png)

**Comment by Anime4000** [comment]
this remaining time disappear because
* Multi-pass encoding (*if `--frames` not equal with 1st pass, encoding stop*)
* VFR (Variable Frame Rate)
* Broken AVI
* Frame Rate set to `Auto`

**Comment by Anime4000** [comment]
version 7.6 fix this missing remaining time (if not using multipass encoding).
For FFmpeg base encoder, sorry.
