### ISSUE TITLE
Windows build Zip file is corrupted

### ISSUE THREAD

**Issue by douglasg14b** [Anime4000/IFME#139]
The zip file for the current build download cannot be extracted on any of my devices, I recieve a `error 0x80004005` error upon extraction of any of the DLLs. I've tried this on 4 different devices with varying versions of Windows thus far.

Specifically the `ifme7.4-amd64_win-linux.zip` download. `7.3` extracts just fine

**Comment by Anime4000** [comment]
have you tried different mirror?

or you can check using checksum.
File: ifme7.4-amd64_win-linux.zip
SHA1: `ff4622b21629e6bb33f74adff0053f4af41ad850`

or download from VideoHelp.com
`https://www.videohelp.com/software/Internet-Friendly-Media-Encoder`

**Comment by Anime4000** [comment]
For this issue, I use standard ZIP file (Deflate).
This because I use LZMA algorithm for maximum compression

If you use windows, you can use installer without needing Archive utility
