### ISSUE TITLE
Internet Friendly Media Encoder 7.5 

### ISSUE THREAD

**Issue by jjigoku** [Anime4000/IFME#141]
I use 7.5 64bit in Window 7 64bit to encode x265 10 ~ 12bit and x264, but all can not hardsub with .ass files.

**Comment by Anime4000** [comment]
IFME doing soft sub, for hardsub, please use [AviSynth Script HardSub](http://docs.aegisub.org/manual/Attaching_subtitles_to_video#Hardsubbing) and import script into IFME

**Comment by Username778** [comment]
At least can you add features for hardsubbing video? or tutorial importing script into IFME?

**Comment by Anime4000** [comment]
Okay, I can add this feature "Hardsubbing"

**Comment by Anime4000** [comment]
Done.... you can Hard Sub in version 7.6 😄
