### ISSUE TITLE
Feature Request: Add all files recursively from a folder and delete them when successfully encoded.

### ISSUE THREAD

**Issue by MycroftHolmes1989** [Anime4000/IFME#143]
I would love to have a batch convert feature where I can add files from a folder and its subfolders recursively, and the original files would be deleted if and when the files are successfully encoded. Whether the files are successfully encoded can be checked using FFMPEG. The destination path of encoded files would be same as original files, with a filename suffix like '_encoded' or something user-defined. A powershell/command-line script equivalent to this feature would be welcome as well.

**Comment by Anime4000** [comment]
this very neat feature! I will add this 👍

**Comment by MycroftHolmes1989** [comment]
Thank you. Looking forward to this feature. I have tonnes of movies and TV series waiting to be transcoded.

**Comment by MycroftHolmes1989** [comment]
Any progress on this? Any estimated time when this might be added?

**Comment by Anime4000** [comment]
I quite busy 😄 

I need setup my computer, someone from Japan donate his Xeon E3-1240 v3 processor and ECC RAM. make development faster since I use a lot of Virtual Machine to build and testing...

next month (November) will be release, v7.6
also good time to gather all bugs/issue, translation, everything that to improve IFME, so, compile into one large Bug Fix

**Comment by MycroftHolmes1989** [comment]
Cool. I have a few new features in mind that will be easy to implement but help the users extremely.

**Comment by Anime4000** [comment]
I made a changes, but deleting source file likely very dangerous, in case encoding fail or bad quality... 
![ifme_import-folder](https://user-images.githubusercontent.com/1908715/32182229-250dbdba-bdd1-11e7-9c40-acb8937b3a03.png)

**Comment by MycroftHolmes1989** [comment]
You may add a dialog box warning the user of the risks of deleting source files. Also, will the output files be placed in source file's directory? In other words, will the folder structure be preserved in outputs? Or will all the encoded files be placed in a single destination folder?

**Comment by Anime4000** [comment]
see "Destination" at bottom UI.
There where file being save, if you make it blank or invalid path, encoded file will be save where source file is.
