### ISSUE TITLE
Command Line Documentation

### ISSUE THREAD

**Issue by MycroftHolmes1989** [Anime4000/IFME#144]
It would be very helpful if the developer provided a command line documentation, no matter how basic, so that we can write scripts to batch convert videos. Just a simple documentation with simple argument list would suffice.

**Comment by Anime4000** [comment]
that will depend on encoder that you choose, I can add online help for each plugins via button

**Comment by MycroftHolmes1989** [comment]
Easier way would be to save an encoding preset and then to use the name of the preset in command line. Can that be done?

**Comment by Anime4000** [comment]
that already done, see `Encoding Preset`, press ⭐️ button, it will show sub-menu, either save existing or make new

**Comment by MycroftHolmes1989** [comment]
I already use that feature. I want to use that preset in command line. That would be easier to do than to write the whole encoding options in command line.

**Comment by Anime4000** [comment]
I can do that, can you give some example? I try to integrate

**Comment by MycroftHolmes1989** [comment]
Something like `IFME.exe -input <inputfilelocation> -output <outputfilelocation> -encode <encodingpreset>`. This would take the input file, encode it according to the encoding preset, and place the output file at output file location. This would be the simplest version of command line usage. There can be more advanced options, like mentioning the encoding options on the command line itself, but that isn't necessary though. Handbrake does have that option ,though. Here's their [documentation](https://handbrake.fr/docs/en/latest/cli/cli-options.html).

**Comment by Dcyperion888** [comment]
They keep ommiting mY work..I use a mobile phone. They use "SUPERDOOPERCOMPOOTERS' to kEEP me Off...wiLL i not be ProUd Ph.?
