### ISSUE TITLE
If input is .avs file, audio doesn't work.

### ISSUE THREAD

**Issue by Ryoandr** [Anime4000/IFME#145]
I get error

    Unknown error occurred    

on encoding audio, regardless of number of channels or codec.

**Comment by Anime4000** [comment]
Try use `FFAudioSource` if input source audio give a problem.
I recommend use `FFVideoSource` and `FFAudioSource` if `DirectShowSource` didn't work...
Note that `DirectShowSource` is follow codec installed on your computer, if Windows Media Player can play, `DirectShowSource` also can 😄

**Comment by Ryoandr** [comment]
just tried indexing with `FFAudioSource`, same error.
Also tried `LSmashAudioSource` and `LWLibavAudioSource` from LSmash, same error.
The .avs file worked with IMFE6.

**Comment by Anime4000** [comment]
I think FFmpeg problem,

**Comment by Ryoandr** [comment]
Ok error happens because I'm using 32bit Avisynth.
IFME tries to encode audio in .avs file with FFMPEG 64bit, that's why it fails.
An option is needed to force IFME to use 32bit FFMPEG encoder if 32bit Avisynth is used (the current one for decoder isn't enough), at least for audio.
I can't switch to avisynth 64bit yet...

**Comment by Anime4000** [comment]
by default IFME use 32bit FFmpeg.

I think this good idea if split AVS and non-AVS option to choose 32/64, what do you think?

**Comment by Anime4000** [comment]
Actually... you can do this way if you didn't use any Audio enhancement on AviSynth.

1. Import script into IFME
2. In Audio Tab, if no stream, you can import original file (outside script), IFME will capture audio inside file

then encode as usual...
