### ISSUE TITLE
Resize video and Hardsubbing

### ISSUE THREAD

**Issue by Username778** [Anime4000/IFME#147]
Let's to the point...
Did you know how to resizeing video at IFME and Hardsubbing it?
I already add subtitle that want to hardsub at IFME but when i play it no subtitle at all.

**Comment by Anime4000** [comment]
IFME using softsub, require codec filter to support

**Comment by Username778** [comment]
How about resizing? When i change resolution it says missing picture in access unit.

**Comment by Anime4000** [comment]
this will generate avs script for hard subbing

**Comment by Anime4000** [comment]
Version 7.6, you can hard sub without needing AviSynth, simply tick Hard Sub and start encoding 😸
