### ISSUE TITLE
[ENHANCEMENT] NVENC HEVC support

### ISSUE THREAD

**Issue by MycroftHolmes1989** [Anime4000/IFME#148]
Dropping `h264nvenc.ffmpeg` in `Plugin` folder enables NVENC H264. Any such plugin available for NVENC HEVC?

**Comment by Anime4000** [comment]
it uses FFmpeg to encode, I'll check soon if FFmpeg support NVENC HEVC

**Comment by MycroftHolmes1989** [comment]
FFMPEG does support NVENC HEVC. Please note that the latest version of NVENC HEVC has lots of features specifically for Pascal series GPU. Kindly enable these features in IFME frontend when a Pascal Series Graphics Card is detected.

**Comment by Anime4000** [comment]
sadly I dont have nvidia GPU, I can put code here to you try

**Comment by MycroftHolmes1989** [comment]
No problem. I'd be happy to test them.

**Comment by L0Lock** [comment]
Me too ! :)

**Comment by Anime4000** [comment]
Guys! Here the latest Hardware Acceleration... Support:
* AMD AMF (GPUOpen)
* Nvidia NVENC
* Intel QuickSync

I test AMD part, it should work perfectly! Not sure on Nvidia or Intel since I don't have these hardware yet, but you can try and edit JSON file to make it work, don't forget to report here 😄 

Download:
https://sourceforge.net/projects/ifme/files/plugin/plugin-hwenc_2017-12-12_amd64.zip/download

**Comment by L0Lock** [comment]
Hi again.
On IFME 7.6 Windows 10 with a nvidia GTX 970 gpu and Intel i7 4790 cpu, I extracted the plugin folder's content into IFME's Plugin folder. So it looks like this :
![ldgjfyx 1](https://user-images.githubusercontent.com/16049822/34108830-e205d5dc-e401-11e7-8bf9-69ab2fa5dd48.png)

Then launched IFME. I watched the console during the startup and I haven't seen the new plugins being loaded. Once IFME ready for use, there are no NVENC nor Intel QuickSync in the encoding options nor the module list.
![neroyc1 1](https://user-images.githubusercontent.com/16049822/34108916-4660eed6-e402-11e7-934a-f5798a7548c5.png)

I also tried to shut down IFME, keep only one .json file (h265 nvenc) and restart IFME but it doesn't work either.
 I have no idea of what I'm supposed to do with the JSON file as I'm not a programmer. 😛 But maybe I

**Comment by Anime4000** [comment]
are you sure folder you extract is same program is running...
based on `H.262` and `H.263` it was inside `video.ffmpeg` folder

**Comment by L0Lock** [comment]
I'm not sure I understood your answer.
But I put the "_video.ffmpeg.gpu_"folder with all of its content into "_C:\Program Files\Internet Friendly Media Encoder\plugins_".

**Comment by Anime4000** [comment]
what I mean,
some user keep version for backward compatible.
since so many versions, mistake installing plugin can happen like wrong version install

**Comment by L0Lock** [comment]
OK I think I understood.
So I tried to completely uninstall IFME then reinstall it, followed by the NVENC plugin installation and now it's available in IFME. :)

I'll come back here as soon as I have some NVENC tests to provide.

**Comment by Anime4000** [comment]
great! I waiting for feedback

**Comment by L0Lock** [comment]
Feedback !
I tested Nvenc on some files, it works so well I'm crying. Great quality, fast encoding, all i want for a nvenc work. :)

**Comment by Anime4000** [comment]
nice 👍 ... have you try compare quality & compression between NVENC vs x265?

**Comment by L0Lock** [comment]
As usual, at equivalent compression settings, NVENC x265/x264 is more quality destructive than normal x265/x264. But it's a good enough quality compared to the fact that the encoding time is smaller and it has a small impact on the computer's performances.
