### ISSUE TITLE
[UI Enhancement] Add tooltips to controls

### ISSUE THREAD

**Issue by MycroftHolmes1989** [Anime4000/IFME#149]
Please consider adding tooltips to controls. Sometimes it's impossible to understand what a button does. For example, there's a new button that looks like speedometer, but I have no idea what that button does.

**Comment by Anime4000** [comment]
that speedometer refer to benchmark,

I didn't add `tooltips` because of updating language file

**Comment by L0Lock** [comment]
If you struggle with languages, I suppose the community around IFME would be happy to help for the translations of language files as long as you give us someting to work on.

**Comment by Anime4000** [comment]
all right, I add tooltips for next release. 👍

**Comment by L0Lock** [comment]
yay ! \o/

**Comment by Anime4000** [comment]
my english is bad, sorry :)

**Comment by L0Lock** [comment]
Mine too. But I'm a good fake. :x
