### ISSUE TITLE
Extra commandline for video not saved

### ISSUE THREAD

**Issue by DarkShadow44** [Anime4000/IFME#15]
When closing and reopening IFME, every setting gets saved and restored but the extra commandline for video encoding isn't.
I guess it's intention that IFME remembers the last configuration, so it would be convenient if the commandline would also be saved.

**Comment by Anime4000** [comment]
I think it conflict with `User Preset`
I made quick fix, I adding `Last saved configuration` under `User Preset`
https://github.com/Anime4000/IFME/blob/master/ifme/UserPreset.cs#L44-L60

for now try create own user preset :heart: it can save video command-line

**Comment by Anime4000** [comment]
Has been added since 4.9.4
