### ISSUE TITLE
Opus audio encoder not working in IFME 7.5

### ISSUE THREAD

**Issue by Monteco** [Anime4000/IFME#150]
It leaves an error message saying:
"F*uck! Video encoder make a mistake! Not my fault!"
Any way of fixing this?

**Comment by Anime4000** [comment]
hahaha. I believe that error message was in older version, you using what version?

**Comment by Monteco** [comment]
I'm using the newest version of IFME, running on Windows 7 64bit. I'm thinking maybe the problem is that the source uses FLAC 5.1 audio source?

**Comment by Anime4000** [comment]
I use FFmpeg to encode Opus, try make it stereo

**Comment by Monteco** [comment]
I tried on another computer running Windows 10 and encoding with opus still doesn't work, the error message I get is:
[libvorbis @ 0000000002575140] encoder setup failed
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

This is with IFME 7.5

**Comment by Anime4000** [comment]
can you share Media Info with me?

**Comment by Monteco** [comment]
File path          : C:\Users\01\Videos\PS4 - Death Stranding Trailer 4K (Hideo Kojima) TGA 2016.mp4
File size          : 195.9MB (base 10), 186.9MiB (base 2)
Bitrate            : 4843551
Duration           : 00:05:23 (estimated)
Format             : mov,mp4,m4a,3gp,3g2,mj2 (QuickTime / MOV)

ID                 : 00
Type:              : Video
Codec              : h264
Width              : 2560
Height             : 1440
Frame rate         : 30.000fps
Frame rate (avg)   : 30.000fps
Bit Depth          : 8bit per channel
Chroma             : 420

ID                 : 01
Type               : Audio
Codec              : aac
Sample rate        : 44100Hz
Channel            : 2Ch

The audio settings in IFME:
Encoder: Opus Encoder (FFmpeg)
Mode: Bitrate
Quality: 128000
Sample Rate: 44100
Channel: 0

Gives me this error:
[libopus @ 00000000028a0560] Specified sample rate 44100 is not supported
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
ifme [warn]: Audio encoding might have a problem!

Video encodes fine, but has no audio

**Comment by Monteco** [comment]
It doesn't matter which video file, it just won't encode in opus.

**Comment by Anime4000** [comment]
I think, FFmpeg try encode opus on stream 00 which is video, not audio, I'll check this

**Comment by Monteco** [comment]
Any progress?

**Comment by Anime4000** [comment]
I dont know why, when I test my self, it works fine...
I update to you

**Comment by Anime4000** [comment]
Version 7.6 is out, this should be fix this problem.
Feel free to re-open case if problem still there 😄
