### ISSUE TITLE
Mkv to mp4

### ISSUE THREAD

**Issue by YellowHerbz** [Anime4000/IFME#151]
ifme never seems to work. When i try to encode a x265 video back into mp4. Im pretty sure ifme just overwrites my settings so it encodes the video into mkv anyway. It has only worked once and that was on one video.

**Comment by Anime4000** [comment]
you need change to mp4 first

**Comment by Anime4000** [comment]
this kind of problem, I already fix on version 7.6
thank you for reporting this issue 🥇
