### ISSUE TITLE
"New version is available" keeps spawning in the latest version

### ISSUE THREAD

**Issue by L0Lock** [Anime4000/IFME#153]
This morning I downloaded the new IFME version as the "_New version is available_" invited me to do so.
But now I'm using version 7.6 and this "_New version is available_" keeps spawning at startup.

![k7uyac5 1](https://user-images.githubusercontent.com/16049822/34109214-29645114-e403-11e7-998b-a4a9b5ea82ea.png)

**Comment by Anime4000** [comment]
x265 2.6+13 ❤️ 
New version spawn is bug, I overlook the code, 😜 

https://github.com/Anime4000/IFME/blob/master/ifme/frmMain.Method.cs#L217

after check `data[0]` is not null,
should be
```
if (string.Equal(current, (string)data[0])
return
```

sorry... haha

**Comment by L0Lock** [comment]
Solved on version 7.7.
Thank you :)

**Comment by Anime4000** [comment]
no problem 👍
