### ISSUE TITLE
[Enhancement] Add a process priority controler

### ISSUE THREAD

**Issue by L0Lock** [Anime4000/IFME#155]
For now, IFME's process (and also the other programs used during encoding) is set to normal CPU priority. An advanced user would enjoy to change the cpu priority in order to speed up the task or to make multytasking easier (who doesn't love encoding an anime while smoothly watching an anime?). Thhe current way to do that is to manually set the cpu priority on each process through Windows's task manager, and this have to be done everytime the process restarts. It's long, repeative and, at the end of the day, quite anoying.

I think it would be nice if IFME could provide a kind of drop down menu allowing the user to change the CPU priority on the fly before or during the encoding process.
And it should do it no matter how mutch files are in queue and no matter which encoder is used.

That would be great.

PS : merry christmas & happy new year.

**Comment by Anime4000** [comment]
On older IFME has this feature.

**Option UX**
https://github.com/Anime4000/IFME/blob/ifme6/ifme/frmOption.cs#L56
https://github.com/Anime4000/IFME/blob/ifme6/ifme/frmOption.cs#L325
**Function Call**
https://github.com/Anime4000/IFME/blob/ifme6/ifme/TaskManager.cs#L142-L175

I drop this because I tried, set Normal to High not much improvement, set to Realtime cause freezing.

it's nice idea to add back since can do encoding while gaming/watching 👍

**Comment by L0Lock** [comment]
Yes. The result really depends on the computer and the other programms runing at the same time. It can do nothing as it can boost the encoding like hell or make a BSOD. That's why it's something that only advanced user should modify. Maybe you could display a waring message near it, like "**Danger zone!** You should use that setting at your own risk only if you know what you are doing".

For me I really speed up my encoding even by setting x265 at "above normal". Last night i set it to high and the video encoding went from 30fps to 60fps average. Speed x2 just by changing the CPU priority, that's a huge difference. :)

**Comment by L0Lock** [comment]
Intel i7 4790 with 16GB RAM and Nvidia GTX 970
And I still feel too slow. (:

**Comment by Anime4000** [comment]
I guess I using older AMD FX cpu, changing process priority no effect on older AMD... huhuhu...
okay, I add this for version 8.0 😈 (2018) xD XD
