### ISSUE TITLE
[BUG] Can't import anything in IFME 7.7

### ISSUE THREAD

**Issue by L0Lock** [Anime4000/IFME#156]
Huge bug :
I can't import any file into IFME since version 7.7, no matter the format. I even tried to import files encoded by IFME or files i could send to IFME 7.6.

Here what the console says :
```
FFmpegDotNet [warn]: Incompatible FFmpeg or Invalid file stream.
```

Windows 10, IFME 7.7 with fmmpeg gpu plugin (removing that plugin doesn't solve the problem).

**Comment by Anime4000** [comment]
This problem probably FFmpeg refuse to print XML about media info.

have you tried latest nightly builds Zeranoe FFmpeg?
at my end, no problem for FFmpeg print info about media.

**Comment by L0Lock** [comment]
It works !
Actually it didn't worked first, then I noticed I downloaded the 64bits ffmpeg into the 32bits ffmpeg plugin folder. Yeah I'm dum. x)

**Comment by Anime4000** [comment]
safe~~~
so I close this issue xD
