### ISSUE TITLE
Output files (mp4?) won't get saved to disk

### ISSUE THREAD

**Issue by jeremythille** [Anime4000/IFME#157]
IFME spends hours recompressing videos, says "Job completed successfully" but no new file appears in the specified output folder. Sometimes the compression works though, I suspect the bug concerns only MP4 input files for some reason.

**Comment by Anime4000** [comment]
may I know what version are you using?

**Comment by jeremythille** [comment]
Sure, at the moment : 6.1.0.0 x64 'Pixelaphobia'. I have updated it because of this bug, in hope the newer version would work better, but it's still here. Please note that it seems to happen only with MP4 input files. I have no problem re-encoding MKV or AVI.
(Absolutely terrific encoder, BTW. It works SO well and it's SO easy to use. It keeps all audio channels and all subtitles upon reencode, it's just the greatest job ever, hats off)

**Comment by Anime4000** [comment]
muxing raw files using FFmpeg instead of MP4box,
maybe you try in newer version

**Comment by jeremythille** [comment]
oh that's right, I thought it was the latest version, but actually now it's 7.7! I tried the latest version and now it works. Sorry about that.

**Comment by Anime4000** [comment]
thanks for your support!
