### ISSUE TITLE
Cannot use empty destination folder, again, in 7.7

### ISSUE THREAD

**Issue by AbdalAliy** [Anime4000/IFME#158]
Given path is wrong: The path is not of a legal form

**Comment by Anime4000** [comment]
this happen when I ask `IsValidPath();` to check is there any illegal characters or UNC.
You want Encoded File save where Source Files located?

**Comment by AbdalAliy** [comment]
yes, the same issue as https://github.com/Anime4000/IFME/issues/133

**Comment by MycroftHolmes1989** [comment]
When can we expect a fix for this bug?

**Comment by Anime4000** [comment]
I doing version 8, end of April you will have version 8.
