### ISSUE TITLE
"Turn off computer when done" should stay enabled while encoding

### ISSUE THREAD

**Issue by KaOs1** [Anime4000/IFME#16]
I don't see the reason why it gets disabled :smirk:

**Comment by Anime4000** [comment]
I can't force to enable, some user want to encode short video :smile: 
I think I didn't add that to presistent settings... I check it now.

**Comment by KaOs1** [comment]
Sorry, I meant enabled in the sense that it should not be greyed-out, so that the user can check or uncheck the option while encoding.

**Comment by Anime4000** [comment]
Oh! sorry for I missunderstand :cry: 
I'll fix this issue, on next release

**Comment by SharmaTushar** [comment]
I was just going to request this on Facebook page, then I saw a post about current issues.

**Comment by Anime4000** [comment]
Here: https://github.com/Anime4000/IFME/commit/aad9e8a148e0b0664d39665a37655c2efa26b6b4#diff-2ec2bd99006fb32eafdf34c3c3db49d2R2101

It will come in next release, version 4.9.4.
if urgent, I can compile for you :smile:

**Comment by SharmaTushar** [comment]
No, that won&#39;t be necessary. I just thought that I should request this, then saw it under already open issues.

**Comment by Anime4000** [comment]
Yeah... Thanks for remain me :smile_cat: 
Today I'll temporary patch, 4.9.3.2, let see if this issue is solved

**Comment by Anime4000** [comment]
This has been fixed :+1:
