### ISSUE TITLE
AviSynth + download not working

### ISSUE THREAD

**Issue by canbonbon** [Anime4000/IFME#160]
Hello, the AviSynth + download link is no longer working. There are way too many versions of AviSynth + floating around. I tried to download many, but I keep getting CRC error when I try to pick the 64bit version and then it defaults to the standard 32 bit version. I am therefore using the AviSynth 2.6 (32 bit version) for now. But it would be great if you could let me know which version of AviSynth + should I download so that IFME could recognize it.

**Comment by Anime4000** [comment]
Try this latest version...
https://www.videohelp.com/software/AviSynth-Plus

CRC Error mean nothing, just tell IFME don't know the version
there a file `avisynth.json` to determine version: https://github.com/Anime4000/IFME/blob/master/ifme/avisynth.json

**Comment by canbonbon** [comment]
Nope did not work. Tried everything. It just cannot use the 64 bit version and reverts to the 32 bit version. Not sure what configuration I am missing. If you could take a look and let me know then that would be great. Also, not sure if 64bit really buys me anything? Should I be chasing it or just forget about it and continue to use the 32 bit AviSynth.

**Comment by Anime4000** [comment]
most AviSynth plugins runs on 32bit, so IFME use 32bit by default.

maybe you can reset IFME config via `ifme.exe -r` and try set FFmpeg 64bit

**Comment by canbonbon** [comment]
Hello, I just installed IFE on another PC running Windows 10. It completes the conversion to HEVC but in the end dies with the following error: MSVCR100.DLL not found. MP4Box.exe gives that error. I looked into both System32 and SysWOW64 folders in Windows and I see that file is there. 

I have obviously tried reinstalling a couple of times but continue to get this issue. Any other suggestions what might be causing this error? Do I need to install MP4Box.exe separately?  Thanks for all your help as usual.

**Comment by Anime4000** [comment]
maybe you can try update `MP4Box.exe` from https://gpac.wp.imt.fr/mp4box/

if you using 64bit windows, you neeed check:
`System32\MSVCR100.DLL` (this is 64bit binary)
`SysWOW64\MSVCR100.DLL` (this is 32bit binary)

in 64bit Windows, yes... System32 folder is 64bit binary file... hahaha
so, you need install Visual C Runtime 32bit and 64bit...

I been thinking to drop MP4Box in the future because of this runtime issue,

**Comment by canbonbon** [comment]
Reinstalling MP4Box fixed it. 

Thanks for all your help.
