### ISSUE TITLE
Request for new feature "Audio normalization"

### ISSUE THREAD

**Issue by pasha-k402** [Anime4000/IFME#162]
Need CheckBox for all audio tracks, that will normalize volume peak to 0 dB for every track.
This project does something that i need https://github.com/slhck/ffmpeg-normalize 
Here is command line normalization for ffmpeg https://trac.ffmpeg.org/wiki/AudioVolume
Thanks, program very useful.

**Comment by pasha-k402** [comment]
Here is command line normalization for ffmpeg https://trac.ffmpeg.org/wiki/AudioVolume

**Comment by Anime4000** [comment]
great feature, I can add this on next release 👍
