### ISSUE TITLE
Crash when encoding video

### ISSUE THREAD

**Issue by Deadshot00** [Anime4000/IFME#164]
Hi, I'm new to ubuntu and I recently encountered an error when attempting to encode a video. Ubuntu 16.04 with IFME 7.7. It happened with 10bit x264 and 8  bit x264 as well. I installed Mono runtime. Here is a picture of the logs.
![ubuntuv2](https://user-images.githubusercontent.com/37586386/37661052-ea31dc6e-2c64-11e8-9ea1-a96b8596ebf1.png)

**Comment by Anime4000** [comment]
sorry... my bad.... hahaha it appear that I leave `.exe` on JSON file...

open `plugin/video.x265gcc/_plugin.json` and remove `.exe` then save
```
		"Encoder": [
			{
				"BitDepth": 8,
				"Binary": "x265-08.exe"
			},
			{
				"BitDepth": 10,
				"Binary": "x265-10.exe"
			},
			{
				"BitDepth": 12,
				"Binary": "x265-12.exe"
			}
```
Line 24, 28, 32

**Comment by Deadshot00** [comment]
I removed it and still got the same error

**Comment by Anime4000** [comment]
permission denied... try
`chmod +x x265-08`
`chmod +x x265-10`
`chmod +x x265-12`

**Comment by Deadshot00** [comment]
Thanks that fixed it. It is working now. How do I use Vapoursynth or Avisynth with ifme?

**Comment by Anime4000** [comment]
you need compile FFmpeg in linux to support it,

**Comment by Deadshot00** [comment]
I've compiled ffmpeg. Where do I add the scripts?

**Comment by Deadshot00** [comment]
I made a sample script as shown here: https://github.com/Anime4000/IFME/wiki/AviSynth but it can't be imported into the encoder. Nothing happens after importing the avs file

**Comment by Deadshot00** [comment]
I updated my avisynth + and it worked now to try it on ubuntu

**Comment by Deadshot00** [comment]
The encoder does not merge the output at the end of encoding. There is no error in the logs

**Comment by Anime4000** [comment]
Mkvmerge said it was success...
Avisynth in linux seem limited in term of avisynth library

**Comment by Deadshot00** [comment]
Will vapoursynth work with ifme?

**Comment by Anime4000** [comment]
not sure about vapoursynth, never been tested. since FFmpeg only read avisynth

**Comment by Anime4000** [comment]
I can add support if have proper linux decoder and pipe support.
like this: http://forum.doom9.org/showthread.php?t=167627
