### ISSUE TITLE
"ERROR: Not connected to the internet?"

### ISSUE THREAD

**Issue by L0Lock** [Anime4000/IFME#166]
When starting up IFME 7.7 I get the following error in the cmd prompt :

`ERROR: Not connected to the internet?`

I don't know what it's used for, but I can assure that I'm connected to the Internet.

-----

On Windows 10 Pro 64bit
Intel i7 4790
Nvidia GTX 970
16GB RAM

**Comment by Anime4000** [comment]
yes... it seem WebClient Service have issue.
I try looking other HTTP Client code to replace WebClient Service
