### ISSUE TITLE
Error parsing slice header: byte_align not found at end of header !

### ISSUE THREAD

**Issue by redking974** [Anime4000/IFME#168]
Hi, I've recently update IFME to the 7.7 version.
I was before on the 6.X because the 7.X was bugged on my system (Windows 10).

Now, it seems to work but after each conversion I got this yellow warnings. I post the end of my terminal :

> Error parsing slice header: byte_align not found at end of header !
> Error parsing slice header: byte_align not found at end of header !
> Error parsing slice header: byte_align not found at end of header !
> Error parsing slice header: byte_align not found at end of header !
> Error parsing slice header: byte_align not found at end of header !
> Error parsing slice header: byte_align not found at end of header !
> HEVC Import results: 199560 samples (199564 NALUs) - Slices: 1900 I 36235 P 161425 B - 1 SEI - 1 IDR
> Stream uses forward prediction - stream CTS offset: 2 frames
> OpenGOP detected - adjusting file brand
> Saving video0000_eng.mp4: 0.500 secs Interleaving
> ifme [info]: Processing RAW MPEG video file OK!
> ifme [info]: Merging RAW files as single media file
> mkvmerge v22.0.0 ('At The End Of The World') 64-bit
> 'C:\Users\XXX\AppData\Local\Temp\IFME\video0000_eng.mp4': Using the demultiplexer for the format 'QuickTime/MP4'.
> 'C:\Users\XXX\AppData\Local\Temp\IFME\video0000_eng.mp4' track 0: Using the output module for the format 'HEVC/h.265'.
> The file 'G:\TEMP\REMUX.mkv' has been opened for writing.
> Progress: 100%
> The cue entries (the index) are being written...
> Multiplexing took 51 seconds.
> ifme [info]: Yay! All media done encoding...

I also remark that the remaining time/ENA is no more displayed into the console

I don't know if it's IFME or x265 or mkvtoolnix, because it was perfect when I was on the 6.X
Here the plugins I change manually :
- x265-2.7+340-aa91024_gcc80-AVX2
- ffmpeg-20180412-8d381b5-win64-static
- AviSynthPlus-MT-r2664

If it's not related to IFME, forgive me to open this issue.

Regards

**Comment by Anime4000** [comment]
H.264 and H.265 raw bitstream will parse to mp4box...

why? because sometime mkvtoolnix can't read...

that yellow warning was normal, try play a video and see, see got any problem

**Comment by mikelimtw** [comment]
I'm getting this error on 7.7 currently. Is there a fix for this?

**Comment by Anime4000** [comment]
try use other build of x265.exe and replace it, see if working fine

**Comment by mikelimtw** [comment]
@Anime4000 
I'm not sure how to install newer plugin versions for IFME. Can you provide a link for me to read up on?

**Comment by Anime4000** [comment]
you can try this one: https://builds.x265.eu/

**Comment by mikelimtw** [comment]
I am using standard installation for IFME 7.7 ie I haven't changed or altered any of the plugins such as AviSynth etc.

I downloaded the nightly build for 2.7.351 and extracted the files into the x265 plugin folder. I backed up the original files and renamed the 2.7.351 files the same names as included files. I'm still getting the error. I will try the link above and see if that helps. I'll let you know after I try them out.

**Comment by MycroftHolmes1989** [comment]
Same here. Lots of files where the video and the current time freezes in the middle of the encoded output, but the audio works.

As an aside, any idea regarding how to find the defective output files?

**Comment by Anime4000** [comment]
I encode a lot using MKV as container, no problem, I using older x265.
for MP4, maybe MP4Box have issue?

**Comment by Anime4000** [comment]
next version, I drop MP4Box, using FFmpeg as muxer
