### ISSUE TITLE
different audio settings

### ISSUE THREAD

**Issue by shogunreaper** [Anime4000/IFME#169]
I'm trying to encode a dual audio anime and i want the english audio to be 192kbps and the japanese to be 128, but the app seems to change both of them at the same time.

is this intended, if so why?

**Comment by Anime4000** [comment]
it should be different each stream...
maybe GUI "trigger" event cause setting did not save

**Comment by shogunreaper** [comment]
Well i was able to get it to work once but not again, so maybe it is a bug.

and how can i do it for a batch encode? The settings don't show up until after the files are already there.

do you need to manually do it for every file?

**Comment by Anime4000** [comment]
when you select more item in main list `Queue`
and do some changes, all selected item and stream will follow what you set for...

if you want to every 1st and 2nd stream different, you need set one by one
