### ISSUE TITLE
IFME halts all jobs in list after single video gives error.

### ISSUE THREAD

**Issue by SailorOnDaTea** [Anime4000/IFME#17]
IFME stops converting all videos after one video gives error while converting. It won't try to convert the next file in queue. It should report it/write a log and continue working on following files. If the rest of the files are good, then it shouldn't ignore whole job queue.

**Comment by Anime4000** [comment]
As on Facebook Page discussion, problem were:
* MKV exit with warning and returning code 1 (IFME mark code 1 as error)
* Missing `warning` and `error` report
* Make list/log for file that cannot encode

Next improvement:
* Understanding **FFmpeg**, **mkvtoolnix**, **MP4Box** and **x265** exit code
* Add `warning` and `error` log
* Add log and list file that cannot encode

**Comment by Anime4000** [comment]
Identified exit code
* [mkvtoolnix](https://www.bunkus.org/videotools/mkvtoolnix/doc/mkvextract.html#d4e1061) 0 = ok, 1 = warn, 2+ = error.
* [x265](http://x265.readthedocs.org/en/latest/cli.html#executable-options) 0 = ok, 1+ = error
* [FFmpeg](http://stackoverflow.com/a/12210436/3827425) 0 = ok, 1+ = error
