### ISSUE TITLE
Errors trying to compile the solution

### ISSUE THREAD

**Issue by MycroftHolmes1989** [Anime4000/IFME#172]
Kindly update the Newtonsoft.Json.Net project. It is way outdated.
Also, the `public FFmpegDotNet.FFmpeg.Stream MediaInfo { get; set; } = new FFmpegDotNet.FFmpeg.Stream();` in `MediaQueue.cs` throws an error because there is no `Stream `type defined in `FFMpegDotNet`.

**Comment by Anime4000** [comment]
oh yea, I use older version since what I understand...
also FFmpegDotNet, try use previous commit, I working on newer version for integrate IFME

**Comment by MycroftHolmes1989** [comment]
Please mention the versions of Json.Net and FFMpegDotNet in your project Readme.

**Comment by Anime4000** [comment]
try
https://github.com/Anime4000/FFmpegDotNet/tree/dc5a47fdebc49ce26236754cc65dc197a1ec2be2
https://github.com/JamesNK/Newtonsoft.Json/tree/c4af75c8e91ca0d75aa6c335e8c106780c4f7712
i working

**Comment by MycroftHolmes1989** [comment]
Kindly close this topic after you update your solution with the latest versions.
