### ISSUE TITLE
How to update plugins like ffmpeg and x265 library?

### ISSUE THREAD

**Issue by canbonbon** [Anime4000/IFME#173]
Regular user of IFME 7.7. However, it was compiled about an year ago. Since I primarily use it for converting to HEVC, so I wanted to know if there is a way to upgrade FFmpeg and x265? Can I just download their exes and copy paste them in the "plugin\ffmpeg32" folder, etc? Or is there more to this.

**Comment by Epagelmatias** [comment]
For x265 and ffmpeg i notice there are two different types of files

Example1 ffmpeg and ffmpeg.exe. 
Example2 x265-08 and x265-08.exe

I only need to replace the exes with the updated ones and leave the same the non exe ones?

**Comment by Anime4000** [comment]
exe is for Windows
without extension is for linux with `-x` execute bit

for windows, just replace exe file

**Comment by canbonbon** [comment]
Hello Anime, I did the required plugin upgrades to the latest version but now it produces an error saying some header issue. But the converted file plays fine. So not sure what that error is. If you could take a look then that would be great.

**Comment by Anime4000** [comment]
header issue cause by x265 encoder it self especially if you want to export under MP4 container.
Such MP4 container require strict rules, it produce warning header issue.

Decent player can play as fine, for un-decent player like china made player, android tv, etc... it may problem to play, it best to export under MKV
