### ISSUE TITLE
Nero AAC Codec

### ISSUE THREAD

**Issue by firekid2014** [Anime4000/IFME#175]
i found nero AAC compress audio a lot almost 50% and similar audio quality. could you please consider to add nero aac codec next update?

**Comment by Anime4000** [comment]
previously I do add Nero AAC, but got legal strike on me, so I strip out. Stupid copyright....

I do have predefined plugins definition file, simply add

**Comment by f2n2is5** [comment]
> i found nero AAC compress audio a lot almost 50% and similar audio quality. could you please consider to add nero aac codec next update?

Hi @firekid2014 
Were you able to compile a .JSON file to resolve your issue? I also had this issue until I read this and did it myself however, commands differ from FFMPEG AAC -> [https://wiki.hydrogenaud.io/index.php?title=Nero_AAC](url)

If Windows, C:\Program Files\Internet Friendly Media Encoder\plugin\sound.ffmpeg\ and open one of the .JSON files so to see what @Anime4000 mentioned.
