### ISSUE TITLE
Slow Encoding

### ISSUE THREAD

**Issue by YinnVI** [Anime4000/IFME#179]
how to make encode faster?
i use "video.ffmpeg.gpu" plugin but still need log time to encode the video

![capture1](https://user-images.githubusercontent.com/26527969/49218919-4df8d600-f404-11e8-9eb4-b33eb85fdcd6.PNG)
![capture](https://user-images.githubusercontent.com/26527969/49218985-83052880-f404-11e8-8d7c-e4e5697c51ba.PNG)

**Comment by Anime4000** [comment]
I see, I dont have nVidia GPU to test, it seem plugin definition not working

**Comment by YinnVI** [comment]
I also test with Intel QuickSync hevc also slow

**Comment by YinnVI** [comment]
> I see, I dont have nVidia GPU to test, it seem plugin definition not working

can you Please add this Plugin nvenc-Encoder from the NVIDIA SDK:
https://github.com/rigaya/NVEnc/releases
https://forum.videohelp.com/threads/370223-NVEncC-by-rigaya-NVIDIA-GPU-encoding

**Comment by Anime4000** [comment]
sure, I can add

**Comment by kodokbeku45** [comment]
is this project dead ??

**Comment by Anime4000** [comment]
nope, I working on new version, just I dont have enough time

**Comment by f2n2is5** [comment]
> how to make encode faster?
> i use "video.ffmpeg.gpu" plugin but still need log time to encode the video
> 
> ![capture1](https://user-images.githubusercontent.com/26527969/49218919-4df8d600-f404-11e8-9eb4-b33eb85fdcd6.PNG)
> ![capture](https://user-images.githubusercontent.com/26527969/49218985-83052880-f404-11e8-8d7c-e4e5697c51ba.PNG)

Hi YinnVI 
What are kind of media are you attempting to covert? I noticed that you may be suing the (.avs) to filter your source file.
Do you have any performance difference if you import the video file directly into IFME?

I've noticed that when encoding with GPU (NVENC) that my GTX 970's encoding cores are locked/limited and take longer than if I were to use x264.
