### ISSUE TITLE
Audio channel not saved

### ISSUE THREAD

**Issue by Ruriko** [Anime4000/IFME#180]
When I try to set the audio channel to stereo and I switch to another tab it resets back to auto instead of stereo. Can you fix this?

**Comment by Anime4000** [comment]
yes, I can

**Comment by Ruriko** [comment]
> yes, I can

ok let me know when you've updated the program

**Comment by f2n2is5** [comment]
> When I try to set the audio channel to stereo and I switch to another tab it resets back to auto instead of stereo. Can you fix this?

Hi @Ruriko 
A work around for this issue is to specify the FFMPEG Audio Channel arguement. 

In IFME's Audio Tab, click the file's "Stream" then on the "Codec" section, click on "Advance Encoder options" and add   **-ac 2** . This overrides IFME's default that the "Encoding Present" defines.

Let me us know if this helps you out.

Add FFMPEG arguement:
-ac <# of channels>
FFMPEG: 
[https://trac.ffmpeg.org/wiki/AudioChannelManipulation](url)

**Comment by Ruriko** [comment]
> > When I try to set the audio channel to stereo and I switch to another tab it resets back to auto instead of stereo. Can you fix this?
> 
> Hi @Ruriko
> A work around for this issue is to specify the FFMPEG Audio Channel arguement.
> 
> In IFME's Audio Tab, click the file's "Stream" then on the "Codec" section, click on "Advance Encoder options" and add **-ac 2** . This overrides IFME's default that the "Encoding Present" defines.
> 
> Let me us know if this helps you out.
> 
> Add FFMPEG arguement:
> -ac <# of channels>
> FFMPEG:
> [https://trac.ffmpeg.org/wiki/AudioChannelManipulation](url)

It works but the the settings doesn't get saved in a new preset so I can't use it for batch encoding. I'd have to manual input the settings for each video

**Comment by f2n2is5** [comment]
I see. 
If you want it for batch encoding you could try updating the IFME's preset file that you created. 
Find your (.JSON) file look for the "Channel" key and enter "2" then save it. Import a folder of media into IFME and then Select All (Ctrl+A). Click on the IFME's Preset drop down and by clicking you trigger a reapply.

(.JSON) Preset Location in Windows:
C:\Program Files \Internet Friendly Media Encoder\preset\_Your-saved-preset_


Question: Will you batch encoding with multiple audio streams?

**Comment by Ruriko** [comment]
yes i'll be batch encoding that have multiple audio streams

**Comment by f2n2is5** [comment]
@Ruriko 
Gotcha, let us know if you have success.

I've tested:
Importing a (.MKV) file which contained many audio streams into IFME
Applying the edited (.JSON) preset

![ifme_preset_channel_test01](https://user-images.githubusercontent.com/48030206/53539909-41018680-3ac8-11e9-9bbd-a88ed9070f3f.png)

**Comment by f2n2is5** [comment]
> yes i'll be batch encoding that have multiple audio streams

@Ruriko I forgot to mentioned:
I imported the folder of media into IFME and then Selected All (Ctrl+A) then, I clicked on the IFME's Preset drop down to apply the audio settings.

**Comment by Anime4000** [comment]
setting will get apply when cursor leave the control (eg: Drop Down).
currently I making a fix, setting get apply when choose, problem I facing other function, how current setting

**Comment by Ruriko** [comment]
> > yes i'll be batch encoding that have multiple audio streams
> 
> @Ruriko I forgot to mention that for the screenshot:
> I then imported the folder of media into IFME and then Selected All (Ctrl+A) then, I clicked on the IFME's Preset drop down to apply the audio settings.

yea editing the json works for batch encoding
