### ISSUE TITLE
Batch add subtitle to all videos

### ISSUE THREAD

**Issue by Ruriko** [Anime4000/IFME#182]
Is there a batch method to add the same subtitle to multiple videos?

**Comment by Anime4000** [comment]
same subtitle?
like... this_a_sub.srt to video1.mp4 video2.mp4 video3.mp4 ?

**Comment by Ruriko** [comment]
> same subtitle?
> like... this_a_sub.srt to video1.mp4 video2.mp4 video3.mp4 ?

yes that is what I want to do

**Comment by Anime4000** [comment]
it is possible, but GUI limitation cause problem, but I can add this stuff
