### ISSUE TITLE
about SVP Free (Without Manager) ?!

### ISSUE THREAD

**Issue by alucardx77** [Anime4000/IFME#183]
hii Anime4000 

about SVP Free (Without Manager) guide do i need to install IFME to use it ?
because no IFME requirement were mentioned in the wiki ..

**Comment by Anime4000** [comment]
No need IFME, just need a Video Player that use ffdshow raw filter,

**Comment by alucardx77** [comment]
i followed the steps and this came to me with yellow note on top :

![Annotation 2019-07-11 041041](https://user-images.githubusercontent.com/52259583/61014929-61085700-a392-11e9-9cce-13793b0223c8.jpg)

**Comment by Anime4000** [comment]
simply delete line `ffdshow_source()`

**Comment by alucardx77** [comment]
i deleted the line and this again
![Annotation 2019-07-12 044733](https://user-images.githubusercontent.com/52259583/61096829-8fa13300-a461-11e9-8fd0-3860a1b0ed61.jpg) 

i'm thinking the problem could be from the latest version of svpflow plugin maybe svp changed something that could not work with your  lines method  ? do you have the latest svpflow ?

**Comment by Anime4000** [comment]
latest version require money, I do make old version installer,

try this
https://github.com/Anime4000/IFME/releases/tag/SVP4

**Comment by alucardx77** [comment]
yah i know 😅, for me  i installed the last version by 30 days trial as you know after that we can't use the manager  but the files is still there and i can update them  ! , 
any way thank you so much for your time in helping me ☺

**Comment by Anime4000** [comment]
alright~
