### ISSUE TITLE
Broken Pipe error on Windows

### ISSUE THREAD

**Issue by BowenMiao** [Anime4000/IFME#187]
I put the new video.x265gcc folder ([ifme-x265gcc920.7z](https://sourceforge.net/projects/ifme/files/plugin/) that uploaded on December 3rd 2019) under the plugin directory. But then I got the Broken Pipe warning.
![Annotation 2020-01-30 232329](https://user-images.githubusercontent.com/7835169/73521984-5a325600-4442-11ea-9faf-156daf2af4dd.png)

**Comment by Anime4000** [comment]
have you update ffmpeg aswell?

**Comment by BowenMiao** [comment]
> have you update ffmpeg aswell?
You got me. I updated ffmpeg, problem solved!
