### ISSUE TITLE
Show expected completion time.

### ISSUE THREAD

**Issue by AlecHex** [Anime4000/IFME#188]
Firstly, must appreciate the software, love  it and it is lightweight and easy to use. Had a few suggestions for improvement. Is it possible for the software to show the expected completion time or something like that? I don't know if there is something that i am not doing right, but I cant seem to see the time I started the encode in itself. If something like that can be implemented, it would be great.

**Comment by Anime4000** [comment]
IFME is using various encoding tool like x264, x265, ffmpg etc...
I was trying to add remaining time but, these tool have own time reading, you can look into Console or Terminal for remaining time,

Some broken video (where FFmpeg fail to read how many frame) encoding start with remaining time, IFME try the best by guessing (total video in second * fps), but! this equation for constant frame rate,

IFME will not read how many frame where video in Variable Frame Rate,

**Comment by AlecHex** [comment]
The terminal doesn't show the remaining time for me/

**Comment by Anime4000** [comment]
x265 and x264 do show remaining time, maybe source video is unpredictable

**Comment by TwistedFaith84** [comment]
I can say that on all the videos that I converted (mostly from 10bit to 8bit) I dont think I've ever seen it give a remaining time.

**Comment by Anime4000** [comment]
remaining time hard to predict since inconsistent speed.
at least x265 and x264 show some progress.
no point to give fake remaining time.
