### ISSUE TITLE
Script error (SVP Free)

### ISSUE THREAD

**Issue by ilufyou** [Anime4000/IFME#189]
After going through all the steps and restarting mpc-hc i'm getting a syntax error on top of the video. 

(ffdshow_filter_avisynth_script, line 13, column 1) 
This should be the line ConvertToYV12()

Any clue about what i did wrong?

**Comment by Anime4000** [comment]
are you using 32bit MPC?

**Comment by ilufyou** [comment]
The 64bit version of MPC. Is that a problem?

**Comment by Anime4000** [comment]
so far, SVP works on 32-bit

**Comment by ilufyou** [comment]
Tried again with the 32 bit version. Still the same error. I got svpflow from your frame interpolation guide, downloaded the mega pack and mpc 32bit and got avisynth+ from videohelp.com. Any other ideas?

**Comment by Anime4000** [comment]
remove AviSynth+, SVP plugins
and try use this SVP Manager Free
https://hitoha.ga/downloads/apps/setup_svp4-free.exe

**Comment by kurai021** [comment]
MPC x86 crashes when ffdshow video filter is enabled, they suggest to uninstall ffdshow decoders only but crashes again
