### ISSUE TITLE
resizing issues 

### ISSUE THREAD

**Issue by MrDeadpool-encoder** [Anime4000/IFME#190]
When i try to change the resolution from 1080p to 720p image quality goes really bad 

my work [info](https://pastebin.com/DY8esyJ5)

![image_2020-04-01_08-16-36](https://user-images.githubusercontent.com/63006770/78219940-3214b100-74de-11ea-8019-9a353f5aa75e.png)
![image_2020-04-01_08-15-56](https://user-images.githubusercontent.com/63006770/78219978-49539e80-74de-11ea-898b-8fe2a1aeaa82.png)

Raw [info](https://pastebin.com/LbwNfd7N)

![image_2020-04-01_08-17-51](https://user-images.githubusercontent.com/63006770/78220453-2f668b80-74df-11ea-8a16-47ec084e0574.png)
![image_2020-04-01_08-19-56](https://user-images.githubusercontent.com/63006770/78220175-a5b6be00-74de-11ea-8cdb-21fb353627db.png)

if can plz help

**Comment by Anime4000** [comment]
have you adjust x265 CRF value above 24 and `veryslow` preset?

**Comment by MrDeadpool-encoder** [comment]
> have you adjust x265 CRF value above 24 and `veryslow` preset?

(--crf 20 --bframes=8 --aq-mode=2  --aq-strength=1  --ref 6 --rdoq-level 2 --amp --subme 5 --cutree --psy-rd=1.5 --qcomp=0.7) at very slow 

and i have to say your software is great

**Comment by Anime4000** [comment]
I guess I using poor FFmpeg resizing, thanks for reporting, I get this fix

**Comment by MrDeadpool-encoder** [comment]
thank u

**Comment by Anime4000** [comment]
need to wait I release new version, this version will never fix, code I made become un-maintable

**Comment by MrDeadpool-encoder** [comment]
don't worry, I used VapourSynth and got it fixed for me
