### ISSUE TITLE
Updated x265 but now IFME gets stuck at 99.8%

### ISSUE THREAD

**Issue by canbonbon** [Anime4000/IFME#191]
Been using IFME for a long time. Today I updated the x265 to 3.3 version. However, IFME gets stuck at 99.9 or 99.8%. So I went to the temp folder and used MKVTools to create the MKV file myself using the extracted Audio and video0000_und.h265 video. The movie was fine. So clearly, it finishes the job but is unable to bind the files back into the final MKV container. Any suggestions? Or I will have to revert back to older version of X265. Please take a look at the logs below:

================================================================
Release: IFME v7.7 amd64 windows

(c) 2020 Anime4000, FFmpeg, MulticoreWare, VideoLAN, GPAC
Xiph.Org Foundation, Google Inc., Nero AG, Moritz Bunkus, et al.

Warning, DO NOT close this Terminal/Console, all useful info will be shown here.

Loading plugins complete!
 ERROR: Not connected to the internet?
ifme [info]: Clearing temp folder: C:\Users\xx\AppData\Local\Temp\IFME
ifme [info]: Extracting chapters, subtitles and fonts :)

ifme [info]: Run command: "C:\Tools\Internet Friendly Media Encoder\plugin\mkvtoolnix\mkvextract" chapters "E:\xxxx(2020).mkv" > chapters.xml
ifme [info]: Encoding audio, please wait...
ifme [info]: Run command: "C:\Tools\Internet Friendly Media Encoder\plugin\copy\..\ffmpeg64\ffmpeg" -hide_banner -v quiet -stats -i "E:\xxxx(2020).mkv"  -map 0:1 -c:a copy     -y "audio0000_eng.mka"
size=  256375kB time=01:30:44.06 bitrate= 385.8kbits/s speed= 222x
ifme [info]: Audio encoding OK!
ifme [info]: Encoding video, this take a while...
ifme [info]: Run command: "C:\Tools\Internet Friendly Media Encoder\plugin\ffmpeg64\ffmpeg" -hide_banner -v error -i "E:\Downloads\JDownloader\xxxx (2020).mkv" -strict -1  -map 0:0 -f yuv4mpegpipe -pix_fmt yuv420p10le -s 1920x1080 -r 23.976   - | "C:\Tools\Internet Friendly Media Encoder\plugin\video.x265gcc\x265-10.exe" - --y4m -p medium --crf 24 -t ssim --output-depth 10 -f 130768  -o video0000_und.h265
y4m  [info]: 1920x1080 fps 2997/125 i420p10 sar 1:1 unknown frame count
raw  [info]: output file: video0000_und.h265
x265 [info]: HEVC encoder version 3.3+20-479b96e84e98
x265 [info]: build info [Windows][GCC 6.3.0][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 4 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 2 / wpp(17 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 23 / 250 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-24.0 / 0.60
x265 [info]: tools: rd=3 early-skip rskip mode=1 signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing lslices=6 deblock sao
[99.8%] 130496/130768 frames, 12.24 fps, 2465.01 kb/s, eta 0:00:22

**Comment by Anime4000** [comment]
oh man, mkvtoolnix problem, wont recompile source into single mkv file

**Comment by canbonbon** [comment]
So are you saying that I should upgrade that plug in too? Maybe I can try that and see if that works. I see only two files in that directory. MKVMerge.exe and MKVExtract.exe. Should I just replace those two with the latest version and then try again? Also, its not clear why it is MKVToolnix issue. Because if I replace the old x265.exe file, then everything works. So are you saying that somehow the new x265.exe file is not compatible with the old MKVtoolnix files? Anyway, thanks for the tip, I will try and post back the results.

**Comment by canbonbon** [comment]
Just an update. I tried to upgrade MKVMerge to the latest version but that did not fix the issue. IFME still gets hung at 99.8%. Then I have to manually put the audio and video files into an MKV container. However, when I switched back to the previous x265.exe file, then it started working again. So clearly, its something being caused by the new x265.exe file. Can you take a look and let me know if you have any suggestions?

**Comment by Anime4000** [comment]
I believe mkvtoolnix disallow this, I have tried contact Moritz Bunkus the author of mkvtoolnix, they quote me, this kind behavior is disallow, which mean, shipping/bundle mkvtoolnix is not allowed.

I making new version, and get rid of mkvtoolnix and MP4Box

**Comment by canbonbon** [comment]
ok its fine. I revered back to the old x265.exe file and everything is working now. Will wait for your new version. Hopefully soon. Thanks again for responding.

**Comment by Anime4000** [comment]
I just notice this in newer version
x265 need explicitly define total frames, over 1 frame cause x265 keep waiting, I try contact x265 developer about this

**Comment by Anime4000** [comment]
![Internet Friendly Media Encoder 20 02](https://user-images.githubusercontent.com/1908715/79854668-6227e380-83fc-11ea-94b6-e0f86173d23d.png)
I have compiled x265 3.2 stable
[x265gcc_ryzen.zip](https://github.com/Anime4000/IFME/files/4509276/x265gcc_ryzen.zip)

Nightly build x265 have stuck/waiting issue when put extra `--frames`.

**Comment by Anime4000** [comment]
Sorry, please use this build
[x265gcc_ryzen.zip](https://github.com/Anime4000/IFME/files/4510021/x265gcc_ryzen.zip)

**Comment by canbonbon** [comment]
Thanks. This worked just fine. Not sure what difference it makes but now I am using the latest version provided by you. 
x265 [info]: HEVC encoder version 3.2_IFME-ZEN_2
Thanks again.

**Comment by Anime4000** [comment]
x265 developer notice this about frame count issue
https://mailman.videolan.org/pipermail/x265-devel/2020-April/012962.html

I haven't test nightly build, for now you use stable release
