### ISSUE TITLE
Update Releases???

### ISSUE THREAD

**Issue by TwistedFaith84** [Anime4000/IFME#192]
Any plans on updating any/all releases (here on Github)? I noticed that the last release was 7.7 and that was from about 2 years ago. Now granted not much was updated since then but there were a few thing that can be integrated into a new/er release.

**Comment by Anime4000** [comment]
I can't guarantee when I can release, I need carefully code and fine tune, so I won't make same mistake and same bug like old version.

but I can give you my current work:
![79854668-6227e380-83fc-11ea-94b6-e0f86173d23d](https://user-images.githubusercontent.com/1908715/80029384-49612000-8519-11ea-9dd4-c0d0c4ae0a8c.png)
this will be the next version

**Comment by TwistedFaith84** [comment]
sounds good. any idea on about how soon for that to me uploaded

**Comment by Anime4000** [comment]
very soon, here: https://hitoha.ga/downloads/app/IFME.Debug.zip
GitHub comment limit at 10MB, so I put in my self-hosted web server
