### ISSUE TITLE
Did you just release something? IFME is asking to download a new version

### ISSUE THREAD

**Issue by canbonbon** [Anime4000/IFME#193]
Did you just release something? IFME is asking to download a new version. However, the new version is also 7.7. So I am a little confused. Are these bug fixes only? Wondering if I should download or not. I did not see any release notes either.

**Comment by Anime4000** [comment]
Yes, a Alpha build for 2020 release, you can get from my web server:
https://hitoha.ga/downloads/app/IFME.Debug.zip

sorry for slow speed
