### ISSUE TITLE
customize presets?

### ISSUE THREAD

**Issue by Omar-AbdulAzeez** [Anime4000/IFME#194]
an option to customize presets and applying the preset on multiple files at once is needed

**Comment by Anime4000** [comment]
customize at this moment not yet, but...
apply preset/profile is functional, highlight all and apply at once!

**Comment by Omar-AbdulAzeez** [comment]
also, does the current alpha release have problems? or just v2020 is not fully complete?

**Comment by Anime4000** [comment]
v2020 not complete, basic function under default is working

**Comment by Anime4000** [comment]
Custom presets now functional 
![Untitled2](https://user-images.githubusercontent.com/1908715/80896473-2ad10500-8d21-11ea-9df3-9bb8aa5130da.png)

Exist in this release:
https://github.com/Anime4000/IFME/releases/tag/20.04.2-alpha
