### ISSUE TITLE
Support for image sequences

### ISSUE THREAD

**Issue by L0Lock** [Anime4000/IFME#196]
As an animator, I export a lot of image sequences and usually use batch files with ffmpeg commands to convert them. And I know a lot of people in the video industry work with image sequences, and ffmpeg is a really powerful tool to get a quick and quality preview out of them. And IFME gives a nice UI for that purpose, but sadly it doesn't support image sequences for now.

If you're interested, the command line syntax is pretty simple (on windows, no idea for Linux or Mac) when it comes to using ffmpeg in command line:

Let's say we have a sequence of frames named "frames_xxx.jpg", then the command would look like:

```batch
ffmpeg -i "frames_%03d.jpg" -arguments output.extension
```
- `%` indicates the start of the numbering (must be `%%` if written in a .bat file)
- `0` indicates the numbering is zero-padded. Do not use if not zero-padded.
- `3d` indicates the amount of digits in the numbering (here it's three, but it can be anything)

If the start frame isn't 1 or 0, the argument `-start_number x` can be added before `-i`.

As for how it could be managed in IFME, the simple and easy way could be to let the user write the things while browsing for his input files. Otherwise, other softwares managing image sequence usually require to either select the first frame or every frames, and then detects the image sequence themselves.

I hope this helps.
And happy to see you back ♥

**Comment by Anime4000** [comment]
I understand, as old IFME it does support, yes, I going to add this feature.
For now, try use `AviSynth` scripts as input file, not clean way but, can work.

**Comment by Anime4000** [comment]
@L0Lock can you help me,
I been trying to compile MP4Box 0.8.0 as static using msys2 tool-chain, I can't get MP4Box.exe become portable.

I put `zlib1.dll` in same folder as `MP4Box.exe` and still popup error message that `zlib1.dll` is missing.

I dont know why it appear missing in some system

**Comment by L0Lock** [comment]
I would like to help but I have little to no knowledge on that stuff 😮 

That page might help? https://github.com/gpac/gpac/wiki/Build-Introduction

I don't know sorry

**Comment by Anime4000** [comment]
I closing this since alpha version 21.06.14 has this feature:
https://sourceforge.net/projects/ifme/files/encoder-gui/21.x/IFME-21.06.14_Debug.7z/download

If you have discord account, invite link available inside **About IFME**
