### ISSUE TITLE
Abort should abort shutdown/restart

### ISSUE THREAD

**Issue by Omar-AbdulAzeez** [Anime4000/IFME#197]
as the title says :P if i have a shutdown scheduled it shouldn't shutdown when i abort

**Comment by Anime4000** [comment]
this also not exist in current alpha release, it will added soon

**Comment by Anime4000** [comment]
Right Click `Start` button to enable shutdown upon complete
![Untitled](https://user-images.githubusercontent.com/1908715/80896443-b007ea00-8d20-11ea-8d4f-c7155f9d3cc2.png)

Available in this release
https://github.com/Anime4000/IFME/releases/tag/20.04.2-alpha
