### ISSUE TITLE
Enable General tab

### ISSUE THREAD

**Issue by Omar-AbdulAzeez** [Anime4000/IFME#198]
Before getting into the first thing here...
How does the new "General" tab work? Is the Right click -> properties window limited to one file? So i have to do this for each file to see the properties?
If so, then the option to enable a tab like before is a good idea... consider this scenario: I have a lot of videos to encode and i have a certain preset but there are irregularities in bit rate... most are 8-bit but there are 10-bit among them.. it would be a shame to downgrade that so i just scroll the files while looking at the bit value to check it quickly but the new way would make this a pain

**Comment by Anime4000** [comment]
Media Info added in this release:
https://github.com/Anime4000/IFME/releases/tag/20.04.2-alpha
