### ISSUE TITLE
NO install and error when finish video

### ISSUE THREAD

**Issue by pcdiabla** [Anime4000/IFME#199]
Error not found xvidcore.dll

**Comment by Anime4000** [comment]
`x264` encoder?

**Comment by Anime4000** [comment]
![x264gcc](https://user-images.githubusercontent.com/1908715/80748346-5bfdd980-8b57-11ea-9a80-b421e820ad15.png)
double check your download, in package it should exist

**Comment by pcdiabla** [comment]
The file is there but it cant found

**Comment by Anime4000** [comment]
Try this: https://github.com/Anime4000/IFME/releases/tag/20.04.2-alpha

**Comment by pcdiabla** [comment]
Same :(
![image](https://user-images.githubusercontent.com/48361644/81448934-75e18280-913c-11ea-863b-76acece5455b.png)

**Comment by Anime4000** [comment]
I guess my own MP4Box compile is not static/portable, I need find someone can guide me to compile Linux tools in Windows, portable way

**Comment by Anime4000** [comment]
The latest IFME `20.05.2` wont have this issue, try it
https://github.com/Anime4000/IFME/releases/tag/20.05.2-alpha
