### ISSUE TITLE
can't add attachments 

### ISSUE THREAD

**Issue by MrDeadpool-encoder** [Anime4000/IFME#200]
this is with the new 20.04.2 ver 
as well as can't see the progress bar when encoding 
![image](https://user-images.githubusercontent.com/63006770/80936162-8b2d7880-8ded-11ea-9b0b-934b826bf9a4.png)

**Comment by Anime4000** [comment]
the SVT is broken or Rich Text Box problem, I try different method.

**Comment by MrDeadpool-encoder** [comment]
> the SVT is broken or Rich Text Box problem, I try different method.

Well 
Thx this happened when I was using av1

**Comment by Anime4000** [comment]
the SVT cant show progress report, this might need hack SVT code, this take time

**Comment by Anime4000** [comment]
Alpha version 21.06.14 has fixed this issue,
https://sourceforge.net/projects/ifme/files/encoder-gui/21.x/IFME-21.06.14_Debug.7z/download

*If you have discord account, you can join IFME project, invite link available inside **About IFME***
