### ISSUE TITLE
Decimal separator problem

### ISSUE THREAD

**Issue by zsuatem** [Anime4000/IFME#201]
Problem with encoder arguments when the decimal separator in the system is not a dot.

![IFME_TNFtj7695W](https://user-images.githubusercontent.com/17302628/81307897-749f4f80-9081-11ea-8bb7-4daf76151eac.png)

![IFME_K5fmeUGrUG](https://user-images.githubusercontent.com/17302628/81307907-779a4000-9081-11ea-8220-bc01b01e5b5a.png)

**Comment by Anime4000** [comment]
ouch, I forgot about this, some country use `,`... aww man

**Comment by Anime4000** [comment]
The fixed version is out, try this:
https://github.com/Anime4000/IFME/releases/tag/20.05.2-alpha

IFME will use `en-US` or `en-GB` all the time.
