### ISSUE TITLE
Updated to new version, IFME does not convert anymore

### ISSUE THREAD

**Issue by canbonbon** [Anime4000/IFME#202]
Long term user of the old version. The new version only converts audio but no video. What am I missing? Also, does not allow me to copy the audio anymore. The checkbox is grayed out. Is there a guide for the new version?

**Comment by Anime4000** [comment]
May I know what error are you getting?

> I have trouble to build portable `MP4Box`, version I ship cause some system can't run due to missing library

Copy audio not available at this moment, but only works when MKV (universal container) is selected,

**Comment by Anime4000** [comment]
Can you try this?
https://hitoha.ga/downloads/apps/IFME_Static-Tools.zip

**Comment by Anime4000** [comment]
Fixed version is here, please try:
https://github.com/Anime4000/IFME/releases/tag/20.05.2-alpha

I close this issue, if anything happen, please reopen 👍
