### ISSUE TITLE
Scaling / DPI issue

### ISSUE THREAD

**Issue by antoshre** [Anime4000/IFME#205]
I have a pair of monitors, one 1080p and the other 4k.  When both are on IFME opens normally and can be moved between them without issue.

When the 1080p is turned off Windows does something with the scaling and breaks the layout.  It stays broken afterwards on both monitors.

![ifme](https://user-images.githubusercontent.com/6820149/87747165-58b5d980-c7a7-11ea-9c2d-4dc112904184.png)

Altering the window size doesn't trigger a re-layout.

**Comment by Anime4000** [comment]
Windows Scaling has been horrible since then, especially WinForms GUI.
I want to try replicate issue like you, unfortunate I don't have 4K monitor to test with.

I keep this in View, to see this fixable or not

**Comment by Anime4000** [comment]
In my test, it scale properly among multiple monitor,

Windows 10 20H2

**Comment by Anime4000** [comment]
WinForms scale between different monitor has been fixed, using Latest Windows 10 release.

reopen this issue if problem still exists
