### ISSUE TITLE
When will you be releasing the final version? I just downloaded and its still Alpha.

### ISSUE THREAD

**Issue by canbonbon** [Anime4000/IFME#207]
When will you be releasing the final version? I just downloaded and its still Alpha.

**Comment by canbonbon** [comment]
I am still having the same issue. The encoding ends in like 30 seconds. 

[INFO] Video filter command is: -vf "scale=1920:816"
av_interleaved_write_frame(): Broken pipe
    Last message repeated 1 times
Error writing trailer of pipe:: Broken pipe
[INFO] Restructure RAW video file...
[INFO] Multiplexing encoded files into single file...

**Comment by Anime4000** [comment]
Sorry, I don't have much time on this project, and I work more as world hit by pandemic,
I can promise this will completed before new year.

**Comment by canbonbon** [comment]
I am still having the same issue. Maybe I am not doing something right. 
I unzip the downloaded file into a folder. That folder has ifme.exe file that I try to run. It comes up fine. Then I put the movie for conversion but it only extracts the audio and end. Here is the log output:
[INFO] Extracting subtitle file...
[INFO] Extracting embeded attachment...
size=       0kB time=-577014:32:22.77 bitrate=N/A speed=N/A    
[INFO] Extract audio file...
[INFO] Encoding video file...
[INFO] Video filter command is: -vf "scale=1920:1080"
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
[INFO] Restructure RAW video file...
[INFO] Multiplexing encoded files into single file...

The options icon does not work either. I am switching back to the old version as this new version does not work for me at least. Can you provide any suggestions on how to make it work?

**Comment by Anime4000** [comment]
sorry for late update, still WIP

Try this:
https://sourceforge.net/projects/ifme/files/encoder-gui/21.x/IFME-21.06.14_Debug.7z/download

*If you have discord account, you can join IFME project, invite link available inside **About IFME***

**Comment by Anime4000** [comment]
I closing this for now, if you have problem, feel free to reopen
