### ISSUE TITLE
Bug Maybe

### ISSUE THREAD

**Issue by Dhanamerdeka** [Anime4000/IFME#208]
When using lastest from github
i experience error when select resolution (after add the video files)
the app not respond forever and need to stop via taskmanager....

any solution?

**Comment by Anime4000** [comment]
oh, Interface Bug, I'll fix this,

**Comment by Dhanamerdeka** [comment]
@Anime4000 thanks :) 
and can you make setting default to not change the resolution?
example the original resolution is 10x10... so you can use checkbox or anything like that to make this app will encode the same resolution like the input...? 
some people i think will use this app to turn normal video to H265 only.... so i think that will be good if you have that... :)


btw thanks for your great app... i hope the new version will be have other great feature :)

**Comment by Anime4000** [comment]
> 
> 
> @Anime4000 thanks :)
> and can you make setting default to not change the resolution?
> example the original resolution is 10x10... so you can use checkbox or anything like that to make this app will encode the same resolution like the input...?
> some people i think will use this app to turn normal video to H265 only.... so i think that will be good if you have that... :)
> 
> btw thanks for your great app... i hope the new version will be have other great feature :)

it have "auto" on the top list for that, I guess this need change to `auto` to `default`

**Comment by Dhanamerdeka** [comment]
yeah i agree... this need auto to be default...
i hope new version will come soon...
because current build too much feature that make this program "not respond" and then crash

**Comment by Anime4000** [comment]
Alpha version 21.06.14 has fixed this issue,
https://sourceforge.net/projects/ifme/files/encoder-gui/21.x/IFME-21.06.14_Debug.7z/download

*If you have discord account, you can join IFME project, invite link available inside **About IFME***
