### ISSUE TITLE
When will there be a new verison of IFME

### ISSUE THREAD

**Issue by malzen** [Anime4000/IFME#212]
I would like to know when you are going to make a stable update to IFME.

**Comment by Anime4000** [comment]
sorry for very late update, here new version available to download
https://sourceforge.net/projects/ifme/files/encoder-gui/21.x/IFME-21.05.25_Debug.7z/download

**Comment by malzen** [comment]
Thank you so much will be testing to see if there are any issues.

**Comment by malzen** [comment]
When encoding is finished there is no video file in saved location it's empty. Could you add a option where to save video file also add dark mode feature.

**Comment by Anime4000** [comment]
can you show the error in the Console log?
