### ISSUE TITLE
glyph not found

### ISSUE THREAD

**Issue by VirusVenomForever** [Anime4000/IFME#213]
how to pass\fix this error?
![AGfyLTz](https://user-images.githubusercontent.com/77768568/112057626-bb0b7900-8b83-11eb-82ef-ec006776b37d.png)

**Comment by Anime4000** [comment]
subtitle issue, can you send that file to me, I like to examine

**Comment by VirusVenomForever** [comment]
Yeah, here. And after process done - text in certaint moment - just square. But in other converter, that only convert in mp4 - doesn't have this issue, text is normal with proper style

[[SOFCJ-Raws] Naruto - 102 (DVDRip 768x576 HEVC VFR 10bit FLAC).zip](https://github.com/Anime4000/IFME/files/6228264/SOFCJ-Raws.Naruto.-.102.DVDRip.768x576.HEVC.VFR.10bit.FLAC.zip)

**Comment by VirusVenomForever** [comment]
> subtitle issue, can you send that file to me, I like to examine

Yeah, here. And after process done - text in certaint moment - just square. But in other converter, that only convert in mp4 - doesn't have this issue, text is normal with proper style

[[SOFCJ-Raws] Naruto - 102 (DVDRip 768x576 HEVC VFR 10bit FLAC).zip](https://github.com/Anime4000/IFME/files/6228269/SOFCJ-Raws.Naruto.-.102.DVDRip.768x576.HEVC.VFR.10bit.FLAC.zip)

**Comment by Anime4000** [comment]
I see...

I think have missing proper fonts,

have you tried to upgrade FFmpeg that shipped with IFME?

I using FFmpeg as MKV Muxer

**Comment by VirusVenomForever** [comment]
shipped - you mean in plugins in ffmpeg64 and 32?

**Comment by VirusVenomForever** [comment]
> I see...
> 
> I think have missing proper fonts,
> 
> have you tried to upgrade FFmpeg that shipped with IFME?
> 
> I using FFmpeg as MKV Muxer

i've got last K-lite codec pack 27th march - there have FFmpeg -  problem still persists.

**Comment by Anime4000** [comment]
This might help
https://stackoverflow.com/questions/58850242/ffmpeg-burn-chinese-subtitlesrt-with-error

**Comment by VirusVenomForever** [comment]
> This might help
> https://stackoverflow.com/questions/58850242/ffmpeg-burn-chinese-subtitlesrt-with-error

fonts are installed in /usr/share/fonts/truetype - it's don't help it all

**Comment by VirusVenomForever** [comment]
find solution - you right - just need change unicode in subtitles and it's proper done.

**Comment by Anime4000** [comment]
the file you send me is ready UTF-8

**Comment by VirusVenomForever** [comment]
> the file you send me is ready UTF-8

sorry, i'm not corretc explain - need change encoding

**Comment by VirusVenomForever** [comment]
another problem - after switch unicode on ansi - some font(arial) got this, another text proper
![r6RW5He](https://user-images.githubusercontent.com/77768568/113302232-abc5c180-9321-11eb-866f-e347eafea8a1.png)

**Comment by Anime4000** [comment]
By default, IFME instruct FFmpeg to render subtitle as UTF-8,

save subtitle as UTF-8, not UTF-8 with BOM or other:
![image](https://user-images.githubusercontent.com/1908715/113333812-818df700-9355-11eb-92c8-8476d5fa2486.png)

import into IFME, try again.

FFmpeg will parse subtitle as UTF-8 without any modification, it should not print any error.

then supported video player to render subtitle, like MPC-HC will read as UTF-8

**Comment by VirusVenomForever** [comment]
> By default, IFME instruct FFmpeg to render subtitle as UTF-8,
> 
> save subtitle as UTF-8, not UTF-8 with BOM or other:
> ![image](https://user-images.githubusercontent.com/1908715/113333812-818df700-9355-11eb-92c8-8476d5fa2486.png)
> 
> import into IFME, try again.
> 
> FFmpeg will parse subtitle as UTF-8 without any modification, it should not print any error.
> 
> then supported video player to render subtitle, like MPC-HC will read as UTF-8

no, i tried this before and try again now - the same error - glyph not found

**Comment by VirusVenomForever** [comment]
in new version - it's fixed, thanks!

**Comment by Anime4000** [comment]
Nice!
