### ISSUE TITLE
hdr

### ISSUE THREAD

**Issue by Mavrick007** [Anime4000/IFME#215]
please can u add the option to encode hdr and hlg please

**Comment by Anime4000** [comment]
you mean `sdr` to `hdr` ?
or HDR to HDR

**Comment by Mavrick007** [comment]
Hdr to hdr

**Comment by Anime4000** [comment]
it should automatically encode hdr

**Comment by Mavrick007** [comment]
well it doesnt, how can i set it to do that plz?

**Comment by Anime4000** [comment]
I haven't, you can freely replace plugins binary and edit plugin definition file, try add extra command there

**Comment by Anime4000** [comment]
FFmpeg did not pass HDR metadata, as #209 

HDR seem bit mess when I trying manually passing HDR data to output, some missing metadata that FFmpeg cannot know

**Comment by Anime4000** [comment]
closing this issue, use #209 issue for HDR supporr
