### ISSUE TITLE
Intel oneAPI Video Processing Library support ?

### ISSUE THREAD

**Issue by MarcoRavich** [Anime4000/IFME#220]
I just noticed that from 1.5.0 release (delivered yesterday), Handbrake now "Updated Intel Quick Sync to use the Intel oneAPI Video Processing Library (oneVPL)".

...do you think it could be useful to support it too ?

https://github.com/oneapi-src/oneVPL
https://github.com/oneapi-src/oneVPL-intel-gpu

**Comment by Anime4000** [comment]
I can try, but cannot test since I dont have Intel System

**Comment by forart** [comment]
Well, alternatively, you can try @rigaya's HW CLI encoders:
https://github.com/rigaya/

**Comment by Anime4000** [comment]
this one? https://github.com/rigaya/QSVEnc

**Comment by forart** [comment]
> this one? https://github.com/rigaya/QSVEnc
That's for Intel GPUs, but - as you can see - he provides HW encoders for all (NVIDIA -> [NVEnc](https://github.com/rigaya/NVEnc#nvenc), AMD -> [VCEEnc](https://github.com/rigaya/VCEEnc#vceenc) and Intel -> [QSVEnc](https://github.com/rigaya/QSVEnc#qsvenc)).

We suggest you to check how @cdgriffith's [FastFlix](https://github.com/cdgriffith/FastFlix/#fastflix) leverages them if you want to use them in your software too.

Hope that inspires.

**Comment by Anime4000** [comment]
I'll take a look, for Nvidia, I can add since I have the GPU to test

**Comment by forart** [comment]
Thanks a lot, it works now.

**Comment by MarcoRavich** [comment]
Everything done !
