### ISSUE TITLE
App crashes after selecting "auto" frame rate 

### ISSUE THREAD

**Issue by MrxHellsing** [Anime4000/IFME#223]
Using 8.0_beta2 version. After opening a video file, If I select frame rate "auto", the app becomes non-responsive and stays like that.
![image](https://user-images.githubusercontent.com/29206412/201353223-611e9fed-8b56-4bd0-9ca5-f0d4130fa864.png)

**Comment by MrxHellsing** [comment]
![image](https://user-images.githubusercontent.com/29206412/201354316-c44232ab-c18a-4866-a079-810ff4051a2d.png)
Update: Tried the same with beta4, similar result.

**Comment by Anime4000** [comment]
Thanks for point it out, the fix will release soon as beta 5 later

**Comment by Anime4000** [comment]
I have release -beta 5, it should fix this issue
