### ISSUE TITLE
Unrecognized option 'cqp'. when using H.265 FFmpeg AMD AMF, Constant Quantization Parameter

### ISSUE THREAD

**Issue by AhmadRehan98** [Anime4000/IFME#226]
Full log output:

[INFO] Encoding video file...
[DEBG] Command Line: "F:\Programs\ENCODING SOFTWARE\IFME-8.1-net48\Plugins\ffmpeg64\ffmpeg" -hide_banner -v error -stats -i "F:\Recordings\lowkey.gg\a_23_hard_phantom_is_here.mkv" -map 0:0 -pix_fmt yuv420p -vf fps=30 -rc cqp -cqp 24 -map_metadata -1 -map_chapters -1 -c:v hevc_amf -quality quality -profile main -profile_tier high -usage transcoding -y video0000_und.mp4
Unrecognized option 'cqp'.
Error splitting the argument list: Option not found

**Comment by Anime4000** [comment]
I am sorry for the unforeseen issue, I don't have AMD GPU to test but, I understand what cause, I releasing v8.2 soon

**Comment by Anime4000** [comment]
now can be download here, see if that works:
https://sourceforge.net/projects/ifme/files/encoder-gui/8.0/IFME-8.2-net48.7z/download
