### ISSUE TITLE
error: x265 multi pass target bitrate --pass 2

### ISSUE THREAD

**Issue by longwu9t** [Anime4000/IFME#229]
……
[DEBG] Command Line: "C:\proApp\IFME\Plugins\ffmpeg64\ffmpeg" -hide_banner -v error -i "D:\vdo\cat.mkv" -map 0:0 -pix_fmt yuv420p -vf scale=720:1280:flags=lanczos,fps=30 -strict -1 -f yuv4mpegpipe - | "c:\proApp\encoders\x265.exe" --y4m - -f 252 --input-depth 8 --output-depth 8 --input-csp i420 -p medium -t ssim --bitrate 500 --pass 2 -o raw-v0000_und.h265
[vost#0:0/wrapped_avframe @ 0000024364a65780] Error submitting a packet to the muxer: Broken pipe
……

**Comment by longwu9t** [comment]
x265 [info]: HEVC encoder version 3.6+27-8787e8702
x265 [info]: build info [Windows][GCC 13.3.0][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-3.1 (Main tier)
x265 [info]: Thread pool created using 8 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 3 / wpp(12 rows)
x265 [error]: 2nd pass has more frames than 1st pass (121 vs 119)
x265 [error]: x265_encoder_open() failed for Enc,
x265 [error]: Failure generating stream headers in x265
[vost#0:0/wrapped_avframe @ 000002122fb29980] Error submitting a packet to the muxer: Broken pipe
    Last message repeated 1 times
[out#0/yuv4mpegpipe @ 000002122fa9f400] Error muxing a packet
[out#0/yuv4mpegpipe @ 000002122fa9f400] Task finished with error code: -32 (Broken pipe)
[out#0/yuv4mpegpipe @ 000002122fa9f400] Terminating thread with return code -32 (Broken pipe)
[out#0/yuv4mpegpipe @ 000002122fa9f400] Error writing trailer: Broken pipe
[out#0/yuv4mpegpipe @ 000002122fa9f400] Error closing file: Broken pipe

**Comment by longwu9t** [comment]
x264
Multi pass, Target bitrate (kbps)
The same problem exists

**Comment by Anime4000** [comment]
I see, for 5 pass, way it should pass is `1`, `3`, `3`, `3`, `2`
I'll check why multipass wrong

**Comment by Anime4000** [comment]
possible fix:

1. Ignore Frame Count, this will not show total progress and ETA
2. Indexing video first, FFmpeg will play and count how many REAL total frame and keep total progress and ETA

which one do you like? for Indexing fix, it will delay and take time to indexing first instead of guessing

**Comment by longwu9t** [comment]
as you wish

**Comment by Anime4000** [comment]
I think most safest is ignore Frame Count, no ETA, try this
[IFME_try8.2.3.zip](https://github.com/user-attachments/files/15935457/IFME_try8.2.3.zip)

**Comment by longwu9t** [comment]
new version works fine!
thanks!!!

**Comment by Anime4000** [comment]
Alright! releasing 8.2.3
