### ISSUE TITLE
ERROR: when adding MKV files, an error occurs if the track title contains non-ASCII characters

### ISSUE THREAD

**Issue by longwu9t** [Anime4000/IFME#230]
![2024-06-24_123959](https://github.com/Anime4000/IFME/assets/9213316/aa3ff68d-ffa2-4866-9c03-ff812213fdce)
When adding MKV files, an error occurs if the track title contains non-ASCII characters
After deleting the corresponding characters using mkvtoolnix, the MKV file can be opened by IFME normally.

**Comment by Anime4000** [comment]
Discussion to #231
