### ISSUE TITLE
Media info display garbled characters

### ISSUE THREAD

**Issue by longwu9t** [Anime4000/IFME#231]
![2024-06-24_130744](https://github.com/Anime4000/IFME/assets/9213316/eb00603c-d934-4dd5-abe2-8ab5575b96d0)

The non-ASCII part of the file name is displayed as garbled characters, 
which does not affect the encoding work, 
just a small problem.

**Comment by Anime4000** [comment]
the ffmpeg probe output JSON, it should be Unicode or at least UTF-8
may I know what is the actual PATH ?

**Comment by longwu9t** [comment]
d:\vdo\国家地理\阿斯哈图石林\01.mp4

**Comment by Anime4000** [comment]
For file path, it could avoid using path from JSON, this should be easy fix.

For issue #230 the Windows Console redirection `>` not properly parsed to UTF-8, as issue long time ago:
https://superuser.com/questions/1584842/ffprobe-output-text-wrong-encoding
https://trac.ffmpeg.org/ticket/8890#comment:2

I think, instead of use redirection pipe, output to file instead, so, JSON closing string corrected at least

**Comment by longwu9t** [comment]
#230 causes some MKV files to be unable to open, 
if character set detection and conversion is a problem,
maybe don't need to read the title of each MKV stream, 
like processing mp4 files.
non-ASCII characters in the mp4 file's title, 
no error occur.

**Comment by Anime4000** [comment]
I understand, my FFmpeg MediaInfo parse doesn't read stream title
https://github.com/Anime4000/IFME/blob/master/IFME.FFmpeg/MediaInfo.cs

However the `-print_format json -show_format -show_streams` will print everything...
I wonder if a way to ignore/not to print stream title

**Comment by longwu9t** [comment]
If need to change the system's regional settings, 
can consider executing chcp 65001 in the CMD first. 
i don't know if it is feasible.

**Comment by longwu9t** [comment]
I tested it again, not all non-ASCII stream titles can cause the error, 
the following string caused the error:
Mandarin Flac 5.1 @ 1718 kbps  带国语解说
[cat.zip](https://github.com/user-attachments/files/15955032/cat.zip)

**Comment by Anime4000** [comment]
For File Path fix

Before:
![Internet Friendly Media Encoder 8 2 3 ( 'Luminous Horizon' )](https://github.com/Anime4000/IFME/assets/1908715/f4af4ab1-2c33-4392-889a-fdea56cf86b9)

After (not using parsed JSON):
![Internet Friendly Media Encoder 8 2 4 ( 'Eclipsed Radiance' )](https://github.com/Anime4000/IFME/assets/1908715/83c15d5a-425a-43b9-8258-0af32b0b7198)

Next fix, ignore stream `title`, so far I import it has no error, this one I need take a look more

**Comment by longwu9t** [comment]
https://github.com/Anime4000/IFME/assets/9213316/4c25e65d-2759-4943-8015-accf317b9836

This title error is definitely possible on my system, but maybe it's an isolated case?

**Comment by Anime4000** [comment]
I instruct Output Redirection to use UTF-8 Encoding, this should print correct text:
![Internet Friendly Media Encoder 8 2 4 ( 'Eclipsed Radiance' )](https://github.com/Anime4000/IFME/assets/1908715/0201a3d5-a458-4621-b6b3-5e07b5ded158)

Unicode Aware:
https://github.com/Anime4000/IFME/blob/master/IFME.FFmpeg/ReadFile.cs#L33

Try this
[IFME_try8.2.4.zip](https://github.com/user-attachments/files/15956624/IFME_try8.2.4.zip)

**Comment by longwu9t** [comment]
FFmpeg Media Info ♥
thanks!!!

**Comment by Anime4000** [comment]
did it work in your environment ?

**Comment by longwu9t** [comment]
new version works fine!

**Comment by Anime4000** [comment]
Nice! Thank You for reporting this ♥
