### ISSUE TITLE
[Add support] exhale - Open Source USAC encoder

### ISSUE THREAD

**Issue by longwu9t** [Anime4000/IFME#232]
![exhale_plugin audio1-amd64_sse json](https://github.com/Anime4000/IFME/assets/9213316/cfe3d4b8-12ef-4bbf-8682-8d914e3c7278)
The Quality of exhale can be expressed in letters, and the location of the parameters is not very friendly.
Although this works, I don't know how to write this configuration file correctly.

**Comment by Anime4000** [comment]
I try add support `exhale`

# Documentation:
## Clone and Enter Build
```
git clone https://gitlab.com/ecodis/exhale
cd exhale
mkdir build
cd build
```
## Compile Statically
```
cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -static" ../
make
```

## Check Runtime
```
Anime4000@ANIME4000-PC MINGW64 ~/exhale/build
$ ldd /home/Anime4000/exhale/build/src/app/exhale.exe                                                       ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7fff77af0000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7fff761c0000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7fff74fa0000)
        msvcrt.dll => /c/Windows/System32/msvcrt.dll (0x7fff76f90000)
```

**Comment by Anime4000** [comment]
during testing, MPC can't play the file, what player support this codec?

**Comment by longwu9t** [comment]
https://github.com/MartinEesmaa/VVCEasy

**Comment by longwu9t** [comment]
https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/0b67c83b2eadf6350587ae7c4a63a8f9bba67cae

I believe that in the near future, the official version of ffmpeg will also support USAC very well. 
In addition, foobar2000 can also play USAC normally using the components foo_pd_aac.

**Comment by longwu9t** [comment]
> during testing, MPC can't play the file, what player support this codec?
good news:
LAV Audio Decoder 0.79.2.16-git (K-Lite Codec Pack 18.4.4 Mega mpc-hc 2.3.1.12 (691b3686b))
can play mp4(vvc+usac)

**Comment by Anime4000** [comment]
![Internet Friendly Media Encoder 8 2 6 ( 'Luminous Echo' )](https://github.com/Anime4000/IFME/assets/1908715/c3f73b21-35e0-4dc7-ae74-eff607b141dc)

![image](https://github.com/Anime4000/IFME/assets/1908715/f0a82b9c-90a9-4447-9fc9-eb3c53c880be)

Nice, making changes now

**Comment by Anime4000** [comment]
Try this:
https://github.com/Anime4000/IFME/releases/tag/8.2.7

**Comment by longwu9t** [comment]
thanks!!!
very nice!

**Comment by longwu9t** [comment]
A small problem
If the source music file is multi-channel, eSBR MODE does not support ChannelDefault 0, and the option of downmixing to stereo should be provided in the configuration file. Even if xHE MODE is used instead of eSBR, if a multi-channel USAC file is generated, only foobar2000 may be able to play it normally, so it seems that ChannelDefault 2 should be the appropriate option at present.

**Comment by Anime4000** [comment]
so, eSBR mode always need down mixing to stereo if source is channel is more then 2 ?

**Comment by longwu9t** [comment]
yes
like aac hev2

**Comment by longwu9t** [comment]
HE-AAC v1  can be multi-channel ...
HE-AAC v2  can be mono or stereo
usac bases on it at least for now.

**Comment by Anime4000** [comment]
I add new property "MultiChannelSupport" in plugins definition (json) file, force to downmix when Mode not support Multi Channel

`Channel` and `ChannelDefault` remain `0` (Auto), just simplicity sake

**Comment by longwu9t** [comment]
follow your way
as your wish

**Comment by Anime4000** [comment]
Try this
https://github.com/Anime4000/IFME/releases/tag/8.2.7.a

**Comment by longwu9t** [comment]
it works!
thanks!!!

By the way
...IFME\Plugins\z\_plugin.audio-ffmpeg64_wav.json is wav(audio only)?
Maybe adding wmv (ffmpeg wmv+wma) support :)

**Comment by longwu9t** [comment]
"MultiChannelSupport": false,
This configuration item does not support ffmpeg (no free) libfdk_aac, 
it is a bit regrettable. 
if support can be added?

**Comment by longwu9t** [comment]
> "MultiChannelSupport": false, This configuration item does not support ffmpeg (no free) libfdk_aac, it is a bit regrettable. if support can be added?

My mistake
"SampleRateDefault": 0 + "MultiChannelSupport": false
When these two options appear at the same time, an error will occur.
If set a value of "SampleRateDefault": 44100 and use it with "MultiChannelSupport": false, no error will be reported. 
If use "SampleRateDefault": 0 alone, no error will occur.
I really don't understand.
However, ffmpeg (no free) libfdk_aac still works fine.

**Comment by Anime4000** [comment]
> ...IFME\Plugins\z_plugin.audio-ffmpeg64_wav.json is wav(audio only)?

the z folder just put item on the last,

> Maybe adding wmv (ffmpeg wmv+wma) support :)

I think not many going to use it

```
[INFO] Encoding audio file...
[DEBG] Command Line: "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\ffmpeg64\ffmpeg" -hide_banner -v error -i "Z:\Videos\GalGame\amegure_op_original.mpeg" -map 0:1 -acodec pcm_s16le -ar 44100 -ac 2 -f wav - | "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\xhe-aac_exhale\exhale.exe" g "audio0000_und.m4a"
  ---------------------------------------------------------------------
 | exhale - ecodis extended high-efficiency and low-complexity encoder |
 |                                                                     |
 | version 1.2.1 (x64, built on Jun 26 2024) - written by C.R.Helmrich |
  ---------------------------------------------------------------------
 Encoding 44-kHz 2-channel 16-bit WAVE to low-complexity xHE-AAC at 108 kbit/s
 Done, actual average incl. SBR data 103.54 kbit/s
 Input statistics:  File loudness -8.15 LUFS,	sample peak level -0.00 dBFS
```
so far I checked, `0` (Auto), `44100` and `48000` are just fine, with `-ac 2` in FFmpeg,

for `0` Auto, no command is passed, just `-ac 2` in eSBR

**Comment by longwu9t** [comment]
{
    "GUID": "deadbeef-0aac-0aac-0aac-0aac0aac0aac",
    "Name": "Advanced Audio Coding (FFmpeg)",
    "Version": null,
    "X64": true,
    "Format": [
        "mp4",
        "m4a",
        "mkv",
        "ts",
    ],
    "Author": {
        "Developer": "Bell, Fraunhofer, Dolby, Sony, Nokia, LG Electronics, NEC, NTT Docomo, Panasonic",
        "URL": "https://ffmpeg.org/"
    },
    "Update": {
        "VersionURL": null,
        "DownloadURL": null
    },
    "Audio": {
        "Extension": "m4a",
        "Encoder": "../ffmpeg64/ffmpeg",
        "SampleRate": [
            8000,
            12000,
            16000,
            22050,
            24000,
            32000,
            44100,
            48000
        ],
        "SampleRateDefault": 44100,
        "Channel": [
            0,
            1,
            2,
            6,
            8
        ],
        "ChannelDefault": 0,
        "Args": {
            "Pipe": false,
            "Input": "-hide_banner -v error -stats -strict -2 -i",
            "Codec": "-vn -sn -dn -c:a libfdk_aac",
            "Output": "-y",
            "Command": "-map_metadata -1 -map_chapters -1"
        },
        "Mode": [
            {
                "Name": "LC_VBR",
                "Args": "-vbr",
                "Quality": [
                    1,
                    2,
                    3,
                    4,
                    5
                ],
                "Default": 5
            },
            {
                "Name": "HE",
                "Args": "-profile:a aac_he -b:a",
                "QualityPrefix": "",
                "QualityPostfix": "k",
                "Quality": [
                    48,
                    64,
                    80,
                    96,
                    112,
                    128,
                    160
                ],
                "Default": 96
            },
            {
                "Name": "HE_V2",
                "Args": "-profile:a aac_he_v2 -b:a",
                "MultiChannelSupport": false,
                "QualityPrefix": "",
                "QualityPostfix": "k",
                "Quality": [
                    32,
                    48,
                    64,
                    80,
                    96,
                    112,
                    128
                ],
                "Default": 64
            }
        ]
    }
}

**Comment by longwu9t** [comment]
https://github.com/nanake/ffmpeg-tinderbox
ffmpeg no free with libfdk_aac
![_plugin audio-ffmpeg64_aac](https://github.com/Anime4000/IFME/assets/9213316/e29b0b71-8fe6-4d18-b3fd-8d5601f495ae)

**Comment by Anime4000** [comment]
what FFmpeg build are you using that have `libfdk_aac` ?
because I am too lazy to build/compile one

**Comment by longwu9t** [comment]
https://www.animmouse.com/p/ffmpeg-binaries/

> what FFmpeg build are you using that have `libfdk_aac` ? because I am too lazy to build/compile one

**Comment by longwu9t** [comment]
Maybe none of the configuration items in this folder (...\IFME\Plugins\ffmpeg.audio) support "SampleRateDefault": 0

**Comment by Anime4000** [comment]
> Maybe none of the configuration items in this folder (...\IFME\Plugins\ffmpeg.audio) support "SampleRateDefault": 0

mostly has valid value on the list, in case define `0` as default but not on the array list, it will use as `0`

try [IFME_try8.2.7b.zip](https://github.com/user-attachments/files/16044716/IFME_try8.2.7b.zip)

**Comment by longwu9t** [comment]
![2024-06-30_210413](https://github.com/Anime4000/IFME/assets/9213316/c2b287e5-e9c9-446b-82a6-fd777004d962)
![2024-06-30_210419](https://github.com/Anime4000/IFME/assets/9213316/4f4b422f-bb92-486f-a36a-c4979bca17ff)
![2024-06-30_210431](https://github.com/Anime4000/IFME/assets/9213316/30a3b81a-099e-43bf-9a1c-5292c501cde1)
it works 
A little problem
“Auto" Not displayed

**Comment by Anime4000** [comment]
if that works, then I code to add Auto in the list when `0` not in the list

**Comment by longwu9t** [comment]
> if that works, then I code to add Auto in the list when `0` not in the list

Very good! Looking forward to finishing it!

**Comment by Anime4000** [comment]
Ok, try this
[IFME_try8.2.7c.zip](https://github.com/user-attachments/files/16044813/IFME_try8.2.7c.zip)

**Comment by longwu9t** [comment]
Everything is perfect！
Thanks!!!

**Comment by Anime4000** [comment]
alright, now can release to public. Thank You!

**Comment by longwu9t** [comment]
^_^

**Comment by longwu9t** [comment]
：）
there is a little little problem...
0 (auto) should not upmix to stereo when the source file is mono, although this is fine in most cases.

**Comment by Anime4000** [comment]
> ：）
> there is a little little problem...
> 0 (auto) should not upmix to stereo when the source file is mono, although this is fine in most cases.

I know 🤣I did it on purpose.
I need find a way to have original data passed to Encoding Pipeline.

**Comment by Anime4000** [comment]
@longwu9t try this, it should mono to mono, stereo to stereo and downmixing
[IFME_try8.2.7d.zip](https://github.com/user-attachments/files/16045360/IFME_try8.2.7d.zip)

**Comment by longwu9t** [comment]
> @longwu9t try this, it should mono to mono, stereo to stereo and downmixing [IFME_try8.2.7d.zip](https://github.com/user-attachments/files/16045360/IFME_try8.2.7d.zip)

Except for exhale, 
ffmpeg.audio and the fdkaac and QAAC I added are all MONO auto to MONO. 
Maybe the ffmpeg pipe configuration file of exhale is hard-coded in the program?
usac supports mono...

**Comment by Anime4000** [comment]
> If there is this parameter in the configuration file, mono auto to 2ch,

this need define channel 0, 1, 2 and manually set 2.
or quick way make it stereo no matter what, ignore mono check

**Comment by longwu9t** [comment]
fdkaac hev2 does not support mono. But exhale SBR does. It's a real headache. I accept this reality. Just process it roughly to stereo.

**Comment by Anime4000** [comment]
well then, I add new entry "MonoSupport" next, if `false` then it will always process Stereo only

**Comment by longwu9t** [comment]
[fdkaac hev2 mono up-mixing]
this works well!
![_plugin audio1-amd64_sse](https://github.com/Anime4000/IFME/assets/9213316/49e001dc-f5fd-41c2-b924-7ab1e10a2091)

**Comment by longwu9t** [comment]
[fdkaac hev2 mono up-mixing]
exhale SBR mono still not support

**Comment by Anime4000** [comment]
Do you compile latest commit to support `MonoSupport` ?

**Comment by longwu9t** [comment]
> Do you compile latest commit to support `MonoSupport` ?

yes 
i pull it and compile it

**Comment by Anime4000** [comment]
now try compile see if that works

**Comment by longwu9t** [comment]
![Uploading 2024-07-02_093237.png…]()

**Comment by longwu9t** [comment]
By the way ...
![2024-07-02_094946](https://github.com/Anime4000/IFME/assets/9213316/b88d7b01-39ac-495e-9907-1ba1825a98aa)

**Comment by longwu9t** [comment]
nero_aac should not be used as the default audio codec. This is equivalent to treating nero_aac as an indispensable component of IFME. If you must have a default audio codec, consider ffmepg aac or ffmpeg ac3.

**Comment by Anime4000** [comment]
> By the way ... ![2024-07-02_094946](https://private-user-images.githubusercontent.com/9213316/344849562-b88d7b01-39ac-495e-9907-1ba1825a98aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODk2MTcsIm5iZiI6MTcxOTg4OTMxNywicGF0aCI6Ii85MjEzMzE2LzM0NDg0OTU2Mi1iODhkN2IwMS0zOWFjLTQ5NWUtOTkwNy0xYmExODI1YTk4YWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMDMwMTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTYyZTdkODhlZGE3YzIzMTA2MmM4N2YwOTc2Mjg4MWQ4NGU0NjI4OWI0YTQ2MTUwZTc4YTU5NDg3MTNmM2NiNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zXEoveC6WUpV22JItwIlnwJLrakqu5sJpopfP_1W9TA)

the "X64" is on purpose for Nero AAC, it just mean can run on 64-bit

> nero_aac should not be used as the default audio codec. This is equivalent to treating nero_aac as an indispensable component of IFME. If you must have a default audio codec, consider ffmepg aac or ffmpeg ac3.

I choose Nero AAC because many prefer Nero AAC, now I set back to FFmpeg AAC

**Comment by longwu9t** [comment]
> now try compile see if that works.

When using a separate fdkaac encoder to encode through ffmpeg's pipe, "MonoSupport": false works normally, but ffmpeg's libfdk_aac does not work using this configuration item. Is "MonoSupport": false only for ffmpeg pipe?

![2024-07-02_120951](https://github.com/Anime4000/IFME/assets/9213316/170057ba-73bf-4365-ac8c-d1c355464be5)

**Comment by Anime4000** [comment]
try again, my bad

**Comment by longwu9t** [comment]
> try again, my bad

this time
perfect
thanks!!!

**Comment by Anime4000** [comment]
I closing the issue, if found, feel free to create new issue

**Comment by longwu9t** [comment]
"MultiChannelSupport": false,
This option may cause multi-channel music files to be unable to be encoded as mono mp3, 
such as the configuration of _plugin.audio-ffmpeg64_mp3.json. 
In addition, for ffmpeg mp3 encoding, you can consider using -c:a libtwolame, 
and for ffmpeg resampling, you can consider using the built-in sox.
wait your free :)
