### ISSUE TITLE
when audio mode change, quality in background command not refresh 

### ISSUE THREAD

**Issue by longwu9t** [Anime4000/IFME#234]
https://github.com/Anime4000/IFME/assets/9213316/d899ad0f-bc17-43c1-9ecb-b01622925611

![2024-06-27_200928](https://github.com/Anime4000/IFME/assets/9213316/114d9bf3-c38d-4401-8e90-c235ec013685)
![2024-06-27_200827](https://github.com/Anime4000/IFME/assets/9213316/68776f67-0800-4720-9140-5a4bc2d2dace)

_plugin.audio-ffmpeg64_aac.json:
[plugin.audio-ffmpeg64_aac.zip](https://github.com/user-attachments/files/16013782/plugin.audio-ffmpeg64_aac.zip)
![_plugin audio-ffmpeg64_aac](https://github.com/Anime4000/IFME/assets/9213316/9e315bb9-1aab-4051-abdb-c9c506e071e3)

when audio mode change, quality in background command not refresh.
The bitrate of the first generated file is correct, 
but the bitrates of the subsequent two generated audio files are wrong.

**Comment by longwu9t** [comment]
It may be that when the MODE is changed, only the text of the GUI is refreshed, the default items can be displayed correctly in the text box of the GUI, but the background command line does not load the default values ​​in time.

**Comment by Anime4000** [comment]
I see, it didn't update/refresh when change the mode

**Comment by Anime4000** [comment]
Try this, it should be fix the issue
[IFME_try825.zip](https://github.com/user-attachments/files/16018805/IFME_try825.zip)

**Comment by longwu9t** [comment]
This version(try825) does not resolve the issue.

![2024-06-28_085116](https://github.com/Anime4000/IFME/assets/9213316/d3a65d2e-0550-4989-a6d1-0c0da584bfda)

The quality values ​​for the next two times are the same as the first time, and the default value does not take effect.

**Comment by Anime4000** [comment]
@longwu9t try this
[IFME_try8.2.6.zip](https://github.com/user-attachments/files/16030223/IFME_try8.2.6.zip)

```
Before Fix:
[DEBG] Command Line: "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\ffmpeg64\ffmpeg" -hide_banner -v error -i "Z:\Videos\GalGame\amegure_op_original.mpeg" -map 0:1 -acodec pcm_s16le -ar 44100 -f wav - | "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\nero_aac\neroAacEnc.exe" -ignorelength -if - -q 0.5 -of "audio0000_und.mp4

[DEBG] Command Line: "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\ffmpeg64\ffmpeg" -hide_banner -v error -i "Z:\Videos\GalGame\amegure_op_original.mpeg" -map 0:1 -acodec pcm_s16le -ar 44100 -f wav - | "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\nero_aac\neroAacEnc.exe" -ignorelength -if - -br 0.5 -of "audio0000_und.mp4"

After fix:
[DEBG] Command Line: "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\ffmpeg64\ffmpeg" -hide_banner -v error -i "Z:\Videos\GalGame\amegure_op_original.mpeg" -map 0:1 -acodec pcm_s16le -ar 44100 -f wav - | "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\nero_aac\neroAacEnc.exe" -ignorelength -if - -q 0.5 -of "audio0000_und.mp4

[DEBG] Command Line: "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\ffmpeg64\ffmpeg" -hide_banner -v error -i "Z:\Videos\GalGame\amegure_op_original.mpeg" -map 0:1 -acodec pcm_s16le -ar 44100 -f wav - | "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\nero_aac\neroAacEnc.exe" -ignorelength -if - -br 128000 -of "audio0000_und.mp4"
```

**Comment by longwu9t** [comment]
> @longwu9t try this [IFME_try8.2.6.zip](https://github.com/user-attachments/files/16030223/IFME_try8.2.6.zip)
> 
> ```
> Before Fix:
> [DEBG] Command Line: "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\ffmpeg64\ffmpeg" -hide_banner -v error -i "Z:\Videos\GalGame\amegure_op_original.mpeg" -map 0:1 -acodec pcm_s16le -ar 44100 -f wav - | "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\nero_aac\neroAacEnc.exe" -ignorelength -if - -q 0.5 -of "audio0000_und.mp4
> 
> [DEBG] Command Line: "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\ffmpeg64\ffmpeg" -hide_banner -v error -i "Z:\Videos\GalGame\amegure_op_original.mpeg" -map 0:1 -acodec pcm_s16le -ar 44100 -f wav - | "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\nero_aac\neroAacEnc.exe" -ignorelength -if - -br 0.5 -of "audio0000_und.mp4"
> 
> After fix:
> [DEBG] Command Line: "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\ffmpeg64\ffmpeg" -hide_banner -v error -i "Z:\Videos\GalGame\amegure_op_original.mpeg" -map 0:1 -acodec pcm_s16le -ar 44100 -f wav - | "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\nero_aac\neroAacEnc.exe" -ignorelength -if - -q 0.5 -of "audio0000_und.mp4
> 
> [DEBG] Command Line: "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\ffmpeg64\ffmpeg" -hide_banner -v error -i "Z:\Videos\GalGame\amegure_op_original.mpeg" -map 0:1 -acodec pcm_s16le -ar 44100 -f wav - | "D:\Users\Anime4000\Documents\GitHub\IFME\IFME\bin\Debug\Plugins\nero_aac\neroAacEnc.exe" -ignorelength -if - -br 128000 -of "audio0000_und.mp4"
> ```
it works fine!
thanks!!!

**Comment by Anime4000** [comment]
nice!
