### ISSUE TITLE
error: Extracting embeded attachment...

### ISSUE THREAD

**Issue by longwu9t** [Anime4000/IFME#235]
When there are multiple wav, flac and other simple audio files in the queue as source files, 
or after encoding a file, 
clearing the queue and adding a new file, 
the encoding queue often gets stuck and reports an error: Extracting embeded attachment...

Maybe for pure audio files, you should skip the Extracting step.

**Comment by Anime4000** [comment]
> Extracting embedded attachment

the audio file has thumbnail build-in ?

try this, I put check if no attachment
[IFME_try8.2.8a.zip](https://github.com/user-attachments/files/16049009/IFME_try8.2.8a.zip)
, no subs and no video should skip

**Comment by longwu9t** [comment]
Multiple music files are used as sources and encoded as m4a. Only the first file is encoded with the suffix m4a, and the rest are generated as mkv files by default.

The good news is: the queue is no longer blocked.

**Comment by longwu9t** [comment]
Further testing shows that when all the music files have the same suffix wav, 
the encoding formation can be successfully completed to generate the predetermined m4a suffix files. 
In this case, the minus button can also clear the files in the list at once. 
I don't understand it at all...

**Comment by longwu9t** [comment]
When the music source file formats in the queue are inconsistent, the encoding is processed correctly, but the remux is wrong, which may also cause the gui queue clearing function to fail. This is just my guess.

**Comment by longwu9t** [comment]
> Multiple music files are used as sources and encoded as m4a. Only the first file is encoded with the suffix m4a, and the rest are generated as mkv files by default.

My operation was not standardized. I first selected m4a (audio only), and then used the mouse to drag some files (ac3 thd dts wav flac...) to the list window. In this way, the default behavior became to convert any file type to mkv format.

Maybe the program shouldn't be too smart and preset an mkv format for the user, just rely on the user's choice and report errors in a timely manner.

**Comment by Anime4000** [comment]
I found the bug cause of it
![image](https://github.com/Anime4000/IFME/assets/1908715/41026fe9-3176-42d9-99fc-81cefbe16043)

when add to queue, it choose selected output selected (1) as default, but GUI always set to MKV (2)

**Comment by longwu9t** [comment]
[should not love MKV] works well
I added multiple types of music files to the encoding queue
The file extension ：thd mid dsf diff... [Muxing Failed]

**Comment by Anime4000** [comment]
what extension is this? thd mid dsf diff

**Comment by Anime4000** [comment]
I made a change, now you can set GUI option like Output Format, Video encoder, Audio encoder, etc...
only Video Resolution, Frame Rate, Chroma Subsample and Bit Depth use video default info, same with audio

**Comment by longwu9t** [comment]
now
works fine
:)

**Comment by longwu9t** [comment]
![image](https://github.com/Anime4000/IFME/assets/9213316/40a312bc-01df-42c0-8e97-e04d79a21a19)
A similar error occurred again. When a pure music source file such as flac contains an image as the album cover in the tag, after such a file is added to the queue, an error will be reported when any audio only output format is selected.

media info:
General
Complete name               : Z:\f.flac
Format                      : flac (raw FLAC)
File size                   : 13674452 bytes
Duration                    : 168.7067 seconds
Overall bit rate            : 648436 bps
Writing Application         : 

Video #0
ID                          : 1
Format                      : mjpeg
Width                       : 467
Height                      : 467
Frame rate mode             : Variable
Frame rate                  : 90000 fps (NaN fps)
Chroma subsampling          : 420
Bit depth                   : 8 bits
Language                    : und
Title                       : 

Audio #0
ID                          : 0
Format                      : flac
Channel(s)                  : 2
Sampling rate               : 44100 Hz
Bit Depth                   : 16 bits
Language                    : und
Title                       :

**Comment by longwu9t** [comment]
> what extension is this? thd mid dsf diff

thd is usually the suffix of Blu-ray audio track files, mid is the suffix of midi music files, dsf dff is the suffix of Super Audio CD (SACD) track files, etc.

**Comment by longwu9t** [comment]
After selecting the output format as a video, 
then click Audio Only, 
will not display the error.

**Comment by Anime4000** [comment]
that error still work in progress, I working on it

**Comment by Anime4000** [comment]
this should fix the crash

**Comment by longwu9t** [comment]
> this should fix the crash

very nice
it works!!!

**Comment by Anime4000** [comment]
> Maybe consider adding the function of encoding multiple music source files at the same time,
> so that the CPU can work more efficiently.
> ^_^

That's in my plan since, that a lot of Threading to work
