### ISSUE TITLE
error: IFME-8.2.9 audio only

### ISSUE THREAD

**Issue by longwu9t** [Anime4000/IFME#236]
https://github.com/Anime4000/IFME/assets/9213316/e6749ed9-9077-41de-8a6b-d782388ed936

As shown in the video

**Comment by longwu9t** [comment]
![2024-07-02_092041](https://github.com/Anime4000/IFME/assets/9213316/051d10bb-e8c1-4539-a2d5-29050f502fdf)
8.30 the same error

**Comment by longwu9t** [comment]
Fixed
^_!

**Comment by Anime4000** [comment]
nice
