### ISSUE TITLE
Suggestion: Add support for wmv+wma

### ISSUE THREAD

**Issue by longwu9t** [Anime4000/IFME#238]
For old machines like WINDOWS XP, 
which do not have any decoders installed, 
ffmpeg's wmv2 and wmav2 encodings are very useful.

https://github.com/Anime4000/IFME/assets/9213316/10c1363b-dcbe-4d9f-ac71-d505e3b5dc3e

**Comment by longwu9t** [comment]
Also, I added the mpg output format to support mpeg1 and mpeg2 encoding.
![image](https://github.com/Anime4000/IFME/assets/9213316/0f736f11-a3aa-4310-9514-6f817e05566c)

**Comment by Anime4000** [comment]
Codec 'vc1' is known to FFmpeg, but no encoders for it are available. FFmpeg might need to be recompiled with additional external libraries.
`Codec 'wmv3' is known to FFmpeg, but no encoders for it are available. FFmpeg might need to be recompiled with additional external libraries.`
FFmpeg for me only has `wmv1` and `wmv2`

Codec 'wmapro' is known to FFmpeg, but no encoders for it are available. FFmpeg might need to be recompiled with additional external libraries.
Codec 'wmalossless' is known to FFmpeg, but no encoders for it are available. FFmpeg might need to be recompiled with additional external libraries.
FFmpeg for me only has `wmav1` and `wmav2`

**Comment by longwu9t** [comment]
wmv2 + wmav2 
enough for old system

**Comment by longwu9t** [comment]
wmv and mpg (mpeg1 or mpeg2 + mp2 or mp3 or ac3)  often be used in office powerpoint...
so mpg is useful

**Comment by Anime4000** [comment]
can you share your mpeg and wmv json file

**Comment by longwu9t** [comment]
[Plugins.zip](https://github.com/user-attachments/files/16114854/Plugins.zip)
I just edited it casually, it's not rigorous. … :)

**Comment by Anime4000** [comment]
> [Plugins.zip](https://github.com/user-attachments/files/16114854/Plugins.zip) I just edited it casually, it's not rigorous. … :)

I see, I thought you have special args xD
