### ISSUE TITLE
After multiple files are added to the queue, only the last file is selected

### ISSUE THREAD

**Issue by longwu9t** [Anime4000/IFME#239]
This is probably not a bug, it's just inconsistent with the usual default operation of the software.
After multiple files are added to the queue, only the last file is selected
must click a file in the queue and press CTRL+A to select all to select the entire queue.
Although this operation is reasonable, it is easy to be overlooked, resulting in only the last file in the queue being encoded as expected.

https://github.com/Anime4000/IFME/assets/9213316/93355d8c-435b-480a-aa92-79fa742e3756

**Comment by Anime4000** [comment]
I did this recent commit, old one do highlight all by default. when forget to select want to edit, it apply all same

**Comment by longwu9t** [comment]
As you wish, the force is with you ^_&

**Comment by Anime4000** [comment]
I think, when plan to add another, deselect old one, so, no mistake change

**Comment by Anime4000** [comment]
I think I have fixed this issue

**Comment by longwu9t** [comment]
> I think I have fixed this issue

very very nice!
