### ISSUE TITLE
Switching between Presets sometimes doesn't change Audio settings

### ISSUE THREAD

**Issue by thefinaldegree** [Anime4000/IFME#27]
Sometimes, when you switch between presets, IFME doesn't change to the audio in the preset

**Comment by Anime4000** [comment]
Which version you currently using?

**Comment by thefinaldegree** [comment]
Sorry, I thought I had mentioned that- I'm running 4.9.4.0.

It did this to me with my original installation & a clean installation

**Comment by Anime4000** [comment]
can you try this https://github.com/Anime4000/IFME/releases/tag/v5.0-alpha.4 ?

**Comment by thefinaldegree** [comment]
Sorry, I didn't get around to trying alpha4, but I tested with beta8 & beta9 and they seem to not have the same bug so far.
I'm just testing a little bit more just in case.

**Comment by Anime4000** [comment]
this mean is ok?

**Comment by Anime4000** [comment]
This issue has been fixed :+1: IFME 5.1 won't have this problem :)
