### ISSUE TITLE
CultureInfo missing, conversion to double fails at some locales

### ISSUE THREAD

**Issue by forkicks** [Anime4000/IFME#37]
At MediaEncoder.cs, in:
public static void Video(string file, Queue item)
{
(...)
framecount = (int)Math.Ceiling(((float)item.Prop.Duration / 1000.0) * Convert.ToDouble(item.Picture.FrameRate));
(...)
}

will fail at some locales because the "." is not the decimal separator, and this assumes it is. If the call is changed to:
framecount = (int)Math.Ceiling(((float)item.Prop.Duration / 1000.0) * Convert.ToDouble(item.Picture.FrameRate, CultureInfo.InvariantCulture));
then it will work.

This was causing ifme to fail right before starting the video decoding without any related message.

**Comment by Anime4000** [comment]
At `Program.cs` I added:
`Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");`
forcing to `.` type...

but your way kind double check, I guess to be safe, I should add :+1:
