### ISSUE TITLE
Flaccl gives error during extraction

### ISSUE THREAD

**Issue by forkicks** [Anime4000/IFME#38]
Compiling current code and running it i get the following at start:
"Downloading component  6 of 12: flaccl
100,00% Completed...Extracting...The system cannot find the path specified.
Done!"

All the others work fine. I tried it on 64 and 32 bit windows, same result.

**Comment by Anime4000** [comment]
If you install on Program Files, need Admin privilege...

upon checking...
`http://master.dl.sourceforge.net/project/ifme/plugins/windows/64bit/flaccl.ifx`
to
`http://master.dl.sourceforge.net/project/ifme/plugins/windows/32bit/flaccl.ifx`

my bad :tropical_fish:
