### ISSUE TITLE
UseShellExecute = false causes file not found

### ISSUE THREAD

**Issue by forkicks** [Anime4000/IFME#39]
At TaskManager.cs, Run method, when the process start info is defined with UseShellExecute = false i always get a file not found when adding files to the queue.

I fixed it by changing UseShellExecute to true instead of false. This does cause the window to appear briefly, but this way the command works and before it didnt. This is probably caused by some interaction between the shell and the command passed to it.

**Comment by forkicks** [comment]
I could reproduce this on Windows 2012 r2 x64 as well as 32 bit Windows 8.1

**Comment by Anime4000** [comment]
weird...
`UseShellExecute = true;` similar to VB.NET `Shell();` which allow non *.exe to run... I use this to hide exe file... simply rename `exe` to `dll` and use `Shell()` it run DLL files just like normal exe, user see might be weird how `DLL` come as process..

to be safe... I try `= true;`
see how it works in both Windows and Linux

**Comment by Anime4000** [comment]
As [this explain](http://stackoverflow.com/a/2343197)
When I set to `= true` program start without stdin/out support...
I guess stay `= false`...

I still find answer how to read result without stdout... just like MeGUI encoding window...

**Comment by forkicks** [comment]
for example:

            Process p = new Process
                        {
                            StartInfo =
                            {
                                UseShellExecute = false,
                                RedirectStandardOutput = true,
                                FileName = "c:\\Windows\\System32\\cmd.exe",
                                Arguments = "ffprobe.exe -hide_banner \"" + anEntry.Path + "\"",
                                WindowStyle = ProcessWindowStyle.Hidden,
                                CreateNoWindow = true
                            }
                        };

            p.Start();

            string output = p.StandardOutput.ReadToEnd();
            p.WaitForExit();

            return output;

this will put the output from the command in the return statement, without creating a window, and it doesn't need to write to an external file and then be read back into the program. If you also need stderror, simply add RedirectStandardError = true to the parameters. 

This way you would avoid having to redirect everything to a temporary file like is happening now.

Or am i missing something?

(by the way, as weird as it seems, the ReadToEnd() and the WaitForExit are in the right order in the code example above. I took some time to figure why i could never read anything when they were reveresed.)

**Comment by forkicks** [comment]
Sorry, closed it by mistake.
