### ISSUE TITLE
About GPU Accelerated Flac

### ISSUE THREAD

**Issue by SailorOnDaTea** [Anime4000/IFME#40]
Latest flaccl from cuetools (2.1.5) won't work on older graphic cards.
Therefore some users need to use older version older version of flaccl(0.3)instead.

There is also another version called flacuda which is designed for cuda instead of opencl so with ATI it probably won't work at all.
Beside, unlike latest flaccl, flacuda and flaccl v0.3 both won't support some parameters like "--lax" and "--ignore-chunk-sizes", they will simply give error. However they supports non-standard 9,10,11 compression levels without "--lax"

Also both encoders need a value(ex: 2,4,6...) after "--cpu-threads", otherwise they won't automatically detect CPU count and will give error with "--cpu-threads"(All versions support this parameter)

Suggesting seperate plugins for Flacuda/flaccl v0.3 and Flaccl 2.1.5+ and leaving decision to user.

**Comment by Anime4000** [comment]
now IFME wont ship OpenCL/CUDA FLAC, install/mod by own need
