### ISSUE TITLE
When you type text into the ratefactor textbox, the characters are entered in the wrong order

### ISSUE THREAD

**Issue by forkicks** [Anime4000/IFME#41]
If you click the video quality->rate control->ratefactor textbox, select all text there and then start writing, text is entered in the wrong order. (if you type 21, it comes up as 12).

**Comment by Anime4000** [comment]
Text box cannot leave empty...

**Comment by Anime4000** [comment]
Move `TextChanged` event to `Leave` event
https://github.com/Anime4000/IFME/blob/master/ifme/frmMain.cs#L762-L800

**Comment by Anime4000** [comment]
this has been fixed :+1:
