### ISSUE TITLE
Temp folder not cleared

### ISSUE THREAD

**Issue by thefinaldegree** [Anime4000/IFME#48]
After encoding has finished, the Temp folder isn't cleared
(running 5.1 release)

**Comment by Anime4000** [comment]
closing program will clear, I purposely not to clear which allow user retrieve raw encoded file, now it will clear no matter what...

temporary patch: https://github.com/Anime4000/IFME/releases/tag/v5.1.2

**Comment by Anime4000** [comment]
application to have Temporary folder dump working file into it... get cleared after job done.
allow temp folder to change, allow larger space required and avoid SSD
I can put super warning about temp folder 👍
