### ISSUE TITLE
Linux: plugin programs not 100% portable

### ISSUE THREAD

**Issue by darealshinji** [Anime4000/IFME#49]
Some of the plugin programs on the Linux version require runtime dependencies like libboost and libav. And these are often not installed by default or they're available in different incompatible versions on different distributions.
I recommend you to build those programs from source and link most dependencies statically.

You can find scripts for faac, ffmsindex, libmediainfo, mkvtoolnix and mp4box that automatically build the latest release versions here: https://github.com/darealshinji/IFME/tree/portable-linux-binaries

The other plugins seem to be already portable, but I could write scripts for them too.

**Comment by Anime4000** [comment]
Under fresh install of Ubuntu 14.04, I do add and ship some binaries and with sh script<br>
example:
```
export PATH=PATH:`pwd`
```

of course I check required binaries via `ldd` command

Thanks for the script and guide, I'll include these on next release... :+1:

**Comment by Anime4000** [comment]
I moved all your sh script here: https://github.com/Anime4000/IFME/tree/master/sources/linux-portable-binaries

**Comment by darealshinji** [comment]
The new v1.8 release of x265 allows you to create a single "multilib" binary capable of handling 8, 10 and 12 bit output, specified via command line: `-D/--output-depth 8|10|12`

A script that builds such a multilib version of the latest stable release can be found [here](https://github.com/darealshinji/IFME/blob/portable-linux-binaries/x265-multilib.sh).
I've uploaded a [pre-built binary](https://github.com/darealshinji/IFME/blob/portable-linux-binaries/x265) too in case you want to test it.

**Comment by Anime4000** [comment]
That's good, I also tried on MSYS GCC 5.1 but failed on Microsoft Visual Studio
![windows 7 64-bit](https://cloud.githubusercontent.com/assets/1908715/10562276/9e28b8ca-7586-11e5-8181-b27087bbb5ec.png)

single binary will reduce line code and more simplified.
https://github.com/Anime4000/IFME/blob/master/ifme/MediaEncoder.cs#L209-L212

I not well expert on building/compile C/C++ as well static building

**Comment by darealshinji** [comment]
I was able to cross-compile it on Linux for Windows 32 and 64 bit.
The build script and pre-compiled binaries are [here](https://github.com/darealshinji/IFME/tree/portable-linux-binaries).
I've also added yasm and cmake to the apt-get line in  x265-multilib.sh.

**Comment by Anime4000** [comment]
This my script earlier, put on x265/build/msys
```
#!/bin/sh

# This script for building x265 for Internet Friendly Media Encoder
# compiled binaries will place here

mkdir -p 8bit 10bit 12bit

cp toolchain-x86_64-w64-mingw32.cmake ./12bit/
cp toolchain-x86_64-w64-mingw32.cmake ./10bit/
cp toolchain-x86_64-w64-mingw32.cmake ./8bit/

cd 12bit
cmake -G "MSYS Makefiles" -DCMAKE_TOOLCHAIN_FILE=toolchain-x86_64-w64-mingw32.cmake ../../../source -DENABLE_SHARED=OFF -DENABLE_CLI=OFF -DEXPORT_C_API=OFF -DHIGH_BIT_DEPTH=ON -DMAIN12=ON
make
cp libx265.a ../8bit/libx265_main12.a

cd ../10bit
cmake -G "MSYS Makefiles" -DCMAKE_TOOLCHAIN_FILE=toolchain-x86_64-w64-mingw32.cmake ../../../source -DENABLE_SHARED=OFF -DENABLE_CLI=OFF -DEXPORT_C_API=OFF -DHIGH_BIT_DEPTH=ON -DMAIN12=OFF
make
cp libx265.a ../8bit/libx265_main10.a

cd ../8bit
cmake -G "MSYS Makefiles" -DCMAKE_TOOLCHAIN_FILE=toolchain-x86_64-w64-mingw32.cmake ../../../source -DENABLE_SHARED=OFF -DENABLE_CLI=ON -DEXTRA_LIB="x265_main10.a;x265_main12.a" -DEXTRA_LINK_FLAGS=-L. -DLINKED_10BIT=ON -DLINKED_12BIT=ON
make
mv x265.exe ../x265.exe
```
but... Intel C Compiler 2016 and Visual Studio 2013 (MSVC12)

**Comment by darealshinji** [comment]
I'll close this since the Linux binaries of the latest release are now all portable.
