### ISSUE TITLE
WMV audio conversion isn't supported?

### ISSUE THREAD

**Issue by DominikStyp** [Anime4000/IFME#51]
I was trying to convert some WMV files. Video conversion goes fine, but at the end mkv isn't created and console gives following error: 

mkvmerge v8.4.0 ('A bettter way to fly') 64bit
Error: The file ".....\Temp\ifme\audio0000_en.wma" is a non-supported file type (Windows Media (ASF/WMV))

Is this normal? Can this be handled by IFME in other way?

**Comment by Anime4000** [comment]
Based on [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_video_container_formats#Audio_formats_supported) MKV suppose to support WMA file... I not sure `mkvtoolnix` reject this format, you can open an issue to [mkvtoolnix](https://github.com/mbunkus/mkvtoolnix) regarding this issue.

in other way:
1. Try download mkvtoolnix 8.4.0 and replace all content inside `mkvtool` folder.
2. Encode audio, not to use `Passthrough`

**Comment by DominikStyp** [comment]
It seems working with Freeware Advanced Audio Coder, I didn't check the others yet. However sometimes it's automatically changing to Passthrough (I assume it's something wrong with saving current options - for example if I save preset, and add new file to the list - it gets old settings again (?))

**Comment by Anime4000** [comment]
Okay... I look into it...
but you need select item item first before changing...

**Comment by Siensien** [comment]
Same issue than Dominik Styp here with v5.1 (fluorite diary) 64bit
Error: The file ".....\Temp\ifme\audio0000_en.wma" is a non-supported file type (Windows Media (ASF/WMV))
Sorry, doesn't understand how to use #51 fix for WMA and #51 #56 audio issue ?
Where can i find mkvtoolnix 8.4.0 ?
regards.

**Comment by Anime4000** [comment]
![mkvtoolnix gui v8 5 2 crosses 64bit](https://cloud.githubusercontent.com/assets/1908715/11154499/b3405598-8a7a-11e5-8e6a-2d3081761a44.png)
mkvtoolnix wont support Windows Media Video/Audio container, [maybe legal issue within Microsoft](https://github.com/mbunkus/mkvtoolnix/issues/751)

I adding fix, found any `*.wma` will be encoded to `FFmpeg AAC` (Default)

**Comment by Anime4000** [comment]
Upcoming IFME 5.2, either save as `mp4` or `mkv`, `wma` will encode to `AAC` via FFmpeg.
