### ISSUE TITLE
5.1: adding srt subtitles gives an error

### ISSUE THREAD

**Issue by dmancornell** [Anime4000/IFME#53]
Just upgraded to 5.1, when I use the subtitles tab to include .srt it gives an error like: "File (English) cannot be opened"

Of course I tagged the .srt as English.  Looks like IFME is looking at the language field instead of the file pointer field.

**Comment by Anime4000** [comment]
This subtitle error has been fix under IFME 5.2
https://github.com/Anime4000/IFME/blob/master/changelog.txt#L10

Upcoming update will coming soon :+1: maybe next month around november

**Comment by Anime4000** [comment]
has been fixed, in IFME 5.2
