### ISSUE TITLE
Cannot process sound if using something other than DirectShowSource

### ISSUE THREAD

**Issue by Ryoandr** [Anime4000/IFME#54]
If I try to use an .avs file with an alt source filter, audio track doesn't appears in audio tab and no audio is encoded.
something like
`v=LSMASHVideoSource("vid.mp4")`
`a=LSMASHAudioSource("vid.mp4")`
`AudioDub(v,a)`

This works in other .avs compatible encoders such as MeGUI

**Comment by Anime4000** [comment]
I added new filter detection, simply relaunch IFME for re-fetch latest filter detection file

https://github.com/Anime4000/IFME/blob/master/ifme/avisynthsource.code#L3-L4

**Comment by Ryoandr** [comment]
you also need to add `LWLibavAudioSource` and `LWLibavVideoSource` for non iso containers. They're also part of LSMASHSource, but unlike DirectShowSource or FFmpegSource2 you can't simply call LSMASHSource(file.mp4) for indexing.

LSMASH is more and more preferred to DirectShowSource and even FFMS because it's frame accurate.

**Comment by Anime4000** [comment]
Allright... I try enhanced IFME to intelligently detect Audio track inside script...

**Comment by Anime4000** [comment]
before IFME need full path, now support file name only, full path will given where script is located
