### ISSUE TITLE
Couple of GUI bugs

### ISSUE THREAD

**Issue by DominikStyp** [Anime4000/IFME#55]
1) If I save encoding preset to certain name like "test", and I try to do it again later - it creates new preset with the same name on the list, instead of overwriting old one.
2) Can't delete item from the list by DEL key (it's unconvenient to look for the icon every time).
3) After saving preset, list goes to <NEW> instead of staying at saved preset.
4) Can I delete saved preset ? (Can't find any option to do that).
5) There is no option "Save in same directory", instead every time I need to pickup directory from the list....
6) Music from "About" sometimes is turning on again after closing "About" window.

**Comment by brokenglish** [comment]
Wow, you are expecting a lot of things...
(1) and (4)
I always edit my presets straight from the source:
%IFME Installation Path%\Internet Friendly Media Encoder\profile
Just edit the .IFP files
(2) It is not that inconvenient when you are used to it, well, it is good to have but not that crucial
(3) List goes to where?
(5) Of all kinds of encoders I have used, not one, by default, saves in the same directory as the source, you either have to specify each file manually or it goes to only one destination.
(6) Seriously? (I didn't even notice that)

**Comment by DominikStyp** [comment]
1) Well I didn't knew where it stores presets
2) Other encoders has this option (TEncoder for example)
3) List goes to NEW, instead of currently saved preset
5) TEncoder has option: Output path: ...... Same as source (checkbox)
6) Yeap, I had to restart program once I've clicked "i" icon (which opens "About" window)

**Comment by DominikStyp** [comment]
7) While processing or paused video - I can't remove any item from the list. 
Do I always have to stop (and loose current progress) to do that? 
I must add that unselecting checkboxes doesn't stop program from processing videos on the list.

**Comment by Anime4000** [comment]
1. save new preset, simple change to `< new >` and save, other then that will save existing...
2. I adding `DEL` now :+1: for removing existing encoding preset.
3. 
4. delete need go to folder, I try add button for this :taxi: 
5. save as source checkbox added already, if you compile my source code, it has, or wait 5.2 :smile: 
6. I think I remove music... I not sure how .NET handle multi threaded work...

7. skip/delete queue only works when not start encoding, this because I using different **thread** to avoid GUI become not responding...

when make new **thread** cannot share same variable, so I had to copy, which mean what ever change to GUI, the new copy data not effected...

**Comment by Anime4000** [comment]
here... what is look like :smile: 
![untitled - internet friendly media encoder v5 2 archangel descending 64bit](https://cloud.githubusercontent.com/assets/1908715/10844101/2c6e47e8-7f38-11e5-8122-02b86ee16c8c.png)

**Comment by forkicks** [comment]
Thanks for this, i had hit all of the reported issues here a few times myself and was going to report them.

This makes the program look and feel more polished. Thanks!

**Comment by Anime4000** [comment]
some limitation, to let IFME capture Audio, need put first before Video, for example:
```
FFAudioSource()
FFVideoSource()
```

or can use `FFVideoSource()` alone if file has audio :smile:

**Comment by Anime4000** [comment]
now :floppy_disk: icon can be use as **new** or **existing**
first item labeled as `< new >` mean new, default value will be date & time,
other then that will be existing

**Comment by Anime4000** [comment]
This has been fix along with upcoming IFME 5.2
