### ISSUE TITLE
4GB wav file limit when converting audio?

### ISSUE THREAD

**Issue by dmancornell** [Anime4000/IFME#56]
I am getting an error on wav files larger than 4GB when re-encoding them with IFME 5.1.  This happens on large movies.  I never ran into this in version 4.x?

Exact error is: "invalid for wav, output file will be broken"

**Comment by Anime4000** [comment]
This likely issue on FFmpeg and Filesystem currently, setting Temp folder on FAT32 not recommended

**Comment by dmancornell** [comment]
I'm running on NTFS.  I think the error is with the wav format itself.  Looking at the ffmpeg code it just spits out an error if the wav file size reaches a defined limit in the header.

Anyways this is an interesting problem, any DTS audio in a 2+ hour movie will not be processed correctly.

**Comment by Anime4000** [comment]
> WAV files are usually stored uncompressed, which means that they can get quite large, but they cannot exceed 4 gigabytes due to the fact that the file size header field is a 32-bit unsigned integer (32 bit file length means a maximum of 4 gigs).

I think, change to need `pipe` method directly to audio encoder, instead of generate wav first.

**Comment by dmancornell** [comment]
Yep, that would be a good solution.

**Comment by Anime4000** [comment]
Yea... before I plan to do this, found out some encoder didn't support `pipe`/`stdin`.
Now best time to change, cons is, cannot show current %

for audio, I think no need to worry about progress and time remaining

**Comment by thefinaldegree** [comment]
Maybe do some simple maths first before starting encode, to select whether to pipe or not? Or you could split the audio file when it hits 4 GB?

**Comment by thefinaldegree** [comment]
By simple maths I mean something like:
Estimated Filesize in KB = ( ( Num-channels * Average-KbpsBitrate-for-single-channel ) * length-in-seconds ) / 8

The Bitrate might be something around 1100Kbps for a single channel? You might have to do some testing, but using that number and a movie that's 2hr14min43sec long with 6.1:

( ( 7 * 1100 ) * 8023 ) / 8 = 7,722,137.5 KB = 7.3644 GB

Then you'd know to either split the file, or pipe it instead.

**Comment by Anime4000** [comment]
That also good solution, but with pipe also reduce Disk I/O.
[Doom9 forums says](http://forum.doom9.org/showthread.php?p=1675135#post1675135):
> No stdin = useless for me if I can't use with Virtualdub's external encoder.

**Comment by Anime4000** [comment]
From now on, IFME using pipe (signed & little endian)

**Comment by Anime4000** [comment]
instruct FFmpeg to use `-acodec pcm_s16le -f wav` for example, pipe with wav header
