### ISSUE TITLE
Audio encoding settings does not stay when setting up file list

### ISSUE THREAD

**Issue by dmancornell** [Anime4000/IFME#57]
I noticed this in previous 4.x versions too and confirmed it in 5.1

When I set the audio setting to AAC with say, 320kbps, then I go to a different panel (e.g. video), then change back to the audio panel, the bitrate is reset to 128kbps.

It seems like the audio bitrate setting is not being saved somehow.

**Comment by Anime4000** [comment]
you need **select** item first (queue) before make changes...
if nothing select, it show a balloon warning... not sure you notice or not

**Comment by dmancornell** [comment]
Yep, I did see the balloon warning.  What I do is I add a bunch of videos into the list, then click each one and make the setting changes.

This is when the audio setting fails to "stick".

**Comment by Anime4000** [comment]
probably `combobox` fail to display.
did you try mix MP4 and MKV in the list?

**Comment by dmancornell** [comment]
Nope, I always use MKV only.

**Comment by Anime4000** [comment]
Here I made a quick patch: https://github.com/Anime4000/IFME/releases/tag/v5.1.3

Pre-5.2 release :+1:

**Comment by dmancornell** [comment]
Sweet.  Thanks!

**Comment by Anime4000** [comment]
Glad it works at your end :+1:
