### ISSUE TITLE
if no langage is detected, audio is marked as 'unk' and mkvmerge throws an error

### ISSUE THREAD

**Issue by Ryoandr** [Anime4000/IFME#62]
Error: 'unk' is neither a valid ISO639-2 nor a valid ISO639-1 code. See 'mkvmerg
e --list-languages' for a list of all languages and their respective ISO639-2 co
des.

You would need to import it as 'und' for undertermined

**Comment by Anime4000** [comment]
can you try this patch?
https://github.com/Anime4000/IFME/releases/tag/v5.1.4

**Comment by Ryoandr** [comment]
already using 5.1.4 but I think I found why. Some of my files have audio marked 'unk'. If I import them in IFME that 'unk' language is kept. 
I didn't see a way to change or set the language tag for audio in IFME, is there any ?

**Comment by Anime4000** [comment]
Ok... I try to fix this, replace unk to und

**Comment by Anime4000** [comment]
Ok.. can you try?
https://github.com/Anime4000/IFME/releases/tag/v5.1.5

**Comment by Ryoandr** [comment]
audio track doesn't appear in audio tab, and choosing a codec generates an error window.
```System.ArgumentOutOfRangeException: L'index était hors limites. Il ne doit pas être négatif et doit être inférieur à la taille de la collection.
Nom du paramètre : index
   à System.Collections.Generic.List`1.get_Item(Int32 index)
   à ifme.frmMain.QueueUpdate(QueueProp Id)
   à ifme.frmMain.cboAudioBit_SelectedIndexChanged(Object sender, EventArgs e)
   à System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   à System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   à ifme.frmMain.cboAudioEncoder_SelectedIndexChanged(Object sender, EventArgs e)
   à System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   à System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   à System.Windows.Forms.ComboBox.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
french windows obviously

**Comment by Anime4000** [comment]
did you download and replace existing?
my other tester just fine

**Comment by Anime4000** [comment]
Wait... I searching cause the problem

**Comment by Anime4000** [comment]
ok... try this :+1: 
https://github.com/Anime4000/IFME/releases/tag/v5.1.6

tell me if worked :smile:

**Comment by Ryoandr** [comment]
It seems it works but, new bug #64 !

**Comment by Ryoandr** [comment]
ok, it doesn't entirely work actually. It works if I open an .avs file or if I make .avs from file.
opening the file directly still keeps it as 'unk' if I open the file directly.

**Comment by Anime4000** [comment]
wait IFME 5.2 :+1:
