### ISSUE TITLE
[5.1.6] Selecting 2 or more entries in queue, then selecting 1 or none causes error window

### ISSUE THREAD

**Issue by Ryoandr** [Anime4000/IFME#64]
System.ArgumentOutOfRangeException: L'index était hors limites. Il ne doit pas être négatif et doit être inférieur à la taille de la collection.
Nom du paramètre : index
   à System.Collections.Generic.List`1.get_Item(Int32 index)
   à ifme.frmMain.clbAudioTracks_ItemCheck(Object sender, ItemCheckEventArgs e)
   à System.Windows.Forms.CheckedListBox.SetItemCheckState(Int32 index, CheckState value)
   à System.Windows.Forms.CheckedListBox.ObjectCollection.Add(Object item, CheckState check)
   à ifme.frmMain.QueueDisplay(Int32 index)
   à ifme.frmMain.lstQueue_SelectedIndexChanged(Object sender, EventArgs e)
   à System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   à System.Windows.Forms.ListView.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Also happens if 
selecting 2 or more files in queue, and then in audio tab selecting 1 audio stream.
selecting 2 or more files in queue, and then removing them (with either del key or Gui button)

**Comment by Anime4000** [comment]
I take a look of this, nice finding :smile:
