### ISSUE TITLE
Avisynth Trim command doesn't apply for audio

### ISSUE THREAD

**Issue by Ryoandr** [Anime4000/IFME#65]
let's say the video is 100 frames long, if I use 

Trim(0,49)

the video will be 50 frames long, but audio will still be 100 frames long and the encoded video will play for 100 frames.

**Comment by Anime4000** [comment]
this because IFME reads AviSynth script and find video file, then use it to encode audio, extract chapter and subtitle.

I aware of this.
future will be fully follow AviSynth script, but this will break multi-stream audio and "Passthrough" no longer valid.

**Comment by Anime4000** [comment]
I done the fix, please try :)
https://github.com/Anime4000/IFME/releases/tag/v5.1.7

**Comment by Ryoandr** [comment]
works except with opus (and passthrough of course)

Invalid bit-depth: 32
--raw-bits must be one of 8,16, or 24
avs2pipe [info]: writing 5 seconds of 48000 Hz, 2 channel audio.
avs2pipe [info]: finished, wrote 0 seconds [0%].
avs2pipe [error]: only wrote 0 of 240005 samples.

ConvertAudioTo16Bit() must be used in the avs script. 16 bits because for some reason LSmash doesn't like convert to 24 bits, I get white noise....

Also, avs2pipe isn't Large Address Aware, which can cause problems and crashes with complex scripts like QTGMC. Patching it to be LAA works well enough.

**Comment by Anime4000** [comment]
maybe replace `avs2pipe` to `ffmpeg` 32bit

**Comment by Anime4000** [comment]
Try this :)
https://github.com/Anime4000/IFME/releases/tag/v5.1.8

**Comment by Anime4000** [comment]
If audio produce a white noise, tell me :+1:

**Comment by Ryoandr** [comment]
I get white noise with opus.

**Comment by Anime4000** [comment]
D: dang opus...
what ifme send:
`avs2pipe audio {file} | ffmpeg -i - -f wav | opus ...`
with my test, no problem~

wait, I try again...

**Comment by Anime4000** [comment]
Ok... here 5.1.9 I test many files with opus, this seem work for you :)
https://github.com/Anime4000/IFME/releases/tag/v5.1.9

**Comment by Ryoandr** [comment]
It's working ! Nice work :)

**Comment by Anime4000** [comment]
glad it's working :+1:
