### ISSUE TITLE
"System can't find specified path"

### ISSUE THREAD

**Issue by DominikStyp** [Anime4000/IFME#66]
Destination file isn't created, conversion runs fine but bug seems to show before merge after this line:
"encoded 39237 frames in 1569.10s (25.01 fps), 884.35 kb/s..... "
I have newest version 5.1.6
Screenshot of the bug: http://grab.by/MenI
Bug on screenshot is in polish but translation is "System can't find specified path".

**Comment by Anime4000** [comment]
I sorry... :(
5.1.6 is way different then previous,
all inside "plugins" folder become invalid, to fix this, please download and replace:
https://sourceforge.net/projects/ifme/files/plugins/windows/

plugins `*.ifx` is using 7zip, can be open with WinRAR

**Comment by Anime4000** [comment]
Here, I made a patch, please try
https://github.com/Anime4000/IFME/releases/tag/v5.1.7

**Comment by DominikStyp** [comment]
I still had to delete plugins folder because overwriting files from this link it's not enough - audio track in merged file doesn't exist. Problem was fixed after remove and re-download plugins folder.

**Comment by Anime4000** [comment]
dont delete `plugins` folder, just delete **inside**

**Comment by Anime4000** [comment]
try this
https://github.com/Anime4000/IFME/releases/tag/v5.1.8
