### ISSUE TITLE
Problem with slider

### ISSUE THREAD

**Issue by DominikStyp** [Anime4000/IFME#67]
Why CRF value is messed up while I'm using slider - which allows to set values from 0.0 to 5.1 and this is too small CRF and huge file size (CRF should be at least 18).
http://grab.by/Mgpe - screen of the bug
... and if I change value manually in the text field, I got an error poping up form .NET Framework about wrong value range.

**Comment by Anime4000** [comment]
Ok.. I think I fixed the UI issue, try patch this file
https://github.com/Anime4000/IFME/releases/tag/v5.1.8
