### ISSUE TITLE
Manual prefix settings

### ISSUE THREAD

**Issue by DominikStyp** [Anime4000/IFME#68]
Can you make one simple upgrade ? It's about "[encoded]" prefix which is added to the converted videos - can it be defined by the user ? Please add it to the options somewhere, because in some cases prefix could be different or none (for example if I convert .wmv to .mkv i don't need prefix)

**Comment by thefinaldegree** [comment]
Since version 5 you're been able to set this in the settings.
Although, if this could have an option added to it like "prefix" or "suffix" so we could set it as a suffix instead?

**Comment by Anime4000** [comment]
![preferences](https://cloud.githubusercontent.com/assets/1908715/11415846/0d0fec9c-9443-11e5-8637-77e2b97b9f51.png)
as for now prefix file name, I add this to avoid same file name when output as origin folder

**Comment by DominikStyp** [comment]
thanks

**Comment by Anime4000** [comment]
Ok, I try
