### ISSUE TITLE
Can't start IFME 5.1 when I'm not connected to internet.

### ISSUE THREAD

**Issue by rokibhasansagar** [Anime4000/IFME#70]
#### When executing the program offline, the "Nemu Command Centre" window shows these lines:
```
 ERROR: WebClient.DownloadString() broken on current version of Mono, skipping...
 Checking for update: No Audio
 Checking for update: Passthrough (Extract all audio)
 Checking for update: avs2pipe (GCC, Avisynth 2.6)
 ERROR: WebClient.DownloadString() broken on current version of Mono, skipping...
```
 and then stays like that, like forever.

- Can't I use IFME offline?
- Does the program have to check update Every single time before starting?
- How can I use IFME completely offline?

**Comment by Anime4000** [comment]
for IFME 5.1, add `-s` to skip any internet activity, example:
`ifme.exe -s`

**Comment by rokibhasansagar** [comment]
Thanks.
I didn't know the trick. It works!
