### ISSUE TITLE
IFME Start up Error 

### ISSUE THREAD

**Issue by mrmorg** [Anime4000/IFME#71]
Hi,
I had a i3 in my server and IFME worked fine. I then upgraded to a Quad Core Xeon and now it does not start up. I have tried a reinstall. getting "Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
at ifme.program.settingsload()
at ifme.program.main(String[] args)

Please help

**Comment by Anime4000** [comment]
First, download this patch & replace
https://github.com/Anime4000/IFME/releases/tag/v5.1.9

Second, delete `plugins` folder, create `plugins` folder

Third, launch IFME (require internet to redownload plugins)

after that, you can run under offline mode by adding `-s`

**Comment by SailorOnDaTea** [comment]
9n hp xw6400, so far so good. :)

**Comment by mrmorg** [comment]
or that's great back up and running. many thanks!
