### ISSUE TITLE
Problem with fonts

### ISSUE THREAD

**Issue by forkicks** [Anime4000/IFME#72]
I have a job fail consistently when copying the fonts to the new file:

[2015/12/11 11:29:50] Error was found, sorry could finish it.
The attachment #1, ID 2867460024, MIME type application/x-truetype-font, size 76000, is written to 'ANNA.ttf'.

And then it stays there and doesn't continue to the next item on the queue. The program is not hanged (controls respond), but it doesn't continue either. I can abort it myself and try again, but it happens again.

I have (and need) the option to keep attachments enabled.

Thanks,
fK
(forgot to add, i'm using 5.1.9 64bit)

A bit more of the log:
(...)
Stream mapping:
  Stream #0:3 -> #0:0 (ass (native) -> ssa (native))
Press [q] to stop, [?] for help
size=      63kB time=00:24:03.21 bitrate=   0.4kbits/s
video:0kB audio:0kB subtitle:58kB other streams:0kB global headers:6kB muxing overhead: 9.678952%
ffmpeg version N-75275-gd13a2df Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      55.  2.100 / 55.  2.100
  libavcodec     57.  1.100 / 57.  1.100
  libavformat    57.  0.100 / 57.  0.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6.  3.100 /  6.  3.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, matroska,webm, from 'D:\temp\conv\Kill Me Baby S01E001.mkv':
  Metadata:
    title           : Kill Me Baby 01
    encoder         : libebml v1.3.0 + libmatroska v1.4.1
    creation_time   : 2015-05-04 01:42:51
  Duration: 00:24:11.20, start: 0.000000, bitrate: 2379 kb/s
    Chapter #0:0: start 0.000000, end 49.091000
    Metadata:
      title           : Prologue
    Chapter #0:1: start 49.091000, end 149.024000
    Metadata:
      title           : Opening
    Chapter #0:2: start 149.024000, end 1330.037000
    Metadata:
      title           : Episode
    Chapter #0:3: start 1330.037000, end 1420.044000
    Metadata:
      title           : Ending
    Chapter #0:4: start 1420.044000, end 1451.200000
    Metadata:
      title           : Preview
    Stream #0:0: Video: h264 (High 10), yuv420p10le(tv, bt709/bt709/unknown), 1280x720, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      title           : Kill Me Baby 01
    Stream #0:1(eng): Audio: ac3, 48000 Hz, stereo, fltp, 224 kb/s (default)
    Stream #0:2(jpn): Audio: ac3, 48000 Hz, stereo, fltp, 224 kb/s
    Stream #0:3(eng): Subtitle: ass (default)
    Metadata:
      title           : Signs/Songs
    Stream #0:4(eng): Subtitle: ass
    Metadata:
      title           : English Subs
    Stream #0:5: Attachment: ttf
    Metadata:
      filename        : ANNA.ttf
      mimetype        : application/x-truetype-font
    Stream #0:6: Attachment: ttf
    Metadata:
      filename        : 63193___.TTF
      mimetype        : application/x-truetype-font
    Stream #0:7: Attachment: ttf
    Metadata:
      filename        : ALIEN5.TTF
      mimetype        : application/x-truetype-font
    Stream #0:8: Attachment: ttf
    Metadata:
      filename        : ANA-ONEIROPARMENI82.TTF
      mimetype        : application/x-truetype-font
    Stream #0:9: Attachment: ttf
    Metadata:
      filename        : A-OTF-FolkPro-Medium.otf
      mimetype        : application/x-truetype-font
    Stream #0:10: Attachment: ttf
    Metadata:
      filename        : arial.ttf
      mimetype        : application/x-truetype-font
    Stream #0:11: Attachment: ttf
    Metadata:
      filename        : Arialtbg.ttf
      mimetype        : application/x-truetype-font
    Stream #0:12: Attachment: ttf
    Metadata:
      filename        : ARNORG.TTF
      mimetype        : application/x-truetype-font
    Stream #0:13: Attachment: ttf
    Metadata:
      filename        : BiffoMTStd.otf
      mimetype        : application/x-truetype-font
    Stream #0:14: Attachment: ttf
    Metadata:
      filename        : BirchStd.otf
      mimetype        : application/x-truetype-font
    Stream #0:15: Attachment: ttf
    Metadata:
      filename        : Bloody Stump.ttf
      mimetype        : application/x-truetype-font
    Stream #0:16: Attachment: ttf
    Metadata:
      filename        : Brady Bunch.ttf
      mimetype        : application/x-truetype-font
    Stream #0:17: Attachment: ttf
    Metadata:
      filename        : BRLNSDB.TTF
      mimetype        : application/x-truetype-font
    Stream #0:18: Attachment: ttf
    Metadata:
      filename        : BrunoJBStd.otf
      mimetype        : application/x-truetype-font
    Stream #0:19: Attachment: ttf
    Metadata:
      filename        : Complete in Him.ttf
      mimetype        : application/x-truetype-font
    Stream #0:20: Attachment: ttf
    Metadata:
      filename        : Complete_in_Him.ttf
      mimetype        : application/x-truetype-font
    Stream #0:21: Attachment: ttf
    Metadata:
      filename        : corbel.ttf
      mimetype        : application/x-truetype-font
    Stream #0:22: Attachment: ttf
    Metadata:
      filename        : Delicious-Heavy.otf
      mimetype        : application/x-truetype-font
    Stream #0:23: Attachment: ttf
    Metadata:
      filename        : DFRULE5.TTC
      mimetype        : application/x-truetype-font
    Stream #0:24: Attachment: ttf
    Metadata:
      filename        : DFRule50.ttc
      mimetype        : application/x-truetype-font
    Stream #0:25: Attachment: ttf
    Metadata:
      filename        : Duepuntozero_bold.ttf
      mimetype        : application/x-truetype-font
    Stream #0:26: Attachment: ttf
    Metadata:
      filename        : Felt Regular.ttf
      mimetype        : application/x-truetype-font
    Stream #0:27: Attachment: ttf
    Metadata:
      filename        : GILLUBCD.TTF
      mimetype        : application/x-truetype-font
    Stream #0:28: Attachment: ttf
    Metadata:
      filename        : HighlanderStd-Medium.otf
      mimetype        : application/x-truetype-font
    Stream #0:29: Attachment: ttf
    Metadata:
      filename        : icedeart.ttf
      mimetype        : application/x-truetype-font
    Stream #0:30: Attachment: ttf
    Metadata:
      filename        : IcedEarth.ttf
      mimetype        : application/x-truetype-font
    Stream #0:31: Attachment: ttf
    Metadata:
      filename        : KompaktLTStd.otf
      mimetype        : application/x-truetype-font
    Stream #0:32: Attachment: ttf
    Metadata:
      filename        : ksbrush.ttf
      mimetype        : application/x-truetype-font
    Stream #0:33: Attachment: ttf
    Metadata:
      filename        : lazy_dog.ttf
      mimetype        : application/x-truetype-font
    Stream #0:34: Attachment: ttf
    Metadata:
      filename        : linkin.ttf
      mimetype        : application/x-truetype-font
    Stream #0:35: Attachment: ttf
    Metadata:
      filename        : MECHAG.TTF
      mimetype        : application/x-truetype-font
    Stream #0:36: Attachment: ttf
    Metadata:
      filename        : Mechanic_Pencil.ttf
      mimetype        : application/x-truetype-font
    Stream #0:37: Attachment: ttf
    Metadata:
      filename        : MinionPro-Regular.otf
      mimetype        : application/x-truetype-font
    Stream #0:38: Attachment: ttf
    Metadata:
      filename        : Montara-Gothic.otf
      mimetype        : application/x-truetype-font
    Stream #0:39: Attachment: ttf
    Metadata:
      filename        : PAPEJE.TTF
      mimetype        : application/x-truetype-font
    Stream #0:40: Attachment: ttf
    Metadata:
      filename        : ReliqStd-Active.otf
      mimetype        : application/x-truetype-font
    Stream #0:41: Attachment: ttf
    Metadata:
      filename        : ROC_____.TTF
      mimetype        : application/x-truetype-font
    Stream #0:42: Attachment: ttf
    Metadata:
      filename        : ROCK.TTF
      mimetype        : application/x-truetype-font
    Stream #0:43: Attachment: ttf
    Metadata:
      filename        : SCAR6.TTF
      mimetype        : application/x-truetype-font
    Stream #0:44: Attachment: ttf
    Metadata:
      filename        : SerifaStd-Light.otf
      mimetype        : application/x-truetype-font
    Stream #0:45: Attachment: ttf
    Metadata:
      filename        : SF Ferretopia Bold.ttf
      mimetype        : application/x-truetype-font
    Stream #0:46: Attachment: ttf
    Metadata:
      filename        : y2k.ttf
      mimetype        : application/x-truetype-font
    Stream #0:47: Attachment: ttf
    Metadata:
      filename        : YanoneTagesschrift.ttf
      mimetype        : application/x-truetype-font
Output #0, ass, to 'sub0001_eng.ass':
  Metadata:
    title           : Kill Me Baby 01
    encoder         : Lavf57.0.100
    Chapter #0:0: start 0.000000, end 49.091000
    Metadata:
      title           : Prologue
    Chapter #0:1: start 49.091000, end 149.024000
    Metadata:
      title           : Opening
    Chapter #0:2: start 149.024000, end 1330.037000
    Metadata:
      title           : Episode
    Chapter #0:3: start 1330.037000, end 1420.044000
    Metadata:
      title           : Ending
    Chapter #0:4: start 1420.044000, end 1451.200000
    Metadata:
      title           : Preview
    Stream #0:0(eng): Subtitle: ssa
    Metadata:
      title           : English Subs
      encoder         : Lavc57.1.100 ssa
Stream mapping:
  Stream #0:4 -> #0:0 (ass (native) -> ssa (native))
Press [q] to stop, [?] for help
size=     101kB time=00:24:06.25 bitrate=   0.6kbits/s
video:0kB audio:0kB subtitle:96kB other streams:0kB global headers:6kB muxing overhead: 5.829162%
[2015/12/11 11:29:50] Error was found, sorry could finish it.
The attachment #1, ID 2867460024, MIME type application/x-truetype-font, size 76000, is written to 'ANNA.ttf'.

**Comment by forkicks** [comment]
After a reboot it worked. No idea why it failed in the first place and always in the same place.
I'm closing the issue.

**Comment by forkicks** [comment]
I closed it too soon. It just happened again, now with a different font file.

**Comment by Anime4000** [comment]
You try to extract embedded font?

**Comment by Anime4000** [comment]
try this 5.1.10_pre5.2
https://github.com/Anime4000/IFME/releases/tag/v5.1.10

**Comment by forkicks** [comment]
mkvextract attachments <filename> 1 2 3 4 ... 25 26
(it has 26! attachments) works fine and extracts all files.

I am testing your release now.

**Comment by forkicks** [comment]
It converted two files it was having issues before. I'll run a longer batch to make sure. 

Thanks for the quick reply!

**Comment by forkicks** [comment]
Seems to be working now, it has converted 6 files without choking on the attachments. 
Again, thanks.

**Comment by Anime4000** [comment]
Great to hear that, after long delay, it's time to release 5.2 :+1:

**Comment by SailorOnDaTea** [comment]
Sorry to reopen this topic but looks like TTC is not recognized.<br>

File contains these fonts(mediaInfo):<br>
A-OTF-FutoMinA101Pro-Bold.otf / arial.ttf / arial_0.ttf / Arialtbg.ttf / Brady Bunch.ttf / Brady Bunch_0.ttf / DFMaruGothic-Bd-Lite.ttf / FG角ｺﾞｼｯｸ体Ca-L & FGP角ｺﾞｼｯｸ体Ca-L .TTC / FJ-KanteiryuEdomoji-Lite.ttf / FONTIN_SANS.OTF / FONTIN_SANS_BI.OTF / FOT-GrecoStd-B.otf / icedeart.ttf / icedeart_0.ttf / LEHN096.TTF / LLRUG.ttf / MECHAG.TTF / MECHAG_0.TTF / Old_Newspaper_Font.ttf / trebuc.ttf / trebuc_0.ttf / Unisketch-light_limited.ttf / y2k.ttf / y2k_0.ttf / ALIEN5.TTF / ALIEN5_0.TTF<br><br>
In CLI it looks like this. But in temp folder there is this file. It is still encoding so I rather call it a bug instead of issue right now. I will see output files and update later. I tried a few more files and it is persistent with this type of attachment/stream.<br>

![2015-12-21 10 33 42](https://cloud.githubusercontent.com/assets/10913460/11926648/212fb8d4-a7cf-11e5-8724-2318c05dd16d.png) <br>

![2015-12-21 10 36 08](https://cloud.githubusercontent.com/assets/10913460/11926650/2135f6ae-a7cf-11e5-9782-d480826b6dd8.png) <br>

![2015-12-21 10 34 35](https://cloud.githubusercontent.com/assets/10913460/11926649/21311d64-a7cf-11e5-8e66-9b9f02510ee0.png)

**Comment by Anime4000** [comment]
Windows Console only display ANSI, any UTF/Unicode will converted to ANSI, but output file name will written in UTF8 (linux) and Unicode (Windows)

**Comment by SailorOnDaTea** [comment]
No no.. look I am aware of that ANSI display, however I told you file is still available in temp folder with Japanese name. But check this out-> output file contains these fonts as attachment(MediaInfo):<br>

ALIEN5.TTF / ALIEN5_0.TTF / arial.ttf / Arialtbg.ttf / arial_0.ttf / Brady Bunch.ttf / Brady Bunch_0.ttf / DFMaruGothic-Bd-Lite.ttf / FJ-KanteiryuEdomoji-Lite.ttf / icedeart.ttf / icedeart_0.ttf / LEHN096.TTF / LLRUG.ttf / MECHAG.TTF / MECHAG_0.TTF / Old_Newspaper_Font.ttf / trebuc.ttf / trebuc_0.ttf / Unisketch-light_limited.ttf / y2k.ttf / y2k_0.ttf / A-OTF-FutoMinA101Pro-Bold.otf / FONTIN_SANS.OTF / FONTIN_SANS_BI.OTF / FOT-GrecoStd-B.otf
<br><br>

TTC is not included in output.

**Comment by Anime4000** [comment]
Try this
https://github.com/Anime4000/IFME/releases/tag/v5.1.13

**Comment by SailorOnDaTea** [comment]
yay! it works now!
