### ISSUE TITLE
Problem with mkvmerge at the end of conversion

### ISSUE THREAD

**Issue by forkicks** [Anime4000/IFME#73]
I get this on one file:

"encoded 34044 frames in 2583.37s (13.18 fps), 1278.85 kb/s, Avg QP:26.25
mkvmerge v8.5.2 ('Crosses') 64bit
Error: 'bol' is neither a valid ISO639-2 nor a valid ISO639-1 code. See 'mkvmerge --list-languages' for a list of all languages and their respective ISO639-2 codes.
[2015/12/14 10:20:54] Completed in 43m 11s 55ms for D:\temp\conv\Senran Kagura S01E002.mkv
[2015/12/14 10:20:54] All Queue Completed in 43m 11s 58ms"

and the output file is not created. There is no error during conversion, it just fails at the end. Mkvmerge does not like something about the output. 

fK

**Comment by Anime4000** [comment]
* you using latest mkvtoolnix.
* which version of IFME you use?

Upon checking latest commit: https://github.com/Anime4000/IFME/blob/master/ifme/iso.code
`bol` not listed, I guess FFmpeg made it up

**Comment by forkicks** [comment]
Just did a clean installation of ifme, with the 5.2 beta you just posted. Same issue.

encoded 34044 frames in 2893.66s (11.77 fps), 1278.92 kb/s, Avg QP:26.25
mkvmerge v8.4.0 ('A better way to fly') 64bit
Error: 'bol' is neither a valid ISO639-2 nor a valid ISO639-1 code. See 'mkvmerge --list-languages' for a list of all languages and their respective ISO639-2 codes.
[2015/12/14 12:42:40] Completed in 48m 22s 726ms for D:\temp\conv\Senran Kagura S01E002.mkv
[2015/12/14 12:42:40] All Queue Completed in 48m 22s 734ms

**Comment by forkicks** [comment]
Btw, the language the file has is japanese (jpn). I wonder where that bol comes from.

**Comment by forkicks** [comment]
This is the mediainfo of the file. There are some "bol" in parts of the font names, perphaps it's trying to read from there?


General
Unique ID                      : 254090821034688456276236048592357348611 (0xBF281CB16FB753928C41B9717600D503)
Complete name                  : D:\temp\conv\Senran Kagura S01E002.mkv
Format                         : Matroska
Format version                 : Version 2
File size                      : 1.40 GiB
Duration                       : 23mn 39s
Overall bit rate mode          : Variable
Overall bit rate               : 8 480 Kbps
Encoded date                   : UTC 2013-08-14 20:17:56
Writing application            : mkvmerge v5.0.1 ('Es ist Sommer') built on Oct  9 2011 11:55:43
Writing library                : libebml v1.2.2 + libmatroska v1.3.0
Attachements                   : CronosPro-BoldCaptIt.otf / CronosPro-Semibold.ttf / CronosPro-SemiboldIt.ttf / CronosPro-Bold.otf / Copybook.TTF / FuckMyr v9001.ttf / Hira v8.ttf / japab.TTF / Joshiraku v9.ttf / Maid TS 2 H.ttf / Maid TS 2 Hsc.ttf / Senran gothic ep.ttf / Senran.ttf / Senran-KagoMoji-W12.ttf / SubSymbol.ttf / ARCENA.ttf / Chuu2-next.ttf

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High 10@L5.1
Format settings, CABAC         : Yes
Format settings, ReFrames      : 16 frames
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 23mn 39s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 23.976 fps
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 10 bits
Scan type                      : Progressive
Title                          : 10bit H.264 - 1080p
Writing library                : x264 core 129 r2245+729M 1a52e03
Encoding settings              : cabac=1 / ref=16 / deblock=1:-1:-1 / analyse=0x3:0x133 / me=umh / subme=11 / psy=1 / fade_compensate=0.00 / psy_rd=0.70:0.00 / mixed_ref=1 / me_range=32 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=18 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / fgo=0 / bframes=16 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=240 / rc=crf / mbtree=1 / crf=14.0 / qcomp=0.90 / qpmin=0 / qpmax=81 / qpstep=4 / ip_ratio=1.40 / aq=3:0.82
Language                       : Japanese
Default                        : Yes
Forced                         : No
Color range                    : Limited
Color primaries                : BT.709
Transfer characteristics       : BT.709
Matrix coefficients            : BT.709

Audio
ID                             : 2
Format                         : FLAC
Format/Info                    : Free Lossless Audio Codec
Codec ID                       : A_FLAC
Duration                       : 23mn 39s
Bit rate mode                  : Variable
Channel(s)                     : 2 channels
Sampling rate                  : 48.0 KHz
Bit depth                      : 16 bits
Title                          : 2.0 FLAC
Writing library                : libFLAC 1.3.0 (UTC 2013-05-26)
Language                       : Japanese
Default                        : Yes
Forced                         : No

Text
ID                             : 3
Format                         : ASS
Codec ID                       : S_TEXT/ASS
Codec ID/Info                  : Advanced Sub Station Alpha
Compression mode               : Lossless
Title                          : Hiryuu
Language                       : English
Default                        : Yes
Forced                         : No

Menu
00:00:00.000                   : en:Prologue
00:01:39.016                   : en:Opening
00:03:08.980                   : en:Part A
00:11:43.953                   : en:Eyecatch
00:11:49.959                   : en:Part B
00:21:54.897                   : en:Ending
00:23:24.902                   : en:Preview

**Comment by Anime4000** [comment]
try do
`ffmpeg -i file.mkv`

IFME fully relying on `ffmpeg`

**Comment by forkicks** [comment]
There you go:

F:\New folder\Internet Friendly Media Encoder\plugins\ffmpeg>ffmpeg -i "d:\temp\conv\Senran Kagura S01E002.mkv"
ffmpeg version N-75275-gd13a2df Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      55.  2.100 / 55.  2.100
  libavcodec     57.  1.100 / 57.  1.100
  libavformat    57.  0.100 / 57.  0.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6.  3.100 /  6.  3.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, matroska,webm, from 'd:\temp\conv\Senran Kagura S01E002.mkv':
  Metadata:
    encoder         : libebml v1.2.2 + libmatroska v1.3.0
    creation_time   : 2013-08-14 20:17:56
  Duration: 00:23:39.92, start: 0.000000, bitrate: 8479 kb/s
    Chapter #0:0: start 0.000000, end 99.016000
    Metadata:
      title           : Prologue
    Chapter #0:1: start 99.016000, end 188.980000
    Metadata:
      title           : Opening
    Chapter #0:2: start 188.980000, end 703.953000
    Metadata:
      title           : Part A
    Chapter #0:3: start 703.953000, end 709.959000
    Metadata:
      title           : Eyecatch
    Chapter #0:4: start 709.959000, end 1314.897000
    Metadata:
      title           : Part B
    Chapter #0:5: start 1314.897000, end 1404.902000
    Metadata:
      title           : Ending
    Chapter #0:6: start 1404.902000, end 1419.919000
    Metadata:
      title           : Preview
    Stream #0:0(jpn): Video: h264 (High 10), yuv420p10le(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      title           : 10bit H.264 - 1080p
    Stream #0:1(jpn): Audio: flac, 48000 Hz, stereo, s16 (default)
    Metadata:
      title           : 2.0 FLAC
    Stream #0:2(eng): Subtitle: ass (default)
    Metadata:
      title           : Hiryuu
    Stream #0:3: Attachment: ttf
    Metadata:
      filename        : CronosPro-BoldCaptIt.otf
      mimetype        : application/x-truetype-font
    Stream #0:4: Attachment: ttf
    Metadata:
      filename        : CronosPro-Semibold.ttf
      mimetype        : application/x-truetype-font
    Stream #0:5: Attachment: ttf
    Metadata:
      filename        : CronosPro-SemiboldIt.ttf
      mimetype        : application/x-truetype-font
    Stream #0:6: Attachment: ttf
    Metadata:
      filename        : CronosPro-Bold.otf
      mimetype        : application/x-truetype-font
    Stream #0:7: Attachment: ttf
    Metadata:
      filename        : Copybook.TTF
      mimetype        : application/x-truetype-font
    Stream #0:8: Attachment: ttf
    Metadata:
      filename        : FuckMyr v9001.ttf
      mimetype        : application/x-truetype-font
    Stream #0:9: Attachment: ttf
    Metadata:
      filename        : Hira v8.ttf
      mimetype        : application/x-truetype-font
    Stream #0:10: Attachment: ttf
    Metadata:
      filename        : japab.TTF
      mimetype        : application/x-truetype-font
    Stream #0:11: Attachment: ttf
    Metadata:
      filename        : Joshiraku v9.ttf
      mimetype        : application/x-truetype-font
    Stream #0:12: Attachment: ttf
    Metadata:
      filename        : Maid TS 2 H.ttf
      mimetype        : application/x-truetype-font
    Stream #0:13: Attachment: ttf
    Metadata:
      filename        : Maid TS 2 Hsc.ttf
      mimetype        : application/x-truetype-font
    Stream #0:14: Attachment: ttf
    Metadata:
      filename        : Senran gothic ep.ttf
      mimetype        : application/x-truetype-font
    Stream #0:15: Attachment: ttf
    Metadata:
      filename        : Senran.ttf
      mimetype        : application/x-truetype-font
    Stream #0:16: Attachment: ttf
    Metadata:
      filename        : Senran-KagoMoji-W12.ttf
      mimetype        : application/x-truetype-font
    Stream #0:17: Attachment: ttf
    Metadata:
      filename        : SubSymbol.ttf
      mimetype        : application/x-truetype-font
    Stream #0:18: Attachment: ttf
    Metadata:
      filename        : ARCENA.ttf
      mimetype        : application/x-truetype-font
    Stream #0:19: Attachment: ttf
    Metadata:
      filename        : Chuu2-next.ttf
      mimetype        : application/x-truetype-font
At least one output file must be specified

F:\New folder\Internet Friendly Media Encoder\plugins\ffmpeg>

**Comment by Anime4000** [comment]
I making patch now, hold on!

**Comment by Anime4000** [comment]
try this:
https://github.com/Anime4000/IFME/releases/tag/v5.1.12

**Comment by forkicks** [comment]
Worked fine!

thanks,
fK
