### ISSUE TITLE
grey screen after encoding with "high frame rate by svp"

### ISSUE THREAD

**Issue by lyolyalya** [Anime4000/IFME#75]
sorry for my english, but i have grey screen in my output file after encoding.i have a sound, but nothing else.for somehow reason i have hfrgen.dll v 0.0.2 instead v.0.0.2.1 like shown in a video and my interframe is not "generate interframe/hfr" but "high frame rate by svp"...what i did wrong?everything else looks right...

**Comment by Anime4000** [comment]
may I know which version you use?

**Comment by Anime4000** [comment]
maybe after generate (by click OK) then try preview code

**Comment by lyolyalya** [comment]
i use 5.1.0.0 with windows 10x64...regular encoding works fine.in the preview i see the same grey picture...

**Comment by Anime4000** [comment]
after apply generate interframe, can you open the file and paste here? I afraid some code generation is wrong

**Comment by lyolyalya** [comment]
LoadPlugin("L:\Raw\InterFrame-2.8.2\InterFrame-2.8.2\Dependencies\svpflow1.dll")
LoadPlugin("L:\Raw\InterFrame-2.8.2\InterFrame-2.8.2\Dependencies\svpflow2.dll")
Import("L:\Raw\InterFrame-2.8.2\InterFrame-2.8.2\InterFrame2.avsi")
Cores=8
SetMemoryMax(512)
SetMTMode(3, Cores)
DirectShowSource("L:\Фильма\Клипы\Разное\B.o.B feat. Bruno Mars - Nothin' On You.mpg").ConvertToYV12()
SetMTMode(2)
InterFrame(Cores=Cores, Preset="Medium", Tuning="Film", FrameDouble=false, GPU=false, InputType="2D")
