### ISSUE TITLE
no saved files

### ISSUE THREAD

**Issue by hocuspocus69** [Anime4000/IFME#76]
i'm on windows 7 64bit with 5.1 fluorite diary
randomly no saved files nor in your default directory videos\ifme nor in my select directory
i see growing file in temp but after that not saving everywhere
is there some log file i can search in my PC?
downloaded 5.1.11 action 52 everything perfect!!!!!

**Comment by SailorOnDaTea** [comment]
Please apply this patch and retry.
https://github.com/Anime4000/IFME/releases/tag/v5.1.13

**Comment by YellowHerbz** [comment]
I did what you said to do, and it did not fix the problem. I am currently using version v5.1.13(Action 52) 64bit and this is annoying when you have tried to encode videos 2-3 times and you get the same results. And it's very, very frustrating when v6 and the new alpha v7 runs into this error "error was found, sorry could finish it" does anyone know how to fix this problem on any version 5.1 or above?
