### ISSUE TITLE
OPUS encodes multichannel audio wrong

### ISSUE THREAD

**Issue by Ryoandr** [Anime4000/IFME#78]
I tried to encode a DTS 5.1 track, and it resulted on channels being assigned wrong all over the place, center became left-front, left went left-surround, right became LFE...
I tried encoding the same track with megui, and it worked fine.

And as a side note, opus will auto downmixing to stereo if surround channels aren't used enough (and apparently no way to force surround encoding). Because of this I couldn't encode a channel test video ; and channel downmixing was also wrong here.

**Comment by SailorOnDaTea** [comment]
when  check opusenc.exe -h it shows only options for how many channels as raw input and endianness… so there is not much can be done on encoder side.

i guess it should be done in previous step.

**Comment by Anime4000** [comment]
I instruct `FFmpeg` to pipe with `header`. The `header` contain information like, how many channel, how channel is mapping, what is decoding BitDepth, what is Sample Rate and more...

Oddly only `opus.exe` cannot read `header` given by `FFmpeg`, other encoders like `FAAC`, `NeroAAC`, `OGG` can read `header` given by `FFmpeg`.

You may send **bug** report to Xiph or Mozilla about `Opus`.

alternatively you can make simple plugins definition file (`ini`) and use FFmpeg as encoder, I guarantee `FFmpeg` pipe to `FFmpeg` will work perfectly

here using FFmpeg to encode Opus
save and put it on `ffmpeg\ffmpeg-opus.ini`
```ini
[info]
guid = ffffffff-1234-4321-1234-faceb00cdead
type = audio
support = mkv

[profile]
arch = 64
name = Opus (FFmpeg)
dev = FFmpeg Team
ver = N-75275-gd13a2df
web = http://www.audiocoding.com/

[provider]
name = IFME
update = 
download = 

[app]
bin = ffmpeg
ext = opus
quality = 45k,64k,80k,96k,112k,128k,160k,192k,224k,256k,320k,512k
default = 128k

[arg]
; Audio encoding is done by pipe/stdin, by default IFME instruct ffmpeg to pipe with wav header.
; Some audio encoder like OPUS still require RAW arguments even wav header is provided.
; Some audio encoder support pipe with header, leave RAW arguments empty.

; Default data presentation: Little Endian, Signed
; If encoder required, take note this place holder:
; {0} mean Sample rate in Hz, eg: 44100, 48000, 192000
; {1} mean Bit, eg: 8, 16, 24
; {2} mean channel, eg: 1, 2, 3, 6, 8
raw = 
input = -i -
output = -y
bitrate = -acodec libopus -b:a
advance = -vbr on -compression_level 10
```

**Comment by Ryoandr** [comment]
It works, channel location is now fine when using ffmpeg :grinning:

**Comment by Anime4000** [comment]
Nice, it apper `opus.exe` didn't read `header`

**Comment by Krautmaster** [comment]
Hm, there seems to be a problem coming from a DTS track with 5.1 Side mapping. Any how opus cant deal with it and once I force the 5.1 mapping, side becomes rear (i think side is better therefor).

Will I need to force 7.1 mapping to keep the original 5.1 track like it is and to have "silent" rear tracks with my file?

**Comment by Anime4000** [comment]
@Krautmaster Please use IFME 7, it should fix audio mapping, since `pipe` encoding didn't receive channel mapping

**Comment by Anime4000** [comment]
this has been fixed 👍
