### ISSUE TITLE
Is it possible to encode avs files in 10/12 bits ?

### ISSUE THREAD

**Issue by Ryoandr** [Anime4000/IFME#79]
If I use an .avs file, I can't select bit depth, it's grayed out. The only workaround is to encode a huffyuv .avi file and then feed it to IFME, which is both time and space consuming.

And even if the source is 8bit, there are known benefits to encoding in 10bits, especially with anime/cg material. Color gradients look much better in 10bits

**Comment by Anime4000** [comment]
As far I know & a lot of testing AviSynth is only 8bit, if you do 10bit or 12bit, output will be 8bit (result) + 2bit (extra bit), video will be 1080p * 2 for example

I tried a lot, no luck, AviSynth :cry:

**Comment by Ryoandr** [comment]
even if original source and/or avisynth output is 8bits, for some contents, it is worth encoding to 10bits as I said. The intermediate huffyuv I created is standard 8bits, and comparing 8 vs 10 encode, I can clearly see the 10bits is better.
![8-10 comp](https://cloud.githubusercontent.com/assets/7342592/12491935/fe7cf3a2-c07d-11e5-96ca-d5d59e4bf3ae.png)

**Comment by Anime4000** [comment]
I saw it... maybe need 10 bit AviSynth.dll ?
or try dithering?

**Comment by Ryoandr** [comment]
isn't it possible to just allow us to select 10bit x265 ? I am already using avisynth 2.6 MT, which should support 10bits, but it isn't relevant here, as I don't use avisynth to do 10bit stuff
in any case I have a ghetto solution for now, I just rename the x265 exe to which bitdepth I need :tongue:

**Comment by Anime4000** [comment]
Future IFME AviSynth 32bit & 64bit support, and ...
no longer using `avs2pipe`, now fully `FFmpeg`, if detected 8bit, 8bit will be use
![filedusersanime4000documentsvisual studio 2015projectsffmpegdotnetffmpegtestbinreleaseffmpegtest exe](https://cloud.githubusercontent.com/assets/1908715/12493487/29b50b76-c0c0-11e5-9557-82ace3a67de7.png)

**Comment by Ryoandr** [comment]
so with ffmpeg, will it be possible to pass --output-depth 10 to get a 10bit encoding ?

**Comment by Anime4000** [comment]
This is the deal, can you share your AviSynth code and library that output 10bit? I like to test with IFME 6.0 now... IFME now fully depend on FFmpeg, anything FFmpeg detect, automatic send to x265

**Comment by Ryoandr** [comment]
As I said, the avisynth test script (and the source file) doesn't use 10bits, it's just

    LWLibavVideoSource("video.mkv")
    Trim(72540, 74011)

i then just used avspmod vfw to output a huffuy lossless file.
the avisynth I use is 2.6 MT 2015.02.20 
http://forum.doom9.org/showthread.php?t=148782

However, as I said, avisynth 8 or 10 bit doesn't matter for now  . All I need is to be able to select 10bit encoder, be it by using `x265-10.exe` or with passing `main10` argument to ffmpeg.

**Comment by Anime4000** [comment]
ok wait, I release IFME 6.0 beta anytime now wait a moment

**Comment by Anime4000** [comment]
sorry for delay, here version 6.0
https://github.com/Anime4000/IFME/releases/tag/v6.0

please try, tell if worked

**Comment by Ryoandr** [comment]
It works ! Thank you ! :smile:

**Comment by Anime4000** [comment]
Nice... :+1:
