### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by mrmorg** [Anime4000/IFME#80]
Hi I have been using IFME for a while and now i have just upgraded to Dual Xeons and now the program doesnt load. i have tried a reinstall but same happens.
![imfe](https://cloud.githubusercontent.com/assets/16198405/12508208/9c64693c-c0f2-11e5-9122-4c3da68e7f57.png)

**Comment by Anime4000** [comment]
Try use this
https://github.com/Anime4000/IFME/releases/tag/v5.1.11
