### ISSUE TITLE
[Linux] Cannot add files from external source

### ISSUE THREAD

**Issue by toynbeeidea** [Anime4000/IFME#83]
I am using ifme-xterm under XFCE in Manjaro Linux.

I keep my video files on a large second drive, mounted as /run/media/[username]/[devicename].

If I try to add a file and navigate to that path, IFME crashes out immediately.  If I try to drag the file into the IFME window, I get a nice long error message that I can't copy from the console, because the strandard ctrl-C CLOSES the whole thing instead of copying like it normally should.

**Comment by Anime4000** [comment]
IFME build top of WinForms, which is Win32 GUI not work pretty well on Linux, so need use **add file** button...

also which version you use?
can you try latest commit? simply run `./configure` & `make`
