### ISSUE TITLE
Error was found during indexing

### ISSUE THREAD

**Issue by DimensioX1** [Anime4000/IFME#84]
everytime i try enconding something it gives error when trying to index the file and says:
"Error was found, sorry could finish it."
pic:
http://i.imgur.com/RINe7aH.png

I tried many file, but they all give the same error

**Comment by Anime4000** [comment]
have you try change from `Seeking` to `Decoding` at Option → Performance window

**Comment by DimensioX1** [comment]
Yes. it's still give the same error.

**Comment by Anime4000** [comment]
I aware of this error, better use older version, I rewrite code from begining

**Comment by Altis8** [comment]
I had the same error and as per your recommendation I removed the ifme-6.1.0.0-x86x64_windows version and installed the ifme-5.1.0.0-x86x64_windows version.
This one gets stuck while updating the FFmpeg file.  It reaches 100 % but freezes right there (see attached picture).
Any suggestions?
![ifme_51_ffmpeg_update_freeze](https://cloud.githubusercontent.com/assets/18055206/14027547/d84de4c0-f200-11e5-80b5-af2a0ec5297e.jpg)

**Comment by Anime4000** [comment]
do this:
`ifme.exe -s`
this will skip updates

**Comment by Altis8** [comment]
Thank you for your time and effort.
This solution works.
You probably know this, I am writing back for the benefit of others who may have the same problem.
Thanks once again :-)

**Comment by YellowHerbz** [comment]
Sorry for not understanding, but this is very unspecific. What am I supposed to do? "Do this" is not helpful at all. From my understanding, you are telling us to rename application, which I tried, but it didn't work, and might be because ".exe" isn't in the fie name for me, just "ifme"

**Comment by thefinaldegree** [comment]
The 'do this' is talking about setting launch options in the shortcut to
IFME.
If you're not sure how to do this, then I would suggest doing a Google
search for "setting launch options ____" where the blank is your operating
system.
