### ISSUE TITLE
V 6.1.0.0 - Many errors

### ISSUE THREAD

**Issue by SilentDude80** [Anime4000/IFME#85]
Hi,

I just updated from V.5 to V.6 and now I get many error messages

Right after program start (IFME does no updates in console window like in V5):
http://pastebin.com/G3EdSH3a

In the message window I can click "Weiter" (Continue in German) and IFME window opens. But on almost every action I get similar error messages, e.g. Switching from "MKV" to "MP4" format:
http://pastebin.com/WL8f7wqg

Adding a video and clicking on it:
http://pastebin.com/NbgJKPiu

![ifme-error](https://cloud.githubusercontent.com/assets/17182500/12984963/9a5803c0-d0f0-11e5-82cd-9e223b51736b.png)

Thanks for your support !

**Comment by Anime4000** [comment]
I aware of this problem... I suggest to downgrade.
in mean time, I fixing this issue,
