### ISSUE TITLE
Ubuntu server issue

### ISSUE THREAD

**Issue by hckweb** [Anime4000/IFME#87]
Working on mono-complete installed ubuntu 14.04.4 server.

with
./ifme -c -i list.xml 
command, i take this errors

![ekran goruntusu - 2016-03-12 00 14 33](https://cloud.githubusercontent.com/assets/15915850/13717451/450359fe-e7ea-11e5-8ccc-e42f92284ddc.png)

**Comment by Anime4000** [comment]
have `mono complete` installed?

**Comment by hckweb** [comment]
yes. mono-complete was installed from ubuntu repos.

**Comment by Anime4000** [comment]
it seem WinForms did not start

**Comment by hckweb** [comment]
It seems winforms already installed.
![ifme2](https://cloud.githubusercontent.com/assets/15915850/13901670/d3e42cb2-ee33-11e5-8cf9-f309687f4303.png)

and when i try this command on my local computer take this errors.
But I can use GUI without any error.
![ifme3](https://cloud.githubusercontent.com/assets/15915850/13901672/fba58462-ee33-11e5-8142-21cbf4fdb4d7.png)

**Comment by Anime4000** [comment]
index out of range... I look into this :)
