### ISSUE TITLE
Tune preset in GUI has no effect

### ISSUE THREAD

**Issue by master131** [Anime4000/IFME#88]
There seems to be an issue where if you attempt to set the Tune value in the Video tab to "grain" for instance, it seems to have no effect on x265.

For instance, this is the reported AQ settings in the command line window:

```
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 1 / 1.0 / 32 / 1
```

However, if you set Tune to "off" and manually add "--tune grain" to "Extra-command line:" you get this instead (which is the expected behaviour).

```
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 1 / 0.3 / 32 / 1
```

**Comment by Anime4000** [comment]
I'll fix this on next version of IFME (v7)
