### ISSUE TITLE
ADPCM sound format

### ISSUE THREAD

**Issue by SailorOnDaTea** [Anime4000/IFME#89]
Hello Anime4000, this is not a big issue but I would like you to keep in mind for your next release.

Some videos I previously downloaded contains ADPCM sound stream. When I encoded them IFME couldn't handle this type of audio format.

I could extract them to wav as standard pcm from original files using ffmpeg.
converted to aac with qaac
remuxed these aac files and ifme output mkv files(which had no sound) with mkvtoolnix.

I guess this is just a simple issue like those TTC font files before.

**Comment by SailorOnDaTea** [comment]
I forgot to add...
I am still using 5.1.13 (action 52)

**Comment by Anime4000** [comment]
edit format.ini
add new entry

**Comment by SailorOnDaTea** [comment]
ahh.. was simple like that?...
ok thanks!
