### ISSUE TITLE
2 bugs and 1 suggestions

### ISSUE THREAD

**Issue by Boooryss** [Anime4000/IFME#93]
ver. 6.1:
don't save files after finish (installing full ver. of mkvtoolnix in plugins folder repair that)
when encoding is on the slider on the task list don't work (scroll is fine)

suggestions for the new version:
add button "stop after finish actual task"

many thanks for this applications is unrivalled   ;D

**Comment by Anime4000** [comment]
I going to fix on next version

**Comment by SailorOnDaTea** [comment]
I am using v 5.1.13 until next v6 or v7 comes out :D

**Comment by Boooryss** [comment]
next problem is loading queue form the xlm file:
![scr01](https://cloud.githubusercontent.com/assets/18713943/15019434/4e2e7b2c-121e-11e6-913b-f9dd0c7ffc04.jpg)
[NewTxtFile.txt](https://github.com/Anime4000/IFME/files/249068/NewTxtFile.txt)
