### ISSUE TITLE
ifme 6 can`t find qaac plugin

### ISSUE THREAD

**Issue by kuh3h3** [Anime4000/IFME#95]
i tried qaac 2.58 plugin in recent ifme 6 x64 experimental.
used SailorOnDaTea`s recent ini and changed version number to 2.58.
but ifme can`t find qaac plugin. need any guid setting?
qaac itself works well.

Microsoft Windows Version 10.0.10586 2015 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd C:\Program Files\Internet Friendly Media Encoder\plugins\qaac64

C:\Program Files\Internet Friendly Media Encoder\plugins\qaac64>qaac64 --check
qaac 2.58, CoreAudioToolbox 7.10.5.0
libsoxconvolver 0.1.0
libsoxr-0.1.1
libsndfile-1.0.26
libFLAC 1.3.1
wavpackdll 4.80.0

C:\Program Files\Internet Friendly Media Encoder\plugins\qaac64>

**Comment by SailorOnDaTea** [comment]
It looks like you are using 64-bit version of QAAC and IFME v6+
On wiki I posted links for IFME v5.x and v5.1.4 uses different type of INI than previous. Also v6 uses different type of INI. If you go up in skydrive folders you can see there is another section for IFME v6.
![image](https://cloud.githubusercontent.com/assets/10913460/14938875/5def6a3e-0f3b-11e6-81f8-ae023c687d40.png)
It should look like this.
What matters is the difference between info and arguments sections. Ver number in INI files refer to qaac executable versions, they are not meant to represent plugin versions, they are informative. I mean, v2.52 means that ini file designed to work with qaac v2.52 but if you update qaac.exe file it may or may not work with new one depending on if they changed command line parameters.

**Comment by kuh3h3** [comment]
thanks for quick and kind reply. Now it works!!
