### ISSUE TITLE
DTS audio passthrough is not included

### ISSUE THREAD

**Issue by Magneticdud** [Anime4000/IFME#96]
When I select to do DTS (*.dca) audio passthrough, the file is not muxed, and in the log i see *.dca file invalid

**Comment by Anime4000** [comment]
you may edit format.ini file
dca = mka

**Comment by Magneticdud** [comment]
The line in format.ini gets deleted when I open IFME

**Comment by SailorOnDaTea** [comment]
does it also happen when you start with "-s" (skip update) ?

**Comment by Magneticdud** [comment]
if I start with -s (skipping updates), the line is not deleted

**Comment by mrmorg** [comment]
does this solve the DTS problem?
i get no audio when encoding DTS

**Comment by mrmorg** [comment]
I have added the -s to skip update and added dca = mka on the to end of the format.ini file but i still get:
Unable to find a suitable output format for 'audio0000_eng.dca' Invalid Argument

Please help

**Comment by Anime4000** [comment]
can you e-mail/facebook PM media file to me?
let me run experiment on that

**Comment by mrmorg** [comment]
its a 4gb file

**Comment by mrmorg** [comment]
can someone send me a copy of the format.ini file to ensure i have it correctly

**Comment by Anime4000** [comment]
Hi, can you try again, I updated `format.ini` repo

**Comment by Magneticdud** [comment]
Sorry for my late reply, after you updated format.ini on your repo, DTS audio passthrough is working fine.
It's now fixed and I close the issue. Thanks
