### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by hurricane51** [Anime4000/IFME#97]
Windows 10 x64 IFME Ver 5.1.5762.41900 x64

Fails at "Checking for Updates: FFmpeg" Stops at 54.59%.

**Comment by hurricane51** [comment]
Repeated attempts to run fail at the "Checking for Updates: FFmpeg" point. Often it gets to 100% but just stays there. I've tried installing in portable mode to no avail.

**Comment by Anime4000** [comment]
use arguments: `ifme.exe -s`

**Comment by hurricane51** [comment]
Some errors flashed quickly, but it launched the app OK. Thanks.
